### ISSUE TITLE
bcl-tests are crashing on startup against a system install in release mode 

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1099]
### Steps to Reproduce
From a clean install, on macOS, run the following:
1. `msbuild build-tools/xa-prep-tasks/xa-prep-tasks.csproj /p:Configuration=Release /p:HostOS=Darwin`
2. `msbuild build-tools/remap-assembly-ref/remap-assembly-ref.csproj /p:Configuration=Release`
3. `msbuild /t:Install tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj /p:FrameworkPathOverride=/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll`
4. `msbuild /t:RunTests tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj /p:AndroidSdkDirectory=~/Library/Developer/Xamarin/android-sdk-macosx`

or use the .apk file linked below:

https://microsoft-my.sharepoint.com/:u:/p/pecolli/EcpjRIgbIAZPgOVwrmlF9v4B2KGPRFNMZQEmqTQCHEpV2Q?e=80773f529fa64e058d696b473620f19e

### Expected Behavior
Tests should execute successfully as expected.

### Actual Behavior
Test run crashes on startup with the following:
```
12-12 16:10:32.727 13007 13007 I MonoDroid: System.ArgumentException: An item with the same key has already been added. Key: MonoTests.System.Security.Cryptography.CryptoConfigTest
```

### Version Information
monodroid/master/036e6d9d

### Log File

```
12-12 16:10:32.717 13007 13007 I MonoDroid: UNHANDLED EXCEPTION:
12-12 16:10:32.727 13007 13007 I MonoDroid: System.ArgumentException: An item with the same key has already been added. Key: MonoTests.System.Security.Cryptography.CryptoConfigTest
12-12 16:10:32.727 13007 13007 I MonoDroid:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <efaafba8c16043b198532214e63a585b>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <efaafba8c16043b198532214e63a585b>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (NUnit.Framework.Internal.TestSuite suite) [0x00015] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (NUnit.Framework.Internal.TestSuite suite) [0x00038] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (System.Reflection.Assembly assembly) [0x00037] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Xamarin.Android.NUnitLite.TestSuiteActivity.AddTest (System.Reflection.Assembly assembly) [0x00005] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Xamarin.Android.BclTests.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00019] in <731bde1ea7674d189c9bb47b53a31706>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <6a1b6a0768bc4e74b762836246a0d4b5>:0 
12-12 16:10:32.727 13007 13007 I MonoDroid:   at (wrapper dynamic-method) System.Object.a028ea48-bb62-4d53-88b2-bb4efad88e7b(intptr,intptr,intptr)
12-12 16:10:32.731 13007 13007 W zygote64: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
12-12 16:10:32.732 13007 13007 D AndroidRuntime: Shutting down VM
12-12 16:10:32.733 13007 13007 E AndroidRuntime: FATAL EXCEPTION: main
12-12 16:10:32.733 13007 13007 E AndroidRuntime: Process: Xamarin.Android.Bcl_Tests, PID: 13007
12-12 16:10:32.733 13007 13007 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.ArgumentException: An item with the same key has already been added. Key: MonoTests.System.Security.Cryptography.CryptoConfigTest
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <efaafba8c16043b198532214e63a585b>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <efaafba8c16043b198532214e63a585b>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (NUnit.Framework.Internal.TestSuite suite) [0x00015] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (NUnit.Framework.Internal.TestSuite suite) [0x00038] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Xamarin.Android.NUnitLite.AndroidRunner.AddTest (System.Reflection.Assembly assembly) [0x00037] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Xamarin.Android.NUnitLite.TestSuiteActivity.AddTest (System.Reflection.Assembly assembly) [0x00005] in <6dcf6e10f5614546aabd56bb3afb32e5>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Xamarin.Android.BclTests.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00019] in <731bde1ea7674d189c9bb47b53a31706>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <6a1b6a0768bc4e74b762836246a0d4b5>:0 
12-12 16:10:32.733 13007 13007 E AndroidRuntime:   at (wrapper dynamic-method) System.Object.a028ea48-bb62-4d53-88b2-bb4efad88e7b(intptr,intptr,intptr)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at xamarin.android.bcltests.MainActivity.n_onCreate(Native Method)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at xamarin.android.bcltests.MainActivity.onCreate(MainActivity.java:29)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6999)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6990)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-12 16:10:32.733 13007 13007 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-12 16:10:32.737  1140  5035 W ActivityManager:   Force finishing activity Xamarin.Android.Bcl_Tests/xamarin.android.bcltests.MainActivity
12-12 16:10:32.740 13007 13007 I Process : Sending signal. PID: 13007 SIG: 9
12-12 16:10:32.758  1140  1668 I ActivityManager: Process Xamarin.Android.Bcl_Tests (pid 13007) has died: cch  CEM 
12-12 16:10:32.758  1140  1173 W zygote64: kill(-13007, 9) failed: No such process
12-12 16:10:32.759  1140  1173 I zygote64: Successfully killed process cgroup uid 10152 pid 13007 in 0ms
```

**Comment by grendello** [comment]
This commit should have fixed the issue: https://github.com/xamarin/xamarin-android/commit/45868ce37fafd0be8142826c8d231f83c3f5b5ca

**Comment by jonpryor** [comment]
> This commit should have fixed the issue: 45868ce

...and therein lies the problem: the BCL tests from mono in 45868ce contains a "duplicate test" (`MonoTests.System.Security.Cryptography.CryptoConfigTest`) which causes `Xamarin.Android.NUnitLite.dll` to fail, which is why commit 45868ce *also* updates `Xamarin.Android.NUnitLite.dll`, so that it can support duplicate tests.

Therein lies the problem: the BCL test assemblies from mono/b06c50f3 *cannot* be used with a `Xamarin.Android.NUnitLite.dll` coming from Xamarin.Android 8.1 (d15-5) or earlier; d15-6 (master) *must* be used.

Which means a system Xamarin.Android *cannot* be used, but the bug/feature is that we support using a system Xamarin.Android!

There are two plausible solutions:

1. "Wait" until we have a system Xamarin.Android which supports conflicting type names, Xamarin.Android 8.2 or later.
2. Edit `Xamarin.Android.Bcl-Tests.csproj`/etc. so that one of the conflicting assemblies -- `monodroid_System_test.dll` or `monodroid_corlib_test.dll` -- is *excluded*.

(2) has the benefit of working *now*, but means a unit tests assembly *will not be run*.

Option (3) could be to fixup mono so that there *aren't* two separate `MonoTests.System.Security.Cryptography.CryptoConfigTest` types across all of the NUnit test assemblies, allowing older Xamarin.Android's to be used. I don't know if upstream would accept this.

**Comment by pjcollins** [comment]
@jonpryor in CI we're always matching the test source revision with the version under test, to avoid such a scenario as you describe here (d15-6 test source running against d15-5 binaries). However when I was working on this locally yesterday I didn't realize that the monodroid reference was so far behind. I was running against test sources from master and a system install of a master build, but they were nearly a month out of sync. I think we can close this without much concern once that reference is updated..

**Comment by jonpryor** [comment]
>  I didn't realize that the monodroid reference was so far behind

This is something we need to better address. I think we're going to have to follow [xamarin-macios](https://github.com/xamarin/xamarin-macios/blob/37683f771ed8914a91469bd1b8c73c919a5ef528/mk/xamarin.mk) and have xamarin-android refer to monodroid and have xamarin-android be the "build entry point", instead of the current setup. This would allow a new monodroid build for ~every xamarin-android commit.

This is something to work on for d15-7.

> I think we can close this without much concern once that reference is updated.

[The reference has been updated](https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=1196&host_id=163&revision_id=922770).
