### ISSUE TITLE
Support building with JDK 9.0.1

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1106]
### Steps to Reproduce

1. Install JDK 9.0.1.
1. Build `xamarin-android`.

### Expected Behavior

It builds!

### Actual Behavior

[It doesn't](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1224076); it fails when building `tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding`:

```
Task "Exec"
        Using task Exec from Microsoft.Build.Tasks.Exec, Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        Executing: ./gradlew assembleDebug --stacktrace
        Environment variables being passed to the tool:
                ANDROID_HOME=/Users/vsts/android-toolchain/sdk
                JAVA_HOME=/usr
        Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
        FAILURE: Build failed with an exception.
        * What went wrong:
        Could not determine java version from '9.0.1'.
        * Try:
        Run with --info or --debug option to get more log output.
        * Exception is:
        java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.
                at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
                at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
                at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
                at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
                at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
                at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
                at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
                at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
                at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
                at org.gradle.launcher.Main.doAction(Main.java:33)
                at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:564)
                at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
                at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
                at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:564)
                at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
                at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
                at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by jonpryor** [comment]
Fixed by PR #1107.
