### ISSUE TITLE
Exception in GenerateJavaStubs

### ISSUE THREAD

**Issue by garuma** [xamarin/xamarin-android#1431]
### Steps to Reproduce

1. Create a new Android project in Visual Studio (Single View App)
2. Run the `SetupDependenciesForDesigner` target with property `DesignTimeBuild` set to true and `AndroidUseManagedDesignTimeResourceGenerator` set to false.

### Expected Behavior

The target completes successfully-ish

### Actual Behavior

InvalidOperationException in `GenerateJavaStubs`:

```
[2018-03-15 18:19:43.6] WARN: : MSBuild error: C:\Program Files (x86)\Microsoft Visual Studio\Dogfood\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(571,2) MSB4018 The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteBinaryMapping(Stream o, Dictionary`2 mapping)
   at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteJavaToManaged(Stream output)
   at Xamarin.Android.Tasks.GenerateJavaStubs.UpdateWhenChanged(String path, Action`1 generator)
   at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Version Information

15.7

**Comment by dellis1972** [comment]
looks like [1] is not handling the case where the enumeration is empty. 
I'll do a PR.

[1] https://github.com/xamarin/java.interop/blob/429dc2a68579c9a820f03a7f09f35da3db9cd54a/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs#L193

**Comment by dellis1972** [comment]
PR is up to handle the exception

https://github.com/xamarin/java.interop/pull/311
