### ISSUE TITLE
Errors after upgrading to Xamarin.Android 8.2.0.15

### ISSUE THREAD

**Issue by samiyaakhtar** [xamarin/xamarin-android#1446]
### Error

The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Support.V7.App.ActionBarActivity' (defined in assembly 'Xamarin.Android.UserVoice, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.v7.AppCompat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.V7.App.ActionBarActivity
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()				

I've updated all my references but there's no Android.Support.V7.App that I can possibly add. Please advise. The new version of Xamarin sdk has broken this build completely.

**Comment by atsushieno** [comment]
There are likely many more changes you made after "upgrading" the product. The missing type `Android.Support.V7.App` is in Xamarin.Android.Support.v7.AppCompat nuget package. If you add the latest stable version of it (27.0.x), you will have to change your target application to Android 8.0.

Alternatively you can revert your Android Support nuget packages to the version you used before. Android support libraries requires very latest stable target SDK version (API level), by Google.

**Comment by atsushieno** [comment]
This should be marked as needs-info.

**Comment by siddh1004** [comment]
@samiyaakhtar I'm also facing this issue. Tried updating all the NuGet package to the latest version. Still, facing this issue. Could resolve this issue by setting the Linker to None but this would increase the size of apk.

**Comment by JonDouglas** [comment]
@siddh1004 Please open up a new issue describing your problem with a sample project.
