### ISSUE TITLE
ResolveLibraryProjectImports task failed unexpectedly on 15.7

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#1620]
### Steps to Reproduce

1. Download the following component - https://components.xamarin.com/view/devexpress-grid
2. Try to build HelloGrid.Android on 15.7
3. Build should fail with the **actual behavior** below

### Expected Behavior

Build should succeed and deploy.

### Actual Behavior

Project fails in Xamarin.Android.Common.targets:

```
The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'HelloGrid, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'HelloGrid.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()


C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1193	
```

### Diagnostic Build Log

https://gist.github.com/JonDouglas/9f580975a0e82b64acdca9818180310f

### Additional Information

This project includes references to old support libraries (v23), if you upgrade to a more recent version such as (v27), it will compile fine and deploy. The behavior is very intermittent but can typically be reproduced on first attempt at building with 15.7. I have tried this on 15.6 and it seems to work fine.

### Version Information

```
15.7 Preview 5
Xamarin.Android 8.3.0.18 (HEAD/1f8462ef1)
```

**Comment by dellis1972** [comment]
The odd thing is the `HelloGrid` project itself fails with 

```
Build FAILED.
1>
1>"C:\Users\dougl\Downloads\devexpress-grid-17.1.2.0test\devexpress-grid-17.1.2.0\samples\HelloGrid\HelloGrid\HelloGrid.csproj" (Rebuild target) (1) ->
1>(XamlC target) -> 
1>  C:\Users\dougl\Downloads\devexpress-grid-17.1.2.0test\devexpress-grid-17.1.2.0\samples\HelloGrid\packages\Xamarin.Forms.2.3.4.247\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.targets(68,4): error MSB4064: The "DebugType" parameter is not supported by the "XamlCTask" task. Verify the parameter exists on the task, and it is a settable public instance property.
1>  C:\Users\dougl\Downloads\devexpress-grid-17.1.2.0test\devexpress-grid-17.1.2.0\samples\HelloGrid\packages\Xamarin.Forms.2.3.4.247\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.targets(62,3): error MSB4063: The "XamlCTask" task could not be initialized with its input parameters. 
1>
1>    0 Warning(s)
1>    2 Error(s)
```

**Comment by dellis1972** [comment]
I think this is because the iOS project is referencing Xamarin.Forms 2.3.4.231 rather than 2.3.4.247. So its probably pot luck as to which of the `Xamarin.Forms.Build.Tasks` assemblies is loaded by the build system.

The 2.3.4.231 version does NOT have the `DebugType` parameter on the XamlCTask, but the 2.3.4.247 version does.

**Comment by dellis1972** [comment]
@JonDouglas can you confirm that every time you get this error the XamlC task had failed? If the XamlC task fails then the android project definitely won't build

I have been unable to repo this so far.

**Comment by JonDouglas** [comment]
@dellis1972 Yes I do get `XamlC` task failing at the same time. Should we boot this over to the forms team then? The larger concern came directly from an upgrade scenario where anyone using an older Xamarin.Forms will fail with a similar error pointing at Xamarin.Android. This behavior seemed to be introduced in 15.7, and from what I can tell we didn't add anything to `ResolveLibraryProjectImports` other than `AarLibraries`. If we should move it, I'll close this out and refile.

**Comment by dellis1972** [comment]
@JonDouglas this is not a forms issue, there isn't much they can do about it. I think its an IDE issue, its because there are two versions of the same Forms Build.Tasks and the MSBuild engine the IDE is using has the wrong one loaded... But I suspect the only solution is to make sure all the projects are using the same version of Xamarin.Forms. 

Did the XamlC errors appear in the IDE?
