### ISSUE TITLE
[layout binding] Layout binding usage crashes on startup

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1659]
### Steps to Reproduce

1. Build and run the attached project on device or emulator:

[App24.zip](https://github.com/xamarin/xamarin-android/files/1985216/App24.zip)

### Expected Behavior
Layout binding API usage compiles and runs.

### Actual Behavior
Attempting to access layout widgets via layout binding results in a crash.

### Version Information
VS 15.7
xamarin-android/master/5d8c2183

### Log File
```
05-08 18:38:08.730  1788  2010 I ActivityManager: Start proc 5026:Mono.Android.DebugRuntime/u0a85 for broadcast Mono.Android.DebugRuntime/com.xamarin.mono.android.ExternalStorageDirectory
05-08 18:38:08.740  5026  5026 W zygote  : Unexpected CPU variant for X86 using defaults: x86
05-08 18:38:08.743  1398  1398 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
05-08 18:38:08.789  1788  1834 D         : HostConnection::get() New Host Connection established 0x8a8c7ac0, tid 1834
05-08 18:38:08.811  2453  4998 I ChromeSync: [Persistence,AffiliationManager] Fetching affiliations from the server.
05-08 18:38:08.855  5010  5010 W monodroid: Trying to load sgen from: /data/app/App24.App24-6ByrID6XLgbkwSWqbXc2cw==/lib/x86/libmonosgen-2.0.so
05-08 18:38:08.896  5010  5010 W monodroid-gc: GREF GC Threshold: 46080
05-08 18:38:08.901  5010  5010 W monodroid: Calling into managed runtime init
05-08 18:38:08.904  2439  2516 D EGL_emulation: eglMakeCurrent: 0x9c785780: ver 2 0 (tinfo 0x9c7834b0)
05-08 18:38:08.940  2453  4977 I PeopleContactsSync: triggerPendingContactsCleanup: no accounts
05-08 18:38:08.996  2289  2300 I zygote  : Background concurrent copying GC freed 69529(4MB) AllocSpace objects, 9(180KB) LOS objects, 50% free, 5MB/10MB, paused 752us total 247.954ms
05-08 18:38:09.007  2453  3427 I Icing   : IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=36
05-08 18:38:09.010  2453  3725 I Icing   : IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=32
05-08 18:38:09.052  2337  2681 D EGL_emulation: eglMakeCurrent: 0x99c1a640: ver 2 0 (tinfo 0x99dffe00)
05-08 18:38:09.241  2337  2552 E ContentStoreEUAS: Failed to commit the deferred actions
05-08 18:38:09.336  2453  3424 W Conscrypt: Could not set socket write timeout:
05-08 18:38:09.342  2453  3424 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
05-08 18:38:09.342  2453  3424 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11947470:13)
05-08 18:38:09.411  2453  2879 I Icing   : App usage reports: 1
05-08 18:38:09.412  2453  2879 I Icing   : Usage reports ok 1, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
05-08 18:38:09.478  2453  2879 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
05-08 18:38:09.668  2453  3424 W Conscrypt: Could not set socket write timeout:
05-08 18:38:09.669  2453  3424 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
05-08 18:38:09.670  2453  3424 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11947470:13)
05-08 18:38:10.353  3366  3649 W SystemServiceRegistry: No service published for: persistent_data_block
05-08 18:38:10.375  5010  5010 I MonoDroid: UNHANDLED EXCEPTION:
05-08 18:38:10.433  5010  5010 I MonoDroid: System.MissingMethodException: Constructor on type 'Binding.activity_main' not found.
05-08 18:38:10.433  5010  5010 I MonoDroid:   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture) [0x00000] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at Android.App.Activity.SetContentView[T] () [0x00000] in <d5180d6ec835483c8e38ee22605ee618>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at App24.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00043] in <714ac3a743304019b53ef75d5f2413c2>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <d5180d6ec835483c8e38ee22605ee618>:0
05-08 18:38:10.433  5010  5010 I MonoDroid:   at (wrapper dynamic-method) System.Object.f5851852-9f11-4505-a78f-5528b8212621(intptr,intptr,intptr)
05-08 18:38:10.448  5010  5010 W zygote  : JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
05-08 18:38:10.457  5010  5010 D AndroidRuntime: Shutting down VM
05-08 18:38:10.460  3366  3649 D EGL_emulation: eglCreateContext: 0x99f4cd80: maj 2 min 0 rcv 2
--------- beginning of crash
05-08 18:38:10.460  5010  5010 E AndroidRuntime: FATAL EXCEPTION: main
05-08 18:38:10.460  5010  5010 E AndroidRuntime: Process: App24.App24, PID: 5010
05-08 18:38:10.460  5010  5010 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.MissingMethodException: Constructor on type 'Binding.activity_main' not found.
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture) [0x00000] in <0483892d46ec48f1be3f9f239175cafd>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at Android.App.Activity.SetContentView[T] () [0x00000] in <d5180d6ec835483c8e38ee22605ee618>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at App24.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00043] in <714ac3a743304019b53ef75d5f2413c2>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <d5180d6ec835483c8e38ee22605ee618>:0
05-08 18:38:10.460  5010  5010 E AndroidRuntime:   at (wrapper dynamic-method) System.Object.f5851852-9f11-4505-a78f-5528b8212621(intptr,intptr,intptr)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at md581f9b340ebe0b4f88925591d25cea609.MainActivity.n_onCreate(Native Method)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at md581f9b340ebe0b4f88925591d25cea609.MainActivity.onCreate(MainActivity.java:31)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6975)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6541)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-08 18:38:10.460  5010  5010 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-08 18:38:10.467  3366  3649 D EGL_emulation: eglMakeCurrent: 0x99f4cd80: ver 2 0 (tinfo 0x99dff940)
05-08 18:38:10.484  1788  3603 W ActivityManager:   Force finishing activity App24.App24/md581f9b340ebe0b4f88925591d25cea609.MainActivity
```

**Comment by jonpryor** [comment]
@grendello: I'm not sure *why* it fails, but the reasoning behind PR #1653 won't fix this.

I'm able to repro this on 7d7068afba1818a9b7e0051472a27ff8fbf961d9 -- *before* #1653 -- and our guess that the constructor was being linked away is not the case:

```
$ .../bin/Debug/bin/xabuild /v:diag /t:SignAndroidPackage /p:Configuration=Release > b.txt
$ mkdir t
$ cd t
$ unzip ../bin/Release/*-Signed.apk
$ monodis --method assemblies/App24.dll
...
########## Binding.activity_main
1: instance default int32 get_ResourceLayoutID ()  (param: 1 impl_flags: cil managed )
2: instance default void '.ctor' (class [Mono.Android]Xamarin.Android.Design.ILayoutBindingClient client)  (param: 1 impl_flags: cil managed )
3: instance default class [Xamarin.Android.Support.v7.AppCompat]Android.Support.V7.Widget.Toolbar get_toolbar ()  (param: 2 impl_flags: cil managed )
4: instance default class [Xamarin.Android.Support.Design]Android.Support.Design.Widget.FloatingActionButton get_fab ()  (param: 2 impl_flags: cil managed )
...
```

The `Binding.activity_main` constructor *exists* -- which makes sense, as the app assembly isn't linked by default -- yet it isn't being *found* by `Activity.SetContentView<T>()`. That's *weird*.

**Comment by grendello** [comment]
Closing the issue as it no longer applies to the current implementation of layout code-behind (we removed the instantiation via reflection)
