### ISSUE TITLE
Xamarin Android linking cannot access file

### ISSUE THREAD

**Issue by nd-srogers** [xamarin/xamarin-android#1706]
(This is a repost from [StackOverflow](https://stackoverflow.com/questions/49356825/xamarin-android-linking-cannot-access-file) at the request of Jon Douglas).

I have a Xamarin Android project that I am trying to use Sdk and User Assembly linking with.

If I set the Android project to Sdk Assembly Linking only, the APK is created and deployed successfully and works.

However, when I set Sdk and User Assembly linking, with no other changes, I get the following error only when I deploy. The solution builds succesfully.

```
The "LinkAssemblies" task failed unexpectedly.    
System.IO.IOException: The process cannot access the file '<path-to-project>\AppName\AppName.Android\obj\Release\android\assets\AppName.Core.dll' because it is being used by another process.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
    at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
    at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
    at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
    at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
    at Mono.Linker.Pipeline.Process(LinkContext context)
    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

AppName.Core.dll is another library project in my solution that is set to build as NetStandard 2.0.

I have looked through many other bug reports and forum posts regarding a similar issue to this, but most seem related to an earlier bug with Visual Studio 15.5.1 that has since been fixed.

The main Xamarin bug report is: https://bugzilla.xamarin.com/show_bug.cgi?id=56275 but was resolved in VS 15.2.
A forum topic (https://forums.xamarin.com/discussion/32976/updating-xamarin-broke-the-build-process-the-process-cannot-access-the-file-appname-dll-mdb) also talks about a similar issue being resolved in VS 15.5.1.
Other SO questions refer to older Xamarin or VS versions, or have unacceptable solutions (such as just turning off linking):
The Link Assemblies tasks failed unexpectedly Xamarin Forms
Regardless, I have tried just about every solution suggested in those links including:

closing and reopening Visual Studio
deleting /bin and /obj folders
opening Visual Studio as Administrator
running MsBuild from a command prompt with VS closed
As well as various combinations of the above.

My custom linker.xml contains an exception for my library project:
```
<?xml version="1.0" encoding="utf-8" ?>
<linker>    
    ...    
    <assembly fullname="AppName.Core" ></assembly>        
    ...        
</linker>
```

As this point I seem to have exhausted all available options and am no closer to a workable solution. Suggestions on solutions, workarounds, or other debugging paths to follow would be most appreciated.

My Android Options config:
![image](https://user-images.githubusercontent.com/33408863/40291870-17c5ce34-5d0b-11e8-9b5c-81d4770ed23d.png)

### Version Information
Visual Studio Version: 15.5.6
Xamarin Forms Version: 2.5.0.280555
Xamarin Version: 26.1.0.1

**Comment by JonDouglas** [comment]
15.5.6 is a fairly old version(January 2018) of Visual Studio as the latest Stable version is 15.7.1(May 2018). We fixed quite a few file locking issues in 15.5 and 15.6 releases. Please try to update to the latest version and see if you're stilling running into this specific file locking scenario. 

It would also be worth your time to use a tool such as [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see what is holding a handle to that file (`<path-to-project>\AppName\AppName.Android\obj\Release\android\assets\AppName.Core.dll`) such as `a Visual Studio instance (`devenv`).

**Comment by nd-srogers** [comment]
Sorry, I missed that when I copied the text from SO. I am currently using VS 15.6.7 and get the same error.

Looking in Process Explorer, MSBuild has a handle to that path:
![image](https://user-images.githubusercontent.com/33408863/40294205-f766bb14-5d17-11e8-97d4-d4bff2176c7d.png)

**Comment by JonDouglas** [comment]
@nd-srogers Can you please attach a project in which you experience this issue(And any reproduction steps)? Also can you please update to the latest Stable release (Which at this time is 15.7.1) just to ensure? I'll be able to investigate further with a reliable reproduction.

Thanks again!

**Comment by nd-srogers** [comment]
@JonDouglas I am unable to reproduce the error creating a solution from scratch. We have a fairly substantial solution so I've had to remove all unnecessary parts and anonymise it. While I was doing this, I continued to get the same linking error even when App.Core contained nothing except some model classes.

However, once I changed the solution and project names, I started getting compiler errors:

> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\App.Android.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\App.App.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\App.Core.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\FormsViewGroup.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Arch.Core.Common.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Arch.Lifecycle.Common.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Arch.Lifecycle.Runtime.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Glide.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Animated.Vector.Drawable.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Annotations.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Compat.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Core.UI.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Core.Utils.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.CustomTabs.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Design.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Fragment.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Media.Compat.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Transition.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v4.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v7.AppCompat.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v7.CardView.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v7.MediaRouter.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v7.Palette.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.v7.RecyclerView.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Android.Support.Vector.Drawable.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Forms.Core.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Forms.Platform.Android.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Forms.Platform.dll" does not exist.
> D:\Applications\Microsoft Visual Studio\2017\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1606,2): error MSB3375: The file "obj\Release\linksrc\Xamarin.Forms.Xaml.dll" does not exist.

I've attached the solution anyway, since this could be related as it talks about the linksrc directory. Make sure to set Release configuration in order for it to use full linking.

I tried the latest VS version last week, however it caused the entire application to fail to build for other reasons, causing me to have to uninstall and reinstall a previous version. I would prefer not to have to do this again unless it's confirmed this is the cause.

Thanks.

[LinkerRepro.zip](https://github.com/xamarin/xamarin-android/files/2025275/LinkerRepro.zip)

**Comment by jonathanpeppers** [comment]
@nd-srogers I removed usage of `AndroidClassParser`, `AndroidFastDeploymentType`, `AndroidPackageNamingPolicy`, and `AndroidErrorOnCustomJavaObject` in your project file, and I'm getting better results (I'm using VS Windows 15.7.4). `AndroidClassParser` is for Java binding projects, and since _I'm_ not familiar with the other MSBuild properties--I would avoid using them. Are there other MSBuild properties/targets you have here that could be to blame?

I had to remove usage of `@drawable/Icon`, since it is not included in the project.

I also get many errors with 9-patch images in this project:
```
1>ERROR: 9-patch image abc_switch_track_mtrl_alpha.9.png malformed.
1>       No marked region found along edge.
1>       Found along top edge.
```

Could you resolve the issues with images and upload a new repro? I'm afraid the project isn't going to run as-is.

**Comment by nd-srogers** [comment]
@jonathanpeppers I removed those elements from the project file, as well as `@drawable/Icon` and updated to Xamarin.Forms 3.0.0.561731 and version 27.0.2 of the Xamarin.Android support libraries. I don't see the error you're getting and I still get the same errors as above.

The believe the `abc_switch_track_mtrl_alpha` files comes from the AppCompat support library. No idea why it's malformed or what I can do to fix this.

I am currently in the process of porting our entire application into a new Solution built with Visual Studio 15.7.4 and Xam Forms 3, since I get the same errors `The file obj/Release/linksrc/***.dll` does not exist in our application.

Hopefully this will fix the issue because I have no other ideas.

**Comment by jonathanpeppers** [comment]
Ok, @nd-srogers I think you are experiencing two issues here:

1. The original file-locking issue with `LinkAssemblies`: I remember seeing a fix for this, I believe using 15.7.x fixes this (although perhaps even 15.6.x would)
1. `The file obj/Release/linksrc/***.dll` does not exist, I believe this might be caused by renaming your projects: a bug that still exists. If you can get this to occur, try deleting `bin` and `obj` directories and restarting VS to see if that solves the poblem?

I'll look into no. 2 tomorrow, and see if I can reproduce it. We have a big initiative to try to track down these "delete bin and obj"-related issues.
