### ISSUE TITLE
Aapt2 - Xamarin.Forms-Performance-Integration project crashes at runtime

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#1881]
### Steps to Reproduce

1. I noticed on Jenkins plots, this app has not been recording its times properly: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/plot/Tests%20times/#plot-8694435842335223270.csv
1. It made me think, "whoops, is this app crashing on startup?"
1. It appears to be since this build: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1033/
1. The build includes a commit that "fixes" Aapt2 support where it is properly enabled: https://github.com/xamarin/xamarin-android/commit/1c2e5fdd9d7b371ec9df05132f90f6996d71b1f4
1. I get a crash at runtime if I build/install the app with `bin/Debug/bin/xabuild /t:Install` and launch it
1. Changing the project to `<AndroidUseAapt2>False</AndroidUseAapt2>` fixes the crash

Crash log:
```
06-25 19:26:41.156 29645 29645 I MonoDroid: UNHANDLED EXCEPTION:
06-25 19:26:41.156 29645 29645 I MonoDroid: Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout ---> Android.Views.InflateException: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout ---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f02011d a=2}
06-25 19:26:41.157 29645 29645 I MonoDroid:    --- End of inner exception stack trace ---
06-25 19:26:41.157 29645 29645 I chatty  : uid=10103(Xamarin.Forms_Performance_Integration) identical 1 line
06-25 19:26:41.157 29645 29645 I MonoDroid:    --- End of inner exception stack trace ---
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00094] in <f0e20cf700b04c12b196f36c4720ea06>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00030] in <f0e20cf700b04c12b196f36c4720ea06>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root) [0x00046] in <f33011ab28e74826967e27e97c70d5db>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00061] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000fc] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager) [0x00031] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00015] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00022] in <27c17fe440cf491ba8255bcefade6e02>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at (wrapper dynamic-method) System.Object.7cd23379-425c-4cf7-9ec5-ac2a3e1e5185(intptr,intptr,intptr,intptr,intptr)
06-25 19:26:41.157 29645 29645 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000b9] in <f0e20cf700b04c12b196f36c4720ea06>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00066] in <f0e20cf700b04c12b196f36c4720ea06>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Android.App.Activity.OnStart () [0x0000c] in <f33011ab28e74826967e27e97c70d5db>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00000] in <1481f85a917c4f2b882ea161e9bc082f>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Xamarin.Forms.Performance.Integration.Droid.MainActivity.OnStart () [0x00016] in <12268734404e475fb9068218a597bed4>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x0000a] in <f33011ab28e74826967e27e97c70d5db>:0
06-25 19:26:41.157 29645 29645 I MonoDroid:   at (wrapper dynamic-method) System.Object.bb0b027b-d819-4413-aed7-818e7b3a6611(intptr,intptr)
06-25 19:26:41.157 29645 29645 I MonoDroid:   --- End of managed Android.Views.InflateException stack trace ---
06-25 19:26:41.157 29645 29645 I MonoDroid: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout
06-25 19:26:41.157 29645 29645 I MonoDroid: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout
06-25 19:26:41.157 29645 29645 I MonoDroid: Caused by: java.lang.reflect.InvocationTargetException
06-25 19:26:41.157 29645 29645 I MonoDroid:     at java.lang.reflect.Constructor.newInstance0(Native Method)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:51)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at xamarin.forms.performance.integration.MainActivity.n_onStart(Native Method)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at xamarin.forms.performance.integration.MainActivity.onStart(MainActivity.java:48)
06-25 19:26:41.157 29645 29645 I MonoDroid:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.Activity.performStart(Activity.java:7029)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.os.Looper.loop(Looper.java:164)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:6494)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-25 19:26:41.158 29645 29645 I MonoDroid: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f02011d a=2}
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.support.design.widget.TabLayout.<init>(TabLayout.java:303)
06-25 19:26:41.158 29645 29645 I MonoDroid:     at android.support.design.widget.TabLayout.<init>(TabLayout.java:261)
06-25 19:26:41.158 29645 29645 I MonoDroid:     ... 31 more
06-25 19:26:41.158 29645 29645 I MonoDroid:
06-25 19:26:41.158 29645 29645 D AndroidRuntime: Shutting down VM
06-25 19:26:41.163 29645 29645 E AndroidRuntime: FATAL EXCEPTION: main
06-25 19:26:41.163 29645 29645 E AndroidRuntime: Process: Xamarin.Forms_Performance_Integration, PID: 29645
06-25 19:26:41.163 29645 29645 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{Xamarin.Forms_Performance_Integration/xamarin.forms.performance.integration.MainActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-25 19:26:41.163 29645 29645 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout
06-25 19:26:41.163 29645 29645 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout
06-25 19:26:41.163 29645 29645 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:51)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at xamarin.forms.performance.integration.MainActivity.n_onStart(Native Method)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at xamarin.forms.performance.integration.MainActivity.onStart(MainActivity.java:48)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7029)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-25 19:26:41.163 29645 29645 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f02011d a=2}
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.design.widget.TabLayout.<init>(TabLayout.java:303)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        at android.support.design.widget.TabLayout.<init>(TabLayout.java:261)
06-25 19:26:41.163 29645 29645 E AndroidRuntime:        ... 31 more
06-25 19:26:41.173 16683 17478 W ActivityManager:   Force finishing activity Xamarin.Forms_Performance_Integration/xamarin.forms.performance.integration.MainActivity
06-25 19:26:41.178 16683 16699 I ActivityManager: Showing crash dialog for package Xamarin.Forms_Performance_Integration
```

### Expected Behavior

Enabling Aapt2 should not crash our Xamarin.Forms test project.

### Actual Behavior

Enabling Aapt2 causes our Xamarin.Forms test project to crash.

### Version Information

xamarin-android master at: 0b5ce8fb5e702b06c1d7f1d8d08a91b14b0e675d

Presumably has done this since: 1c2e5fdd9d7b371ec9df05132f90f6996d71b1f4

**Comment by jonathanpeppers** [comment]
I tried a `File | New Xamarin.Forms Project` and it worked fine with `$(AndroidUseAapt2)=True`.

It must be something specific failing with this test project.

**Comment by dellis1972** [comment]
so we are hitting [1] or [2]. Which means both of those have a value.. but one or the other does not exist in the package.

[1] https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TabLayout.java#335
[2] https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TabLayout.java#343

**Comment by dellis1972** [comment]
even weirder.. the resource its looking for its in the apk

```
./aapt d resources /Users/dean/Documents/Sandbox/Xamarin/xamarin-android/bin/TestRelease/Xamarin.Forms_Performance_Integration-Signed.apk | grep 0x7f02011d
      spec resource 0x7f02011d Xamarin.Forms_Performance_Integration:attr/textColorError: flags=0x00000000
        resource 0x7f02011d Xamarin.Forms_Performance_Integration:attr/textColorError: <bag>
```

**Comment by jonathanpeppers** [comment]
@dellis1972 could it be something to do with `-` in the project name? it looks like it's getting switched to an underscore.

**Comment by dellis1972** [comment]
I think those come from the `package="Xamarin.Forms_Performance_Integration"` in the manifest. Most of my others are `com.xamarin.foo`. Will see if that changes anything

**Comment by dellis1972** [comment]
na, changing the `package` didn't change anything
