### ISSUE TITLE
AOT `.so` files need to have `DT_SONAME` set.

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#1910]
### Steps to Reproduce

1. Build `samples/HelloWorld` with AOT enabled:

        cd samples/HelloWorld
        msbuild /p:AotAssemblies=True /p:Configuration=Release /t:Install

2. Run the app
3. Read `adb logcat`

`adb logcat` contains messages from the linker, e.g.:

```
linker  : /data/app/com.xamarin.android.helloworld-LMCh2_phMORAYd6mcwj0tw==/lib/arm/libaot-mscorlib.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-mscorlib.dll.so"
```

Fun fact! If you build [Xamarin.Forms.ControlGallery.Android](https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.ControlGallery.Android) with AOT and LLVM enabled, these linker messages *appear* to "contribute" ~1.4s to process startup!

```
Time	Device Name	Type	PID	Tag	Message
07-02 18:18:15.552	5x	Info	1591	ActivityManager	Start proc 30122:AndroidControlGallery.AndroidControlGallery/u0a94 for activity AndroidControlGallery.AndroidControlGallery/md546303760447087909496d02dc7b17ae8.Activity1
07-02 18:18:15.645	5x	Warning	30122	zygote	Unexpected CPU variant for X86 using defaults: x86
07-02 18:18:17.088	5x	Warning	30122	monodroid	Trying to load sgen from: /data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libmonosgen-2.0.so
07-02 18:18:17.376	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-mscorlib.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-mscorlib.dll.so"
07-02 18:18:17.521	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.ControlGallery.Android.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.ControlGallery.Android.dll.so"
07-02 18:18:17.539	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Mono.Android.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Mono.Android.dll.so"
07-02 18:18:17.582	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.dll.so"
07-02 18:18:17.595	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Mono.Security.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Mono.Security.dll.so"
07-02 18:18:17.608	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Java.Interop.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Java.Interop.dll.so"
	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@12685026@12.6.85 (040700-197041431):13)
	at java.lang.reflect.Method.invoke(Native Method)
07-02 18:18:17.745	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Core.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Core.dll.so"
	at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:175)
	at libcore.io.Linux.setsockoptTimeval(Native Method)
07-02 18:18:17.806	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Xml.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Xml.dll.so"
07-02 18:18:17.877	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Platform.Android.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Platform.Android.dll.so"
07-02 18:18:17.893	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Core.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Core.dll.so"
07-02 18:18:17.900	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Net.Http.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Net.Http.dll.so"
07-02 18:18:17.909	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.v7.AppCompat.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.v7.AppCompat.dll.so"
07-02 18:18:17.943	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Fragment.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Fragment.dll.so"
07-02 18:18:17.950	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Core.UI.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Core.UI.dll.so"
07-02 18:18:17.966	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Runtime.Serialization.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Runtime.Serialization.dll.so"
07-02 18:18:17.980	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.ServiceModel.Internals.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.ServiceModel.Internals.dll.so"
07-02 18:18:17.990	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Design.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Design.dll.so"
07-02 18:18:18.030	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.v7.RecyclerView.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.v7.RecyclerView.dll.so"
07-02 18:18:18.049	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Compat.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Compat.dll.so"
07-02 18:18:18.054	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.v7.CardView.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.v7.CardView.dll.so"
07-02 18:18:18.058	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-FormsViewGroup.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-FormsViewGroup.dll.so"
07-02 18:18:18.078	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Controls.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Controls.dll.so"
07-02 18:18:18.103	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Xaml.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Xaml.dll.so"
07-02 18:18:18.138	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.CustomAttributes.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.CustomAttributes.dll.so"
07-02 18:18:18.176	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Maps.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Maps.dll.so"
07-02 18:18:18.204	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Newtonsoft.Json.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Newtonsoft.Json.dll.so"
07-02 18:18:18.240	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Numerics.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Numerics.dll.so"
07-02 18:18:18.246	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-System.Xml.Linq.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-System.Xml.Linq.dll.so"
07-02 18:18:18.296	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Microsoft.CSharp.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Microsoft.CSharp.dll.so"
07-02 18:18:18.315	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Plugin.DeviceInfo.Abstractions.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Plugin.DeviceInfo.Abstractions.dll.so"
07-02 18:18:18.319	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Plugin.DeviceInfo.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Plugin.DeviceInfo.dll.so"
07-02 18:18:18.322	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Plugin.CurrentActivity.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Plugin.CurrentActivity.dll.so"
07-02 18:18:18.326	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Platform.Android.AppLinks.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Platform.Android.AppLinks.dll.so"
07-02 18:18:18.333	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Firebase.AppIndexing.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Firebase.AppIndexing.dll.so"
07-02 18:18:18.344	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.GooglePlayServices.Basement.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.GooglePlayServices.Basement.dll.so"
07-02 18:18:18.352	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.GooglePlayServices.Base.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.GooglePlayServices.Base.dll.so"
07-02 18:18:18.358	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.GooglePlayServices.Tasks.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.GooglePlayServices.Tasks.dll.so"
07-02 18:18:18.365	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Maps.Android.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Maps.Android.dll.so"
07-02 18:18:18.372	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.GooglePlayServices.Maps.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.GooglePlayServices.Maps.dll.so"
07-02 18:18:18.380	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PagesGallery.Droid.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PagesGallery.Droid.dll.so"
07-02 18:18:18.383	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PagesGallery.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PagesGallery.dll.so"
07-02 18:18:18.388	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Pages.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Pages.dll.so"
07-02 18:18:18.398	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Microsoft.Azure.Mobile.Client.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Microsoft.Azure.Mobile.Client.dll.so"
07-02 18:18:18.408	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.CustomTabs.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.CustomTabs.dll.so"
07-02 18:18:18.415	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PCLCrypto.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PCLCrypto.dll.so"
07-02 18:18:18.420	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Validation.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Validation.dll.so"
07-02 18:18:18.422	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Arch.Core.Common.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Arch.Core.Common.dll.so"
07-02 18:18:18.424	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Arch.Lifecycle.Common.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Arch.Lifecycle.Common.dll.so"
07-02 18:18:18.427	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Arch.Lifecycle.Runtime.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Arch.Lifecycle.Runtime.dll.so"
07-02 18:18:18.430	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Animated.Vector.Drawable.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Animated.Vector.Drawable.dll.so"
07-02 18:18:18.444	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Annotations.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Annotations.dll.so"
07-02 18:18:18.494	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Core.Utils.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Core.Utils.dll.so"
07-02 18:18:18.500	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Media.Compat.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Media.Compat.dll.so"
07-02 18:18:18.501	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Transition.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Transition.dll.so"
07-02 18:18:18.506	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.v4.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.v4.dll.so"
07-02 18:18:18.513	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.v7.Palette.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.v7.Palette.dll.so"
07-02 18:18:18.523	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Android.Support.Vector.Drawable.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Android.Support.Vector.Drawable.dll.so"
07-02 18:18:18.555	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Firebase.Common.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Firebase.Common.dll.so"
07-02 18:18:18.572	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.Forms.Platform.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.Forms.Platform.dll.so"
07-02 18:18:18.573	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Xamarin.GooglePlayServices.AppIndexing.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Xamarin.GooglePlayServices.AppIndexing.dll.so"
07-02 18:18:18.575	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PInvoke.BCrypt.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PInvoke.BCrypt.dll.so"
07-02 18:18:18.580	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PInvoke.Kernel32.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PInvoke.Kernel32.dll.so"
07-02 18:18:18.583	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-PInvoke.Windows.Core.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-PInvoke.Windows.Core.dll.so"
07-02 18:18:18.587	5x	Warning	30122	monodroid-gc	GREF GC Threshold: 46080
	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@12685026@12.6.85 (040700-197041431):13)
	at java.lang.reflect.Method.invoke(Native Method)
07-02 18:18:18.621	5x	Warning	30122	monodroid	Calling into managed runtime init
07-02 18:18:19.287	5x	Info	30122	FirebaseInitProvider	FirebaseApp initialization unsuccessful
07-02 18:18:19.668	5x	Warning	30122	linker	/data/app/AndroidControlGallery.AndroidControlGallery-3tnRD63AYnrm5K8x_JRvAw==/lib/x86/libaot-Mono.Android.Export.dll.so: is missing DT_SONAME will use basename as a replacement: "libaot-Mono.Android.Export.dll.so"
```

Would it be possible for mono's AOT compilers to set `DT_SONAME` as part of the `.so` generation?

**Comment by vargaz** [comment]
What should the soname be ? Does it need to be unique among the assemblies in the process ? We can add a soname=<soname> aot argument which monodroid can set, would that work ?

**Comment by atsushieno** [comment]
SONAME should be the same as the fallback values indicated by the Android system log. (It would have been problematic if the files are like `*.so.1` but they are so far just `*.so` so they just work. Yet linking perf. improvements is surprisingly big...?)

**Comment by radekdoulik** [comment]
How is this going? I still see the warnings in the logcat output of our tests. I guess the 1.4sec time probably also contains the time to load the libraries?

Part of current Mono.Android_Tests logcat output:
```
11-06 03:34:23.028  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-mscorlib.dll.so" has no DT_SONAME (will use libaot-mscorlib.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.039  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-Mono.Android-Tests.dll.so" has no DT_SONAME (will use libaot-Mono.Android-Tests.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.040  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.dll.so" has no DT_SONAME (will use libaot-System.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.042  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-Mono.Security.dll.so" has no DT_SONAME (will use libaot-Mono.Security.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.043  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-Xamarin.Android.NUnitLite.dll.so" has no DT_SONAME (will use libaot-Xamarin.Android.NUnitLite.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.044  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.Xml.dll.so" has no DT_SONAME (will use libaot-System.Xml.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.045  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-Mono.Android.dll.so" has no DT_SONAME (will use libaot-Mono.Android.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.046  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.Core.dll.so" has no DT_SONAME (will use libaot-System.Core.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.047  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.Net.Http.dll.so" has no DT_SONAME (will use libaot-System.Net.Http.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.049  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-Java.Interop.dll.so" has no DT_SONAME (will use libaot-Java.Interop.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.050  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-TestRunner.Core.dll.so" has no DT_SONAME (will use libaot-TestRunner.Core.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.051  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.IO.Compression.dll.so" has no DT_SONAME (will use libaot-System.IO.Compression.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.052  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-System.IO.Compression.FileSystem.dll.so" has no DT_SONAME (will use libaot-System.IO.Compression.FileSystem.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
11-06 03:34:23.053  8802  8802 W linker  : Warning: "/data/app/Mono.Android_Tests-zh3eUS7-fQ19LSgz1Uvsqg==/lib/x86/libaot-TestRunner.NUnit.dll.so" has no DT_SONAME (will use libaot-TestRunner.NUnit.dll.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22)
```
