### ISSUE TITLE
Deployment failed on android simulator

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#1964]
### Steps to Reproduce

1. Select a google android 8.0 simulator
2. CTRL-F5 ro build/run the android app

### Expected Behavior
The app runs

### Actual Behavior
The simulator is started, but not the app. And the deployment failed.

Note that with the previous version of visual studo 15.7.4 it was working fine.
Note that multidex is on, use shared runtime and fast deployment are on too. Enable debuggin is on, and use the concurrent garbage collector too. 
The other options are off.

### Version Information
VS 15.7.5

### Log File
```
4>DEBUG RunShellCommand emulator-5554 am broadcast -a "mono.android.intent.action.PACKAGE_VERSIONS" -e "packages" "Mono.Android.DebugRuntime,Mono.Android.Platform.ApiLevel_27,com.cosmoconnected.cosmoconnected" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.PackageVersions"
4>[END] 
4> Deployment failed
4>Mono.AndroidTools.AdbException: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée 127.0.0.1:5037 ---> System.Net.Sockets.SocketException: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée 127.0.0.1:5037
4>   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
4>   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
4>   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
4>   at Mono.AndroidTools.Adb.AdbClient.EndConnect(IAsyncResult asyncResult) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 141
4>   at Mono.AndroidTools.Adb.AdbClient.ConnectTransport_OnConnected(IAsyncResult result) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 186
4>   --- End of inner exception stack trace ---
4>   at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Util\AggregateAsyncResult.cs:line 72
4>   at Mono.AndroidTools.Adb.AdbClient.EndConnectTransport(IAsyncResult asyncResult) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 207
4>   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
4>Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée 127.0.0.1:5037
4>   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
4>   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
4>   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
4>   at Mono.AndroidTools.Adb.AdbClient.EndConnect(IAsyncResult asyncResult) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 141
4>   at Mono.AndroidTools.Adb.AdbClient.ConnectTransport_OnConnected(IAsyncResult result) in E:\A\_work\7\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 186
4>Done executing task "InstallPackageAssemblies".
```

**Comment by softlion** [comment]
I updated android sdks, tools, simulators and others using android studio. VS is now able to deploy again correcty. Hence i close the issue.
