### ISSUE TITLE
Android App with Proguard enabled fails to build in Release mode

### ISSUE THREAD

**Issue by OlgaBoiarshynova** [xamarin/xamarin-android#2007]
### Steps to Reproduce

1. Create new Android App project
2. Set the configuration to Release
3. Select 'Enable Proguard' checkbox in Android project options
4. Save changes
5. Build solution

### Expected Behavior
Build succeded

### Actual Behavior
Build failed with " "java" exited with code 1." error
### Version Information

http://xqa.blob.core.windows.net/gist/log-41f6c488213b4fde8589d3c1c517b668.txt

Uses XA Version: 9.0.0.18

### Log File

Diagnostic build output:
http://xqa.blob.core.windows.net/gist/log-d2228aeedaf348229901105639ceed28.txt

IDE log:
http://xqa.blob.core.windows.net/gist/TestEnableProguard.Ide.log.180726133733-c6efd278b0904f24be5fc76a22cee454.txt

> VS bug [#655384](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/655384)

**Comment by JonDouglas** [comment]
@OlgaBoiarshynova Can you please attach a [Diagnostic MSBuild Output Log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) to this issue? This will help us determine why `"java" exited with code 1."`. 

Thanks in advance!

**Comment by pjcollins** [comment]
I've updated the description to include the relevant log content. In this case, proguard is bailing with a bunch of warnings about unresolved references, as I've pasted below.

I've finally managed to reproduce this with the following steps, and it requires compiling with a `Mono.Android.dll` that is newer than your `android.jar` file.
1) Ensure that API 27 is your latest installed Android platform SDK version.
2) Create a new max compat template. This should result in the following elements being written to your .csproj file:
* `<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>`
* `<AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>`
3) Enable proguard in the release configuration and build.

```
 PROGUARD_HOME=/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/proguard
    /usr/bin/java -jar /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/proguard/lib/proguard.jar -include '/Users/builder/Library/Developer/Xamarin/android-sdk-macosx//tools/proguard/proguard-android.txt' -include 'obj/Release/proguard/proguard_xamarin.cfg' -include 'obj/Release/proguard/proguard_project_references.cfg' -include 'obj/Release/proguard/proguard_project_primary.cfg' -include '/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/packages/Xamarin.Android.Arch.Lifecycle.Runtime.1.0.3/build/MonoAndroid80/../../proguard/proguard.txt' -include '/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/packages/Xamarin.Android.Support.Core.UI.27.0.2/build/MonoAndroid81/../../proguard/proguard.txt' -include '/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/packages/Xamarin.Android.Support.Media.Compat.27.0.2/build/MonoAndroid81/../../proguard/proguard.txt' -include '/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/packages/Xamarin.Android.Support.Animated.Vector.Drawable.27.0.2/build/MonoAndroid81/../../proguard/proguard.txt' -injars "'obj/Release/android/bin/classes/../classes.zip'(!META-INF/MANIFEST.MF):'/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v9.0/mono.android.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/1/jl/arch-core-common.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/10/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/11/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/12/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/2/jl/arch-lifecycle-common.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/3/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/4/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/6/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/7/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/8/jl/bin/classes.jar'(!META-INF/MANIFEST.MF):'obj/Release/lp/9/jl/bin/classes.jar'(!META-INF/MANIFEST.MF)" -libraryjars '/Users/builder/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-27/android.jar' -outjars obj/Release/proguard/__proguard_output__.jar -optimizations !code/allocation/variable 
    ProGuard, version 5.3.2
    Note: the configuration doesn't specify which class members to keep for class 'android.arch.core.internal.SafeIterableMap$SupportRemove'
    Note: there were 1 '-keepclassmembers' options that didn't specify class
          members. You should specify at least some class members or consider
          if you just need '-keep'.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#classmembers)
    Reading input...
    Reading program zip [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/android/bin/classes.zip] (filtered)
    Reading program jar [/Library/Frameworks/Xamarin.Android.framework/Versions/9.0.0-18/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v9.0/mono.android.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/1/jl/arch-core-common.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/10/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/11/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/12/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/2/jl/arch-lifecycle-common.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/3/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/4/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/6/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/7/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/8/jl/bin/classes.jar] (filtered)
    Reading program jar [/Users/builder/agent/_work/r27/a/XQA/XQA.VisualStudioMac/TestResults/61c53ceb/TestEnableProguard/Temp/DroidApp/DroidApp/obj/Release/lp/9/jl/bin/classes.jar] (filtered)
    Reading library jar [/Users/builder/Library/Developer/Xamarin/android-sdk-macosx/platforms/android-27/android.jar]
    Initializing...
    Note: the configuration refers to the unknown class 'com.google.vending.licensing.ILicensingService'
    Note: the configuration refers to the unknown class 'com.android.vending.licensing.ILicensingService'
    Note: the configuration refers to the unknown class 'android.support.annotation.Keep'
    Note: the configuration refers to the unknown class 'android.support.annotation.Keep'
    Note: the configuration refers to the unknown class 'android.support.annotation.Keep'
    Note: the configuration refers to the unknown class 'android.support.annotation.Keep'
    Note: the configuration refers to the unknown class 'android.support.annotation.Keep'
    Note: android.support.v4.app.NotificationCompatJellybean calls 'Field.getType'
    PROGUARD : warning : mono.android.app.admin.DevicePolicyManager_OnClearApplicationUserDataListenerImplementor: can't find superclass or interface android.app.admin.DevicePolicyManager$OnClearApplicationUserDataListener
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find superclass or interface android.graphics.ImageDecoder$OnHeaderDecodedListener
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find superclass or interface android.graphics.ImageDecoder$OnPartialImageListener
    PROGUARD : warning : mono.android.media.MediaPlayer_OnMediaTimeDiscontinuityListenerImplementor: can't find superclass or interface android.media.MediaPlayer$OnMediaTimeDiscontinuityListener
    PROGUARD : warning : mono.android.media.MediaPlayer_OnSubtitleDataListenerImplementor: can't find superclass or interface android.media.MediaPlayer$OnSubtitleDataListener
    PROGUARD : warning : mono.android.os.StrictMode_OnThreadViolationListenerImplementor: can't find superclass or interface android.os.StrictMode$OnThreadViolationListener
    PROGUARD : warning : mono.android.os.StrictMode_OnVmViolationListenerImplementor: can't find superclass or interface android.os.StrictMode$OnVmViolationListener
    PROGUARD : warning : mono.android.se.omapi.SEService_OnConnectedListenerImplementor: can't find superclass or interface android.se.omapi.SEService$OnConnectedListener
    PROGUARD : warning : mono.android.view.View_OnUnhandledKeyEventListenerImplementor: can't find superclass or interface android.view.View$OnUnhandledKeyEventListener
    PROGUARD : warning : mono.android.app.admin.DevicePolicyManager_OnClearApplicationUserDataListenerImplementor: can't find referenced class android.app.admin.DevicePolicyManager$OnClearApplicationUserDataListener
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$OnHeaderDecodedListener
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$ImageInfo
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$Source
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$ImageInfo
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$Source
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$ImageInfo
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnHeaderDecodedListenerImplementor: can't find referenced class android.graphics.ImageDecoder$Source
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find referenced class android.graphics.ImageDecoder$OnPartialImageListener
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find referenced class android.graphics.ImageDecoder$DecodeException
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find referenced class android.graphics.ImageDecoder
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find referenced class android.graphics.ImageDecoder$DecodeException
    PROGUARD : warning : mono.android.graphics.ImageDecoder_OnPartialImageListenerImplementor: can't find referenced class android.graphics.ImageDecoder$DecodeException
    PROGUARD : warning : mono.android.media.MediaPlayer_OnMediaTimeDiscontinuityListenerImplementor: can't find referenced class android.media.MediaPlayer$OnMediaTimeDiscontinuityListener
    PROGUARD : warning : mono.android.media.MediaPlayer_OnSubtitleDataListenerImplementor: can't find referenced class android.media.MediaPlayer$OnSubtitleDataListener
    PROGUARD : warning : mono.android.media.MediaPlayer_OnSubtitleDataListenerImplementor: can't find referenced class android.media.SubtitleData
    PROGUARD : warning : mono.android.media.MediaPlayer_OnSubtitleDataListenerImplementor: can't find referenced class android.media.SubtitleData
    PROGUARD : warning : mono.android.os.StrictMode_OnThreadViolationListenerImplementor: can't find referenced class android.os.StrictMode$OnThreadViolationListener
    PROGUARD : warning : mono.android.os.StrictMode_OnThreadViolationListenerImplementor: can't find referenced class android.os.strictmode.Violation
    PROGUARD : warning : mono.android.os.StrictMode_OnThreadViolationListenerImplementor: can't find referenced class android.os.strictmode.Violation
    PROGUARD : warning : mono.android.os.StrictMode_OnVmViolationListenerImplementor: can't find referenced class android.os.StrictMode$OnVmViolationListener
    PROGUARD : warning : mono.android.os.StrictMode_OnVmViolationListenerImplementor: can't find referenced class android.os.strictmode.Violation
    PROGUARD : warning : mono.android.os.StrictMode_OnVmViolationListenerImplementor: can't find referenced class android.os.strictmode.Violation
    PROGUARD : warning : mono.android.se.omapi.SEService_OnConnectedListenerImplementor: can't find referenced class android.se.omapi.SEService$OnConnectedListener
    PROGUARD : warning : mono.android.se.omapi.SEService_OnConnectedListenerImplementor: can't find referenced class android.se.omapi.SEService
    PROGUARD : warning : mono.android.view.View_OnUnhandledKeyEventListenerImplementor: can't find referenced class android.view.View$OnUnhandledKeyEventListener
    Note: android.support.v4.app.FragmentTransition: can't find dynamically referenced class android.support.transition.FragmentTransitionSupport
    Note: android.support.v4.graphics.TypefaceCompatApi24Impl: can't find dynamically referenced class android.graphics.FontFamily
    Note: android.support.v4.graphics.TypefaceCompatApi26Impl: can't find dynamically referenced class android.graphics.FontFamily
    Note: android.support.v4.media.ParceledListSliceAdapterApi21: can't find dynamically referenced class android.content.pm.ParceledListSlice
    Note: android.support.v4.text.ICUCompat: can't find dynamically referenced class libcore.icu.ICU
    Note: android.support.v4.text.ICUCompat: can't find dynamically referenced class libcore.icu.ICU
    Note: android.support.v7.app.ResourcesFlusher: can't find dynamically referenced class android.content.res.ThemedResourceCache
    Note: android.support.v7.widget.DrawableUtils: can't find dynamically referenced class android.graphics.Insets
    Note: the configuration keeps the entry point 'android.support.graphics.drawable.VectorDrawableCompat$VPath { void setPathData(android.support.v4.graphics.PathParser$PathDataNode[]); }', but not the descriptor class 'android.support.v4.graphics.PathParser$PathDataNode'
    Note: the configuration keeps the entry point 'android.support.v4.view.ViewPager { void setAdapter(android.support.v4.view.PagerAdapter); }', but not the descriptor class 'android.support.v4.view.PagerAdapter'
    Note: the configuration keeps the entry point 'android.support.v4.view.ViewPager { void setOnPageChangeListener(android.support.v4.view.ViewPager$OnPageChangeListener); }', but not the descriptor class 'android.support.v4.view.ViewPager$OnPageChangeListener'
    Note: the configuration keeps the entry point 'android.support.v4.view.ViewPager { android.support.v4.view.ViewPager$OnPageChangeListener setInternalPageChangeListener(android.support.v4.view.ViewPager$OnPageChangeListener); }', but not the descriptor class 'android.support.v4.view.ViewPager$OnPageChangeListener'
    Note: the configuration keeps the entry point 'android.support.v4.widget.DrawerLayout { void setDrawerListener(android.support.v4.widget.DrawerLayout$DrawerListener); }', but not the descriptor class 'android.support.v4.widget.DrawerLayout$DrawerListener'
    Note: the configuration keeps the entry point 'android.support.v4.widget.NestedScrollView { void setOnScrollChangeListener(android.support.v4.widget.NestedScrollView$OnScrollChangeListener); }', but not the descriptor class 'android.support.v4.widget.NestedScrollView$OnScrollChangeListener'
    Note: the configuration keeps the entry point 'android.support.v4.widget.SlidingPaneLayout { void setPanelSlideListener(android.support.v4.widget.SlidingPaneLayout$PanelSlideListener); }', but not the descriptor class 'android.support.v4.widget.SlidingPaneLayout$PanelSlideListener'
    Note: the configuration keeps the entry point 'android.support.v4.widget.SwipeRefreshLayout { void setOnRefreshListener(android.support.v4.widget.SwipeRefreshLayout$OnRefreshListener); }', but not the descriptor class 'android.support.v4.widget.SwipeRefreshLayout$OnRefreshListener'
    Note: the configuration keeps the entry point 'android.support.v4.widget.SwipeRefreshLayout { void setOnChildScrollUpCallback(android.support.v4.widget.SwipeRefreshLayout$OnChildScrollUpCallback); }', but not the descriptor class 'android.support.v4.widget.SwipeRefreshLayout$OnChildScrollUpCallback'
    Note: the configuration keeps the entry point 'android.support.v7.view.menu.ActionMenuItemView { void setItemInvoker(android.support.v7.view.menu.MenuBuilder$ItemInvoker); }', but not the descriptor class 'android.support.v7.view.menu.MenuBuilder$ItemInvoker'
    Note: the configuration keeps the entry point 'android.support.v7.view.menu.ActionMenuItemView { void setPopupCallback(android.support.v7.view.menu.ActionMenuItemView$PopupCallback); }', but not the descriptor class 'android.support.v7.view.menu.ActionMenuItemView$PopupCallback'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActionBarContainer { void setTabContainer(android.support.v7.widget.ScrollingTabContainerView); }', but not the descriptor class 'android.support.v7.widget.ScrollingTabContainerView'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActionBarOverlayLayout { void setActionBarVisibilityCallback(android.support.v7.widget.ActionBarOverlayLayout$ActionBarVisibilityCallback); }', but not the descriptor class 'android.support.v7.widget.ActionBarOverlayLayout$ActionBarVisibilityCallback'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActionMenuView { void setPresenter(android.support.v7.widget.ActionMenuPresenter); }', but not the descriptor class 'android.support.v7.widget.ActionMenuPresenter'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActionMenuView { void setOnMenuItemClickListener(android.support.v7.widget.ActionMenuView$OnMenuItemClickListener); }', but not the descriptor class 'android.support.v7.widget.ActionMenuView$OnMenuItemClickListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActivityChooserView { void setActivityChooserModel(android.support.v7.widget.ActivityChooserModel); }', but not the descriptor class 'android.support.v7.widget.ActivityChooserModel'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ActivityChooserView { void setProvider(android.support.v4.view.ActionProvider); }', but not the descriptor class 'android.support.v4.view.ActionProvider'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ContentFrameLayout { void setAttachListener(android.support.v7.widget.ContentFrameLayout$OnAttachListener); }', but not the descriptor class 'android.support.v7.widget.ContentFrameLayout$OnAttachListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.FitWindowsFrameLayout { void setOnFitSystemWindowsListener(android.support.v7.widget.FitWindowsViewGroup$OnFitSystemWindowsListener); }', but not the descriptor class 'android.support.v7.widget.FitWindowsViewGroup$OnFitSystemWindowsListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.FitWindowsLinearLayout { void setOnFitSystemWindowsListener(android.support.v7.widget.FitWindowsViewGroup$OnFitSystemWindowsListener); }', but not the descriptor class 'android.support.v7.widget.FitWindowsViewGroup$OnFitSystemWindowsListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.MenuPopupWindow$MenuDropDownListView { void setHoverListener(android.support.v7.widget.MenuItemHoverListener); }', but not the descriptor class 'android.support.v7.widget.MenuItemHoverListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.SearchView { void setOnQueryTextListener(android.support.v7.widget.SearchView$OnQueryTextListener); }', but not the descriptor class 'android.support.v7.widget.SearchView$OnQueryTextListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.SearchView { void setOnCloseListener(android.support.v7.widget.SearchView$OnCloseListener); }', but not the descriptor class 'android.support.v7.widget.SearchView$OnCloseListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.SearchView { void setOnSuggestionListener(android.support.v7.widget.SearchView$OnSuggestionListener); }', but not the descriptor class 'android.support.v7.widget.SearchView$OnSuggestionListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.SearchView { void setSuggestionsAdapter(android.support.v4.widget.CursorAdapter); }', but not the descriptor class 'android.support.v4.widget.CursorAdapter'
    Note: the configuration keeps the entry point 'android.support.v7.widget.SearchView$SearchAutoComplete { void setSearchView(android.support.v7.widget.SearchView); }', but not the descriptor class 'android.support.v7.widget.SearchView'
    Note: the configuration keeps the entry point 'android.support.v7.widget.Toolbar { void setOnMenuItemClickListener(android.support.v7.widget.Toolbar$OnMenuItemClickListener); }', but not the descriptor class 'android.support.v7.widget.Toolbar$OnMenuItemClickListener'
    Note: the configuration keeps the entry point 'android.support.v7.widget.ViewStubCompat { void setOnInflateListener(android.support.v7.widget.ViewStubCompat$OnInflateListener); }', but not the descriptor class 'android.support.v7.widget.ViewStubCompat$OnInflateListener'
    Note: there were 7 references to unknown classes.
          You should check your configuration for typos.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
    Note: there were 1 classes trying to access generic signatures using reflection.
    PROGUARD : warning : there were 38 unresolved references to classes or interfaces.
             You may need to add missing library jars or update their versions.
             If your code works fine without the missing classes, you can suppress
             the warnings with '-dontwarn' options.
             (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
    java.io.IOException: Please correct the above warnings first.
    	at proguard.Initializer.execute(Unknown Source)
    	at proguard.ProGuard.initialize(Unknown Source)
    	at proguard.ProGuard.execute(Unknown Source)
    	at proguard.ProGuard.main(Unknown Source)
          You should consider keeping the signature attributes
          (using '-keepattributes Signature').
          (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
    Note: there were 28 unkept descriptor classes in kept class members.
          You should consider explicitly keeping the mentioned classes
          (using '-keep').
          (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
    Note: there were 8 unresolved dynamic references to classes or interfaces.
          You should check if you need to specify additional program jars.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2465,3): error MSB6006: "java" exited with code 1.
  Done executing task "Proguard" -- FAILED.
```

**Comment by pjcollins** [comment]
I should also note that given the removal of `AndroidUseLatestPlatformSdk` in VS 15.8, it is not possible to encounter this scenario from within VS in 15.8. If you change the target framework of your project to v9.0 in VS, you won't be able to build until you install API 28 (android-28/android.jar).
