### ISSUE TITLE
[AAPT2] Java.Lang.NullPointerException:  on project that runs fine with AAPT

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-android#2056]
### Steps to Reproduce

1.  git clone https://github.com/PureWeen/ReactiveTalk.git
2.  git checkout aapt2
3.  Open Xamarin/DevDays.SLN
4.  Run DevDays.Android

At this point it should crash for you

If you disable aapt2
delete bin/obj
rebuild
then project runs fine

### Expected Behavior
Project should run

### Actual Behavior
Project crashes with

![image](https://user-images.githubusercontent.com/5375137/43977054-23967144-9ca0-11e8-91ff-5b2c85f89c77.png)

### Version Information
Xamarin.Android.SDK 9.1.0.8

**Comment by Silic0nS0ldier** [comment]
I've hit this too after enabling aapt2.

Xamarin.Android.SDK 9.0.0.19

![screen shot 2018-08-25 at 9 43 21 am](https://user-images.githubusercontent.com/17376090/44612374-65e01d00-a84b-11e8-8099-732c824c51cf.png)

Full stacktrace:
```
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference
  at java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference
  at at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:502)
  at at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
  at at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
  at at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
  at at md5fd2fbb76a5fa77b93268e51471f44033.MainActivity.n_onCreate(Native Method)
  at at md5fd2fbb76a5fa77b93268e51471f44033.MainActivity.onCreate(MainActivity.java:32)
  at at android.app.Activity.performCreate(Activity.java:7036)
  at at android.app.Activity.performCreate(Activity.java:7027)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
  at at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6501)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by jpobst** [comment]
Assuming this is obsolete as Android Support libraries are deprecated and no longer supported.
