### ISSUE TITLE
Mono.Cecil.Cil.SymbolsNotMatchingException warning

### ISSUE THREAD

**Issue by deakjahn** [xamarin/xamarin-android#2120]
_Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly_ warning appeared in XF/Android projects right after upgrading to VS 15.8.2. The project compiles and runs fine.

### Steps to Reproduce

1. Open a project

### Expected Behavior

No warning.

### Version Information

VS 15.8.2

**Comment by AngeloLazzari** [comment]
same problem on VSC 7.6.3

**Comment by tickerman** [comment]
Im having The same Issue in Xamarin forms project , Visual Studio after Updating to 15.9

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)

**Comment by xufeipyxis** [comment]
I'm having this issue in VS15.9.2

```
warning : Failed to read 'D:\is.Android\obj\Debug\81\android\assets\uore.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
warning : Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
warning :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
warning :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
warning :    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
warning :    at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
warning :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
warning :    at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
warning :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)

```
The app builds and runs fine but I can't set a breakpoint in my code.

**Comment by shao200** [comment]
I'm having this issue in VS15.9.2
 Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   在 Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   在 Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   在 Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   在 Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   在 Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   在 Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   在 Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)		 	

Failed to read 'D:\CoorIdentityMobile\CoorIdentityMobile\CoorIdentityMobile.Android\obj\Debug\81\android\assets\CoorIdentityMobile.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.		 

symbols not display!

**Comment by codan-prices** [comment]
I get this issue (since updating to VS15.9.2) and it seems a clean and rebuild fixes the issue (temporarily). 
As soon as you make a change the source files are out of date and no more working breakpoints.

**Comment by Alex-Witkowski** [comment]
Same behavior as @codan-prices with VS15.9.3 . This kills productivity when working on Forms :( 
@pierceboggan are you aware of this bug?

**Comment by Alex-Witkowski** [comment]
Okay seems like setting DebugType to full like mentioned in:
https://github.com/xamarin/Xamarin.Forms/issues/3137 

And after this manually deleting bin and obj folder of android and .NET Standard projekt helps to get debug working without clean every time. But VS still has some issues with highlighting the right lines (or especially only the lines where pointer stands) in editor.

**Comment by stesvis** [comment]
I am having this issue now in **VS 2019 16.3.7**.
Deleting `bin` and `obj` + rebuild all does not solve it.
Any idea?

**Comment by ezverev** [comment]
**VS 2019 16.4.2** has this issue as well.

**Comment by MihaMarkic** [comment]
I'm getting a variation of this: "Mono.Cecil.Cil.SymbolsNotFoundException: No symbol found for file" but otherwise the message is the same.

**Comment by jitendrajadav** [comment]
After Migrating AndroidX I am having issue like below

Severity	Code	Description	Project	File	Line	Suppression State
Error		Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()	KegID.Android	C:\Users\jdj1\.nuget\packages\xamarin.androidx.migration\1.0.0\buildTransitive\monoandroid90\Xamarin.AndroidX.Migration.targets	227

**Comment by hardikphd** [comment]
I have same issue after Upgrading Xamarin.Essentials to 1.5 from 1.4

**Comment by pmahend1** [comment]
Same issue

**Comment by hardikphd** [comment]
@pmahend1 I found workaround  by using last version of Xamarin Forms 4.4 (4.4.0.991757) and Xamarin.Essentials 1.4. 
It is compatibility issue of few nugets with AndroidX, I can't seems to point out which one.

**Comment by pmahend1** [comment]
@hardikphd Thanks. Its weird because it builds fine on local machine and fails on AppCenter CI. 
I am trying by removing AndroidX nugets for now.  Lets see.

If now I will downgrade Forms and Essentials nugets

**Comment by pmahend1** [comment]
Update: It gets built in **Release** mode in _AppCenter_ but not **Debug** mode. Doing nothing specific in Debug or Release mode actually.

**Comment by hardikphd** [comment]
@pmahend1 with Latest Xamarin Forms (4.5) and Xamarin.Essentials (1.5.1) ???

**Comment by pmahend1** [comment]
@hardikphd latest Xamarin forms. But I think essentials was not installed. Seems there was an issue with build agent on AppCenter in my case. I had reached out support team

**Comment by lunjio** [comment]
I have the same issue with a dotfuscator enabled, before release i run debug with a dotfuscator enabled, to ensure that a release configuration will build success with obfuscation. I even generated the new DotfuscatorConfigFile, but didn't help, both release and debug falls with the error above.

**Comment by alienwareone** [comment]
> I have the same issue with a dotfuscator enabled, before release i run debug with a dotfuscator enabled, to ensure that a release configuration will build success with obfuscation. I even generated the new DotfuscatorConfigFile, but didn't help, both release and debug falls with the error above.
https://github.com/xamarin/AndroidX/issues/8

I also wait for a solution.
I tried several changes in "PreEmptive.Dotfuscator.Xamarin.Targets" to run the Task after "_AndroidXCecilfyShrink" but I always get an error.

**Comment by lunjio** [comment]
> > I have the same issue with a dotfuscator enabled, before release i run debug with a dotfuscator enabled, to ensure that a release configuration will build success with obfuscation. I even generated the new DotfuscatorConfigFile, but didn't help, both release and debug falls with the error above.
> > [xamarin/AndroidX#8](https://github.com/xamarin/AndroidX/issues/8)
> 
> I also wait for a solution.
> I tried several changes in "PreEmptive.Dotfuscator.Xamarin.Targets" to run the Task after "_AndroidXCecilfyShrink" but I always get an error.

To tell a truth i thought similar - the problem is that obfuscation comes before modifying dll by AndroidX migrator, and somehow i need to move obfuscation after AndroidX manipulations, but my experience is not enough to go so deep. I hope solution will come soon, i also checked does PreEmptive.Dotfuscator.Xamarin.Targets changed since last time, but nothing changed.

**Comment by dellis1972** [comment]
In this case the warning is not pointing out anything wrong I believe. The Obfuscation process is probably changing the assembly to such an extent that the debug symbols are no longer valid. 

Also the warning does not provide any useful information which would allow a user to fix the issue, other than ignoring the warning. So I added this PR https://github.com/xamarin/java.interop/pull/622 to remove this completely. Its not really needed and is only useful for people who actually develop the Xamarin.Android product.

**Comment by bramborman** [comment]
@dellis1972 but that still doesn't resolve the original issue I believe. I was getting the same warning when working on some app but I was not using any kind of obfuscation. Or is some kind of obfuscation on by default in new Xamarin.Android or Xamarin.Forms project? I mean in the default templates in Visual Studio for Windows.

**Comment by elpanas** [comment]
It happens to me too, but as an error:

> Symbols were found but are not matching the assembly
>    in Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
>    in Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
>    in Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
>    in Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
>    in Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
>    in Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
>    in Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()	BeachuApp.Android

**Comment by dellis1972** [comment]
@elpanas looking at your stack trace I believe you are hitting the following issues https://github.com/xamarin/AndroidX/issues/8. I also believe that the team are looking into that problem.

**Comment by elpanas** [comment]
> @elpanas looking at your stack trace I believe you are hitting the following issues [xamarin/AndroidX#8](https://github.com/xamarin/AndroidX/issues/8). I also believe that the team are looking into that problem.

Top. Currently I think I've solved using this hint:

[https://github.com/xamarin/AndroidX/issues/8#issuecomment-572197993](url)

Thanks for the advice :)

**Comment by lunjio** [comment]
In my case the problem comes on, only when dotfuscator is enabled. I tried cleaning, closing, opening, tried even to remove one by one a dotfuscator's hints i have in my project, but only disabling dotfuscator resolves an issue. My guess is that an obfuscation must run after all operations, before packaging an apk.

**Comment by elpanas** [comment]
> In my case the problem comes on, only when dotfuscator is enabled. I tried cleaning, closing, opening, tried even to remove one by one a dotfuscator's hints i have in my project, but only disabling dotfuscator resolves an issue. My guess is that an obfuscation must run after all operations, before packaging an apk.

I've solved my first issue due to dotfuscator in this way: [https://github.com/xamarin/xamarin-android/issues/2120#issuecomment-623097383](url) as suggested by dellis1972

**Comment by KerosenoDev** [comment]
In my case, it was by manually editing `AndroidManifest.xml`.
I undid it, and made the changes through the project `Properties` menu.

**Comment by Frostklinga** [comment]
@elpanas suggestion worked for me. Moved the Release and Debug folders -> clean solution -> rebuild solution -> Problem solved!

**Comment by KatoneVi** [comment]
Here is how I solved it:
On the bottom of Unity Editor (the section where all your assets are), right click -> "Reimport All"

Done.
I updated the Project Settings and it was just off sync.
I hope this helps someone.
