### ISSUE TITLE
Editing axml with "Highlight Containers" in Xamarin.Android project breaks designer

### ISSUE THREAD

**Issue by SDV-MINI-DEV-2** [xamarin/xamarin-android#2203]
Every time I edit my axml by typing in the axml when the option "Highlight Containers" is on (this option highlights the view borders), the designer throws an "Object reference not set to an instance of an object" exception. 
Also when I drag a widget when the option "Highlight Containers" is on I've found this exception. 

The designer is now broken and I can't work, because working without Highlight Containers option is very very annoying. 
### Steps to Reproduce

1. File -> New Project -> Android Blank App
2.  Resource --> layout --> Activity_main.axml 
3.  Highlight Containers --> Drag a textview or a random widget/Typing in axml --> Error

### Log File

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.AndroidDesigner.LayoutInfo.GetElementXml(XmlWriter writer, AndroidXmlItem elem, LayoutXmlTarget xmlTarget, Dictionary`2 acwMap, Dictionary`2 userNamespaces) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 912
   at Xamarin.AndroidDesigner.LayoutInfo.GetElementXml(XmlWriter writer, AndroidXmlItem elem, LayoutXmlTarget xmlTarget, Dictionary`2 acwMap, Dictionary`2 userNamespaces) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 960
   at Xamarin.AndroidDesigner.LayoutInfo.GetElementXml(XmlWriter writer, AndroidXmlItem elem, LayoutXmlTarget xmlTarget, Dictionary`2 acwMap, Dictionary`2 userNamespaces) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 960
   at Xamarin.AndroidDesigner.LayoutInfo.GetElementXml(XmlWriter writer, AndroidXmlItem elem, LayoutXmlTarget xmlTarget, Dictionary`2 acwMap, Dictionary`2 userNamespaces) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 960
   at Xamarin.AndroidDesigner.LayoutInfo.GetRenderXml(AndroidXmlItem root, LayoutXmlTarget xmlTarget, Dictionary`2 acwMap) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 898
   at Xamarin.AndroidDesigner.LayoutInfo.GetLayoutXml(LayoutXmlTarget xmlTarget, Dictionary`2 acwMap) in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\LayoutInfo.cs:line 881
   at Xamarin.AndroidDesigner.AndroidRenderSession.<InflateAsync>d__110.MoveNext() in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\AndroidRenderSession.cs:line 745
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidDesigner.AndroidRenderSession.<DoRefreshAsync>d__106.MoveNext() in E:\A\_work\122\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Xamarin.AndroidDesigner\AndroidRenderSession.cs:line 597

> VS bug [#690456](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/690456)

**Comment by JonDouglas** [comment]
@SDV-MINI-DEV-2 Thank you for this report. We are currently tracking this issue through another reported issue:

https://developercommunity.visualstudio.com/content/problem/335651/editing-axml-with-highligh-container-in-xamarinand.html

Thus we will be closing this issue here, please follow the link above for updates on this issue.
