### ISSUE TITLE
When there is a property of Nullable<> of a complex struct type defined in a class and it is used as a Page StaticResource, there is a runtime exception.

### ISSUE THREAD

**Issue by ezverev** [xamarin/xamarin-android#2244]
### Steps to Reproduce

1. Define a class which will be used as a static resource:

```
    public class StaticResourceClass
    {
        //Nullable Enum - ok.
        public FontAttributes? FontAttributes
        {
            get; set;
        }

        //Nullable primitive types - ok.
        public double? FontSize
        {
            get; set;
        }

        //Nullable complex struct - problem.
        public Color? TextColor
        {
            get; set;
        }

        //Nullable complex struct - problem.
        public Thickness? Padding
        {
            get; set;
        }
    }
```

2. Include the `StaticResourceClass` into a page as a StaticResource.

```
    <ContentPage.Resources>
        <ns1:StaticResourceClass x:Key="_key" TextColor="Black"">
        </ns1:StaticResourceClass>
    </ContentPage.Resources>
```

3. Run the project.

### Expected Behavior
The app should run without a problem.

### Actual Behavior
An unhandled runtime exception is thrown:
System.InvalidProgramException: Invalid IL code in XamarinForms.MainPage:InitializeComponent (): IL_0172: newobj    0x0a000023

### Version Information

[VS_version_info.txt](https://github.com/xamarin/xamarin-android/files/2433659/VS_version_info.txt)

[adb_logcat.txt](https://github.com/xamarin/xamarin-android/files/2433654/adb_logcat.txt)

**Comment by grendello** [comment]
Hi @ezverev! This issue may be a problem with the JIT compiler, but it is impossible to tell for sure given the information at hand. Would you mind creating, zipping up and attaching as simple project which reproduces the issue? In order to determine the cause of the behavior we need to be able to reproduce the issue locally. Thanks!

**Comment by ezverev** [comment]
Here is the repo: 
[Problem2.zip](https://github.com/xamarin/xamarin-android/files/2441674/Problem2.zip)

**Comment by grendello** [comment]
The full exception from running the attached repro on an API 28 emulator:

```
10-03 17:39:25.500  2285  2285 D Mono    : Assembly Ref addref Xamarin.Forms.Core[0xed6c6e80] -> Xamarin.Forms.Platform[0xed6c6f40]: 2
10-03 17:39:25.596  2285  2285 I MonoDroid: UNHANDLED EXCEPTION:
10-03 17:39:25.602  2285  2285 I MonoDroid: System.InvalidProgramException: Invalid IL code in Problem2.MainPage:InitializeComponent (): IL_0090: newobj    0x0a000015
10-03 17:39:25.602  2285  2285 I MonoDroid: 
10-03 17:39:25.602  2285  2285 I MonoDroid: 
10-03 17:39:25.602  2285  2285 I MonoDroid:   at Problem2.MainPage..ctor () [0x00008] in <cac9ca9f86e841beb47df8d3d7a78ff4>:0 
10-03 17:39:25.602  2285  2285 I MonoDroid:   at Problem2.App..ctor () [0x0000f] in <cac9ca9f86e841beb47df8d3d7a78ff4>:0 
10-03 17:39:25.602  2285  2285 I MonoDroid:   at Problem2.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00027] in <ee6d5c4fe20145f58859cbb0db38bc51>:0 
10-03 17:39:25.602  2285  2285 I MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00012] in <0e1cbcf3688949929d25ced677edffc7>:0 
10-03 17:39:25.602  2285  2285 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
10-03 17:39:25.611  2285  2285 I monodroid-timing: Runtime.register: start time: 1538581165611 ms
10-03 17:39:25.611  2285  2285 I monodroid-timing: JNIEnv.RegisterJniNatives ("Android.Runtime.JavaProxyThrowable, Mono.Android", 0xffb4a924) start: 1538581165611.67
10-03 17:39:25.611  2285  2285 W com.companynam: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
10-03 17:39:25.612  2285  2285 I monodroid-timing: JNIEnv.RegisterJniNatives total time: 1538581165611.85 [elapsed: 0.182 ms]
10-03 17:39:25.612  2285  2285 I monodroid-timing: Runtime.register: end time: 1538581165612 [elapsed 1 ms]
10-03 17:39:25.617  2285  2285 D Mono    : DllImport searching in: '__Internal' ('(null)').
10-03 17:39:25.617  2285  2285 D Mono    : Searching for 'java_interop_jnienv_throw'.
10-03 17:39:25.617  2285  2285 D Mono    : Probing 'java_interop_jnienv_throw'.
10-03 17:39:25.617  2285  2285 D Mono    : Found as 'java_interop_jnienv_throw'.
10-03 17:39:25.619  2285  2285 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-03 17:39:25.620  2285  2285 E AndroidRuntime: FATAL EXCEPTION: main
10-03 17:39:25.620  2285  2285 E AndroidRuntime: Process: com.companyname, PID: 2285
10-03 17:39:25.620  2285  2285 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.InvalidProgramException: Invalid IL code in Problem2.MainPage:InitializeComponent (): IL_0090: newobj    0x0a000015
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 
10-03 17:39:25.620  2285  2285 E AndroidRuntime:   at Problem2.MainPage..ctor () [0x00008] in <cac9ca9f86e841beb47df8d3d7a78ff4>:0 
10-03 17:39:25.620  2285  2285 E AndroidRuntime:   at Problem2.App..ctor () [0x0000f] in <cac9ca9f86e841beb47df8d3d7a78ff4>:0 
10-03 17:39:25.620  2285  2285 E AndroidRuntime:   at Problem2.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00027] in <ee6d5c4fe20145f58859cbb0db38bc51>:0 
10-03 17:39:25.620  2285  2285 E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00012] in <0e1cbcf3688949929d25ced677edffc7>:0 
10-03 17:39:25.620  2285  2285 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at md53eb6fbe7d56f2adb9a66fb4ee01f846b.MainActivity.n_onCreate(Native Method)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at md53eb6fbe7d56f2adb9a66fb4ee01f846b.MainActivity.onCreate(MainActivity.java:29)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-03 17:39:25.620  2285  2285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

IL code for the referenced methods:

```cil
namespace Problem2
{
  .class public auto ansi beforefieldinit MainPage
        extends [Xamarin.Forms.Core]Xamarin.Forms.ContentPage
  {
    .custom instance void [Xamarin.Forms.Xaml]Xamarin.Forms.Xaml.XamlFilePathAttribute::.ctor(string) =  (
                01 00 0D 4D 61 69 6E 50 61 67 65 2E 78 61 6D 6C   // ...MainPage.xaml
                00 00                                           ) // ..
        
        
    // method line 7
    .method public hidebysig specialname rtspecialname
           instance default void '.ctor' ()  cil managed
    {
        // Method begins at RVA 0x20fb
        // Code size 16 (0x10)
        .maxstack 8
        IL_0000:  ldarg.0
        IL_0001:  call instance void [Xamarin.Forms.Core]Xamarin.Forms.ContentPage::.ctor()
        IL_0006:  nop
        IL_0007:  nop
        IL_0008:  ldarg.0
        IL_0009:  call instance void class Problem2.MainPage::InitializeComponent()
        IL_000e:  nop
        IL_000f:  ret
    } // end of method MainPage::.ctor

    // method line 8
    .method private hidebysig
           instance default void InitializeComponent ()  cil managed
    {
        .custom instance void class [System]System.CodeDom.Compiler.GeneratedCodeAttribute::'.ctor'(string, string) =  (
                01 00 1F 58 61 6D 61 72 69 6E 2E 46 6F 72 6D 73   // ...Xamarin.Forms
                2E 42 75 69 6C 64 2E 54 61 73 6B 73 2E 58 61 6D   // .Build.Tasks.Xam
                6C 47 07 32 2E 30 2E 30 2E 30 00 00             ) // lG.2.0.0.0..

        // Method begins at RVA 0x210c
    } // end of method MainPage::InitializeComponent

    // method line 9
    .method private hidebysig
           instance default void __InitComponentRuntime ()  cil managed
    {
        // Method begins at RVA 0x2216
        // Code size 19 (0x13)
        .maxstack 8
        IL_0000:  nop
        IL_0001:  ldarg.0
        IL_0002:  ldtoken Problem2.MainPage
        IL_0007:  call class [mscorlib]System.Type class [mscorlib]System.Type::GetTypeFromHandle(valuetype [mscorlib]System.RuntimeTypeHandle)
        IL_000c:  call Could not decode method token 0x1f due to Could not load file or assembly 'Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
        IL_0011:  pop
        IL_0012:  ret
    } // end of method MainPage::__InitComponentRuntime

  } // end of class Problem2.MainPage
}
```

**Comment by marek-safar** [comment]
@grendello did you manage to reproduce the issue?

**Comment by grendello** [comment]
@marek-safar yes, the exception above is from my emulator

**Comment by pjcollins** [comment]
Is this still present in the latest release of VS 2019? If so, we likely should move this over to https://github.com/mono/mono/issues for further investigation.
