### ISSUE TITLE
Can't deploy/debug app to Samsung Galaxy S9 since last week

### ISSUE THREAD

**Issue by sensboston** [xamarin/xamarin-android#2470]
### Steps to Reproduce

1. Connect Samsung Galaxy S9 phone (dev. mode enabled, adb works, Android Studio works perfectly)
2. Start deploying/debugging
3. It takes forever (but 100% worked a couple of weeks ago), communication exception isn't handled correctly by Xamarin plugin. 

### Expected Behavior
It should work as it worked before, two weeks ago (with this SGS9). By the way, it works with another Android phone, LG G3.

### Actual Behavior
From the logs: I'm getting an exception:
``
MonoDroidLog: Error: 0: [E:]:                     Deployment failed
Mono.AndroidTools.AdbException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at Mono.AndroidTools.Adb.AdbClient.ReadText_OnReadText(IAsyncResult ar) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 548
   --- End of inner exception stack trace ---
   at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Util\AggregateAsyncResult.cs:line 72
   at Mono.AndroidTools.Adb.AdbClient.EndReadText(IAsyncResult ar) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 563
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
``

**Please note**: there is NOTHING wrong with the phone and my PC setup; adb, Android Studio are working correctly, USB 3.0 connection is fast as a hell. The issue is in Xamarin but I'm unsure about the roots: latest Xamarin update or SGS9 update. 

### Version Information
[version.txt.zip](https://github.com/xamarin/xamarin-android/files/2631137/version.txt.zip)

### Log File
[logs.zip](https://github.com/xamarin/xamarin-android/files/2631134/logs.zip)

**Comment by jonathanpeppers** [comment]
These are odd errors:
```
Mono.AndroidTools.AdbException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at Mono.AndroidTools.Adb.AdbClient.ReadText_OnReadText(IAsyncResult ar) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 548
   --- End of inner exception stack trace ---
   at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Util\AggregateAsyncResult.cs:line 72
   at Mono.AndroidTools.Adb.AdbClient.EndReadText(IAsyncResult ar) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 563
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
...
Mono.AndroidTools.AdbException: device '33544a5748303098' not found
   at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Util\AggregateAsyncResult.cs:line 72
   at Mono.AndroidTools.Adb.AdbClient.EndConnectTransport(IAsyncResult asyncResult) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 207
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

@sensboston do any of the following solve the problem?
* Uninstall the `Mono Shared Runtime` and any `Xamarin.Android API-* Support` packages from the device
* Delete your `bin` and `obj` directories. Or `git clean -dxf` if using git.
* Try again?

What is the version of Android on your device?

**Comment by sensboston** [comment]
@jonathanpeppers, thanks, after uninstalling Xamarin/Mono runtimes, I'm able to deploy/debug on SGS9 again! 
By the way, I'm worried for the production: can this happen on release version submitted to the Play store?

**Comment by jonathanpeppers** [comment]
The `Mono Shared Runtime` is something that makes our "Fast Deployment" feature work. It is only for debugging purposes.

Release builds don't use it, so no problem there.
