### ISSUE TITLE
The "Link Assemblies" task failed unexpectedly

### ISSUE THREAD

**Issue by sundeeppeethani** [xamarin/xamarin-android#2522]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Support.V7.App.NotificationCompat/MediaStyle' (defined in assembly 'Plugin.MediaManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.v7.AppCompat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.V7.App.NotificationCompat/MediaStyle
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MDC

**Comment by JonDouglas** [comment]
Please provide us with more information such as a way to reproduce this behavior. See our wiki for more details:

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports

**Comment by brendanzagaeski** [comment]
Thanks for the report! This appears to be a downstream issue in the [Plugin.MediaManager](https://www.nuget.org/packages/Plugin.MediaManager/) NuGet package. The most recent version of that package (published in October 2017) was built against version 25 of the Xamarin.Android.Support.v7.AppCompat NuGet package. The linker error occurs because Google removed the `Android.Support.V7.App.NotificationCompat/MediaStyle` type from version 27.0.0 of the support library (see the information about "Some deprecated classes removed" in the [release notes](https://developer.android.com/topic/libraries/support-library/revisions#27-0-0)), and it is accordingly absent from version 27 of the Xamarin.Android.Support.v7.AppCompat NuGet package. The problem is that the old October 2017 version of Plugin.MediaManager still uses `Android.Support.V7.App.NotificationCompat/MediaStyle`, for example in [MediaNotificationManagerImplementation](https://github.com/martijn00/XamarinMediaManager/blob/0.4.4/MediaManager.Android/MediaSession/MediaNotificationManagerImplementation.cs). 

The corresponding GitHub issue that is tracking the necessary changes for the Plugin.MediaManager NuGet package is <https://github.com/martijn00/XamarinMediaManager/issues/278>.
