### ISSUE TITLE
AbstractMethodError when using interfaces

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#2630]
### Steps to Reproduce

Hey folks, I think I found a bug or something. Still not sure - maybe I am just tired and I can't think.

This is my code:
```csharp
public interface ITesting
{
	string Managed { get; }
}
public abstract class TestingBase<TManagedType> : Java.Lang.Object
{
	public TManagedType Managed { get; private set; }
}
public class Testing : TestingBase<string>, ITesting
{
}
public static class Tester
{
	public static void DoTest(ITesting testing)
	{
		// all of these operations throw
		if (testing.Managed == null)
			return;
		if (testing.Managed is string)
			return;
		if (!(testing.Managed is string))
			return;
		if (!(testing.Managed is string typeBang))
			return;
	}
}
```
And the code that fires this all off is this:
```csharp
var testing = new Testing();
Tester.DoTest(testing);
```
This appears to be a bug as I have an instance, but, it also works if I remove the base type of the `Java.Lang.Object`

### Expected Behavior

No crashes.

### Actual Behavior

Crashes with exception:

```
[MonoDroid] Java.Lang.AbstractMethodError: Exception of type 'Java.Lang.AbstractMethodError' was thrown.
[MonoDroid]   at AbstractTest.Testing.get_Managed () [0x00005] in <616b6e44090c4ba3b28f5c1b8673168c>:0 
[MonoDroid]   at AbstractTest.Tester.DoTest (AbstractTest.ITesting testing) [0x00001] in /Users/matthew/Projects/Testing/AbstractTest/AbstractTest/MainActivity.cs:40 
[MonoDroid]   at AbstractTest.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001b] in /Users/matthew/Projects/Testing/AbstractTest/AbstractTest/MainActivity.cs:18 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <5f142c269d8a438c94480ac03744dec7>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.10(intptr,intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.AbstractMethodError stack trace ---
[MonoDroid] java.lang.AbstractMethodError
[MonoDroid] 	at md553f852e908783864c7b1de458d6b28de.MainActivity.n_onCreate(Native Method)
[MonoDroid] 	at md553f852e908783864c7b1de458d6b28de.MainActivity.onCreate(MainActivity.java:29)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7136)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7127)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
[MonoDroid] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:193)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[MonoDroid] 
```

### Version Information

https://gist.github.com/mattleibow/953050a4f599d3f7222633939786ad52

### Log File

https://gist.github.com/mattleibow/a3e310125c7de6d5ed3951669bfc6a77

**Comment by jonathanpeppers** [comment]
@jonp  or @radekdoulik I don't know what is going on here, but is this a scenario the [FixAbstractMethods](https://github.com/xamarin/xamarin-android/blob/7c9dea81e5a4abdbe910e227493be95d89456017/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs) linker step is supposed to fix up? 

Or a known limitation?

**Comment by radekdoulik** [comment]
This indeed looks like bug in https://github.com/xamarin/xamarin-android/blob/7c9dea81e5a4abdbe910e227493be95d89456017/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs

We generate `get_Managed` method, which is then called by the `DoTest`, while we shouldn't as there already exists an implementation of `get_Managed`.

```
+  .method public hidebysig newslot specialname virtual final 
+          instance string  get_Managed() cil managed
+  {
+    // Code size       6 (0x6)
+    .maxstack  8
+    IL_0000:  newobj     instance void [Mono.Android]Java.Lang.AbstractMethodError::.ctor()
+    IL_0005:  throw
+  } // end of method Testing::get_Managed
+
 } // end of class AbstractTest.Testing
```

Might be related to usage of generics.

**Comment by mattleibow** [comment]
Been a few days, but I think it only happened with the generics - if I used non-generic types, it worked fine.

**Comment by allsorts46** [comment]
I'm experiencing something similar, and not sure if it's the same issue or not. No generics are involved. Essentially:

    // In assembly A:

    public interface IHasColor
        {
        Color? Color { get; }
        }

    public class ActualThing : IHasColor
        {
        public String SomeProperty { get; set; }
        public Color? Color { get; set; }
        }

    // In assembly B:
    
    public abstract class ThingWrapperBase
        {
        public ThingWrapperBase(Object thing)
            {
            if (thing is IHasColor hasColor)
                {
                var WhichColor = hasColor.Color;     // Throws Java.Lang.AbstractMethodError
                Color = WhichColor;        // We don't get to this line. Exception is from interface getter, not abstract class setter.
                }
            }

        public Color? Color { get; set; }
        }

    public class ActualThingWrapper : ThingWrapperBase
        {
        public ActualThingWrapper(Object thing)
            : base(thing)
            {
            }
        }

    // Invocation somewhere:
    var MyThing = GetAThingFromSomewhere();
    var MyWrapper = new ActualThingWrapper(MyThing);        // Exception thrown as indicated above
    
I see this issue is reasonable old (almost 2 years). If there's no fix, is there a recommended workaround?

**Comment by allsorts46** [comment]
Looks like this specific issue didn't get looked at in the last 7 years, but just in case anyone else comes across this, the bug does not seem to exist in .Net 8.0. I am not sure which version fixed this and whether it was deliberate or a side effect of fixing something else, but my original code as above now works fine.
