### ISSUE TITLE
Android implementation of HTTPClient throwing up java.io.IOException 

### ISSUE THREAD

**Issue by terrajobst** [xamarin/xamarin-android#2651]
_From @UnreachableCode on January 17, 2019 16:54_

I believe this relates to the bug detailed in Xamarin's old Bugzilla:
https://bugzilla.xamarin.com/show_bug.cgi?id=41100

and is also similar to the issue discussed here:
https://github.com/square/okhttp/issues/1517

Here is the main stacktrace of my issue:

LoginProvider+<LoginAsync>d__1.MoveNext () C:\source\repos\{MyApp}\{MyApp}\{MyApp}\Services\LoginProvider.cs:35
java.io.IOException: unexpected end of stream on Connection{testclarity.i-menzies.com:443, proxy=DIRECT@ hostAddress=62.244.173.166 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1} (recycle count=0)
com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
Caused by: java.io.EOFException: \n not found: size=0 content=...
com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)

I have tried setting the connection closed header and setting chunked transfer encoding but neither of these fixes work. I would try to set the OkHTTP.setRetryOnConnectionFailure(true) but I don't think there is a way to do this in the referenced Java source.

_Copied from original issue: dotnet/standard#1055_

**Comment by terrajobst** [comment]
@marek-safar is bugzilla still the right location for filing Xamarin bugs?

**Comment by terrajobst** [comment]
_From @marek-safar on January 23, 2019 8:7_

No, use https://github.com/xamarin/xamarin-android/ for new issues

**Comment by terrajobst** [comment]
@UnreachableCode 

Your issue is implementation specific, I've moved it.

**Comment by jonathanpeppers** [comment]
@UnreachableCode are you using [ModernHttpClient](https://www.nuget.org/packages/modernhttpclient/)?

I am confused on how `okhttp` is in your Java stacktrace, Xamarin.Android doesn't use that?

The options for HTTP settings here under `Project Options | Android Options | Advanced`:

![image](https://user-images.githubusercontent.com/840039/51753775-48281580-2080-11e9-96be-9da9fddf213a.png)

None of the built-in options here use `okhttp`.

**Comment by UnreachableCode** [comment]
Hi @jonathanpeppers.

Not using ModernHttpClient. Just the default HttpClient setup. I had these settings:

![capture35](https://user-images.githubusercontent.com/1167553/51761096-0de06780-20c4-11e9-9c32-5464600a9990.PNG)

Which lead to okhttp appearing in my stacktraces. However, I have now changed to this:

![capture36](https://user-images.githubusercontent.com/1167553/51761138-2ea8bd00-20c4-11e9-9df9-6ac2499f14a8.PNG)

And I seem to no longer be receiving the error, leading me to believe it's not using okhttp anymore.

**Comment by muhaym** [comment]
@jonathanpeppers, Using Android HttpClient Implementation does throw Java exceptions instead of .NET exceptions. Similarly HttpClient iOS exception is System.Web.Exception.

Is there any way that I could get the .NET Exceptions, so that I could use libraries like Polly to implement policies from .NET Standard project itself.

I don't have any reference to Okhttp, but not sure how okhttp ends up in logs like the report above.

```
{Java.Net.UnknownHostException: Unable to resolve host "smc.kooz.top": No address associated with hostname ---> Java.Lang.RuntimeException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect () [0x0000a] in <a6696dd5fce04f5480364911ef1529f2>:0 
  at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 () [0x0005a] in <a6696dd5fce04f5480364911ef1529f2>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x0012e] in <a6696dd5fce04f5480364911ef1529f2>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002be] in <a6696dd5fce04f5480364911ef1529f2>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
  at SpotMyCourt.Services.CommonFiles.Services.RequestProvider.PostAsync[TRequest,TResult] (System.String uri, TRequest data, System.String token) [0x00188] in C:\Projects\SpotMyCourt\SpotMyCourt.Services\CommonFiles\Services\RequestProvider.cs:99 
  --- End of managed Java.Net.UnknownHostException stack trace ---
java.net.UnknownHostException: Unable to resolve host "smc.kooz.top": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
	at java.net.InetAddress.getAllByName(InetAddress.java:787)
	at com.android.okhttp.Dns$1.lookup(Dns.java:39)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
	... 15 more
}
```

**Comment by jonathanpeppers** [comment]
@muhaym I am not familiar with Polly, but the exception will come through as `Java.Net.UnknownHostException`, a type you won't have a reference to in your netstandard project. Unfortunately, this is the result of running on different platforms, we don't map the native exception types back to .NET standard ones.

Does Polly have a way to retry based on the type name? As a string? Not ideal, but a workaround for now.

Can you file an issue on https://github.com/xamarin/xamarin-android/issues explaining the difference in exceptions you see in regular .NET vs iOS vs Android?

**Comment by muhaym** [comment]
@jonathanpeppers  Thanks for the reply. Polly have a generic system to get the exception. Any way the matter of concern is not the ability to use Polly, but the ability to understand the core issue of exception from .NET Standard shared code.

I have enough data of various exception for iOS and Android project from a live project. Should I file iOS and Android separately, or what will be the right place to discuss this issue? 

Ideally mapping to .NET Standard exception is what a developer can rely on, otherwise, the code duplication and writing separate interface for the httpclient for native platforms are double efforts of the same code.

**Comment by jonathanpeppers** [comment]
It seemed like iOS you are getting `WebException`, so that seems reasonable to deal with--maybe you don't need to file an iOS bug? Android, for sure, it seems weird you have no way to catch `Java.Lang.FooException` types.

**Comment by muhaym** [comment]
Yes, I'll proceed with an issue in this repo.

**Comment by theo-albers** [comment]
Since AndroidClientHandler is the default HTTP handler in Xamarin Forms projects, it's at least interesting there is no reference about native Java exceptions bubbling up in the documentation, see https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/. This was a big surprise to me when some devices like the Samsung Galaxy S9 with Android 9 started showing up in AppCenter with crashes, specifically around 
![image](https://user-images.githubusercontent.com/9417380/67156182-87d41300-f31b-11e9-8d15-87996192ad8d.png)
There are other exceptions as discussed here [3216](https://github.com/xamarin/xamarin-android/issues/3216). 
As Xamarin Forms developer writing a netstandard shared project, I would have expected catching the typical HTTP managed exceptions. Catching System.Exception is not good enough either.
For me the workaround was to extend AndroidClientHandler, since I'm spinning up the AndroidClientHandler in the Android project:
```csharp
    public class WorkaroundAndroidClientHandler : AndroidClientHandler
    {
        public WorkaroundAndroidClientHandler()
        {
            this.AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // The native Android HTTP client handler bubbles up Java exceptions in contrast to the iOS native handler.
            // See for instance https://github.com/xamarin/xamarin-android/issues/3216.
            // We see this behavior on a Samsung 9 with Android 9.
            // Remedy is to explicitly catch expected native network exceptions.
            try
            {
                return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Java.Net.SocketException ex)
            {
                throw new WebException($"Native SocketException on HTTP request: {ex.Message}", ex);
            }
            catch (Java.IO.IOException ex)
            {
                throw new WebException($"Native IOException on HTTP request: {ex.Message}", ex);
            }
            catch (Java.Lang.Exception ex)
            {
                throw new WebException($"Native Exception on HTTP request: {ex.Message}", ex);
            }
        }
    }
```
