### ISSUE TITLE
"Error inflating class android.support.v7.widget.ActionBarOverlayLayout" when using the r8.jar version in the d16-0 branch rather than ProGuard

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#2931]
### Steps to Reproduce

Attempt to run the [attached test case](https://github.com/xamarin/xamarin-android/files/3045715/R8AndroidSupport.zip) in either the Debug or Release configuration any Android device or emulator. (I tested on an Android 9.0 Pie (API level 28) Google Pixel 3 as well as an Android 7.1.1 Nougat (API level 25) device.)

(The test case is the **Android App (Xamarin) > Blank App** template, modified to add `<AndroidLinkTool>r8</AndroidLinkTool>` and to enable linking and disable the shared runtime in the Debug configuration.)

### Expected Behavior

If the *.csproj* is configured with `<AndroidLinkTool>proguard</AndroidLinkTool>` instead, the app launches successfully and displays the text "Large Text". This behavior is consistent back to at least Visual Studio 2017 version 15.7.6 (using the older `<AndroidEnableProguard>true</AndroidEnableProguard>` property).

(For historical reference, the older **Mobile App (Xamarin.Forms) > Master Detail** template that was shipped in Visual Studio 2017 version 15.7.6 used to hit a `NullReferenceException` during app startup when built with Visual Studio 2017 version 15.7.6 and `<AndroidEnableProguard>true</AndroidEnableProguard>` [unless some additional rules were added in a `@(ProguardConfiguration)` item](https://github.com/xamarin/xamarin-android/issues/1646#issuecomment-425479814). But, like the attached test case, the *current* **Mobile App (Xamarin.Forms) > Master-Detail** template that is shipped in Visual Studio 2019 runs successfully when built using Visual Studio 2017 version 15.7.6 and `<AndroidEnableProguard>true</AndroidEnableProguard>`, with no need for an additional `@(ProguardConfiguration)` item.)

### Actual Behavior

The application hits an unhandled exception during launch. Excerpt of the top of the stack trace:

```
UNHANDLED EXCEPTION:
Java.Lang.Exception: Binary XML file line #17: Binary XML file line #17: Error inflating class android.support.v7.widget.ActionBarOverlayLayout ---> Java.Lang.Exception: Binary XML file line #17: Error inflating class android.support.v7.widget.ActionBarOverlayLayout ---> Java.Lang.ReflectiveOperationException: <init> [class android.content.Context, interface android.util.AttributeSet]
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <b49e0c493a5e4c5186212e29f6b77d1e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <b49e0c493a5e4c5186212e29f6b77d1e>:0 
  at Android.App.Activity.SetContentView (System.Int32 layoutResID) [0x00022] in <db7eb011ae5d498ba9f82c91bf3ead2d>:0 
  at Test1.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0000e] in <7e409eb71a644608be0a248b58beee09>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <db7eb011ae5d498ba9f82c91bf3ead2d>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
  --- End of managed Java.Lang.Exception stack trace ---
android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.support.v7.widget.ActionBarOverlayLayout
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.v7.widget.ActionBarOverlayLayout
Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at android.view.LayoutInflater.createView(LayoutInflater.java:618)
```

### Possible Workaround

For this simple test scenario, the following steps are sufficient to work around the error during app startup. There might be other scenarios that the current version of *r8.jar* doesn't handle that would require additional custom rules to solve.

 1. Create a new text file in the app project. I named mine *proguard.cfg* to follow the old habit from when ProGuard was the only available code shrinking option.
 2. Add the following lines to the file:

    ```txt
    -keep class android.support.v7.widget.** { *; }
    -dontwarn android.support.v7.widget.*
    -keep class android.support.v7.view.** { *; }
    -dontwarn android.support.v7.view.*
    ```
  3. Use **File > Save ... As** to save the file. Click the drop-down menu on the **Save** button to select **Save with Encoding** and click **Yes** to confirm overwriting the existing file.
  4. Select the **US-ASCII - Codepage 20127** encoding and click **OK**.  This step is necessary to remove a byte-order mark that otherwise causes an error when `r8` reads the file.
  5. Set the **View > Properties Window > Build Action** for the new file to **ProguardConfiguration**.
  6. **Build > Clean** the project, and then build and redeploy it.

### Version Information

Xamarin.Android 9.2.0.5 (d16-0@fa7ba9db04226e63e583e185304593509cc5cda6)

### Logs

[adblogcat.txt](https://github.com/xamarin/xamarin-android/files/3045723/adblogcat.txt)

**Comment by brendanzagaeski** [comment]
This issue is already fixed in recent development versions like xamarin-android/d16-1@1ce948bb30ac24b13c2b4f9a1283029fdcd78e7b

In fact, copying the *r8.jar* file from the [CI build of that version](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-d16-1/16/Azure/) to overwrite the current version shipped in Visual Studio 2019 is sufficient to resolve the issue for me.

Based on this result, I am closing this issue as resolved upstream in newer version of the R8 tool.
