### ISSUE TITLE
Failed to deploy - Unexpected install output: Killed 

### ISSUE THREAD

**Issue by toomasz** [xamarin/xamarin-android#3160]
### Steps to Reproduce

Not sure, got it today without any changes in project

### Expected Behavior

App should deply successfully

### Actual Behavior

Unexpected install output: Killed 

### Version Information
```
Microsoft Visual Studio Community 2019
Version 16.1.0
VisualStudio.16.Release/16.1.0+28917.181
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2019   0
Xamarin.Android SDK   9.3.0.22 (HEAD/8e7764fdf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3cb36842fc4
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Xamarin.iOS and Xamarin.Mac SDK   12.10.0.153 (750a879)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
### Log File
[error_log.txt](https://github.com/xamarin/xamarin-android/files/3244684/error_log.txt)

**Comment by jpobst** [comment]
Looks like this was some unexpected output from ADB:

```
2>Mono.AndroidTools.InstallFailedException: Unexpected install output: Killed 
2>
2>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
2>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t)
2>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.Execute()
2>ADB0010: Unexpected install output: Killed 
2>
2>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
2>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t)
2>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
2>   at System.Threading.Tasks.Task.Execute()
```

Given that we have had no further reports, I guess either Google or us fixed it.
