### ISSUE TITLE
Got a SIGSEGV while executing native code

### ISSUE THREAD

**Issue by mfeingol** [xamarin/xamarin-android#3398]
### Steps to Reproduce

Unclear how to reproduce in isolation, sorry. However, there's a page in my app that has a 100% repro just entering it in an Intel-based emulator. This only happens when the app is run under the debugger, oddly enough.

I can provide access to the app if needed.

### Expected Behavior

No SIGSEGVs.

### Actual Behavior

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
07-27 23:40:32.043 E/mono-rt ( 7314): /proc/self/maps:
=================================================================

07-27 23:40:32.043 E/mono-rt ( 7314): 12c00000-5ac00000 rw-p 00000000 00:01 7372       /dev/ashmem/dalvik-main space (region space) (deleted)
07-27 23:40:32.043 E/mono-rt ( 7314): 5d6c9000-5e4da000 rw-s 00000000 00:01 88187      /dev/ashmem/gralloc-buffer (deleted)
07-27 23:40:32.043 E/mono-rt ( 7314): 5e4da000-5f2eb000 rw-s 00000000 00:01 88188      /dev/ashmem/gralloc-buffer (deleted)
07-27 23:40:32.043 E/mono-rt ( 7314): 5f2eb000-600fc000 -w-s 00000000 00:10 5173       /dev/goldfish_pipe
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x864980cf):0x864980bf  75 11 f6 06 10 75 0c 8b 46 08 f6 40 14 04 75 03  u....u..F..@..u.
0x864980cf  8b 6d 00 89 e8 83 c4 1c 5e 5f 5b 5d c3 8d 83 a5  .m......^_[]....
0x864980df  7e f4 ff 8d 8b 4c 7a f4 ff 8d 93 6d 9f f3 ff 50  ~....Lz....m...P
0x864980ef  68 33 03 00 00 51 52 e8 35 8b f5 ff 90 90 90 90  h3...QR.5...

07-27 23:40:32.043 E/mono-rt ( 7314): 600fc000-618fe000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62080000-62280000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-27 23:40:32.043 E/mono-rt ( 7314): 622f8000-62378000 rw-p 00000000 00:00 0 ....

No native Android stacktrace (see debuggerd output).

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
07-27 23:40:32.043 E/mono-rt ( 7314): 6237c000-623fc000 rw-p 00000000 00:00 0 

07-27 23:40:32.043 E/mono-rt ( 7314): 62400000-62700000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-27 23:40:32.043 E/mono-rt ( 7314): 62700000-62800000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 6287c000-628fc000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62a04000-62a08000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62a0c000-62a1c000 rwxp 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62a1c000-62a1e000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62a2c000-62a7c000 rwxp 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62a7c000-62afc000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62b00000-62c00000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62c00000-62d00000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-27 23:40:32.043 E/mono-rt ( 7314): 62d00000-62e00000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62e03000-62e7c000 rwxp 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62e7c000-62efc000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 62f00000-63000000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-27 23:40:32.043 E/mono-rt ( 7314): 6300c000-6307c000 rwxp 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 6307c000-630fc000 rw-p 00000000 00:00 0 
07-27 23:40:32.043 E/mono-rt ( 7314): 63200000-63400000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-27 23:40:32.046 F/libc    ( 7314): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7314 (ckroads.android)
```

### Log File

```
Time	Device Name	Type	PID	Tag	Message
07-28 11:25:13.465	android_8_0	Warning	1627	Looper	Dispatch took 172ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {2f0b443} cb=android.view.Choreographer$FrameDisplayEventReceiver@63b5ac0 msg=0
07-28 11:25:15.788	android_8_0	Warning	1391	audio_hw_generic	Not supplying enough data to HAL, expected position 1427253 , only wrote 1274400
07-28 11:25:13.803	android_8_0	Warning	2201	OpenGLRenderer	Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
07-28 11:25:13.459	android_8_0	Info	2163	MicroDetectionWorker	onReady
07-28 11:25:13.459	android_8_0	Warning	2163	SpeechLevelGenerator	Really low audio levels detected. The audio input may have issues.
07-28 11:25:13.428	android_8_0	Info	2163	MicrophoneInputStream	mic_started  SR : 16000 CC : 16 SO : 1999
07-28 11:25:13.417	android_8_0	Info	1479	AudioFlinger	AudioFlinger's thread 0xac68c9c0 tid=7397 ready to run
07-28 11:25:13.416	android_8_0	Info	2163	MicrophoneInputStream	mic_starting  SR : 16000 CC : 16 SO : 1999
07-28 11:25:13.416	android_8_0	Info	2163	MultipleReaderAudioSrc	Using micInputStream
07-28 11:25:13.416	android_8_0	Info	2163	MicroRecognitionRunner	Starting detection.
07-28 11:25:13.413	android_8_0	Info	2163	MicroDetectionWorker	onReady
07-28 11:25:13.411	android_8_0	Info	2163	AudioController	Created new AudioSource
07-28 11:25:13.409	android_8_0	Info	2163	MicroDetectionWorker	#startMicroDetector [speakerMode: 0]
07-28 11:25:13.338	android_8_0	Debug	1627	EGL_emulation	eglMakeCurrent: 0x862bc560: ver 2 0 (tinfo 0x81e17180)
07-28 11:25:13.305	android_8_0	Warning	2163	SessionLifecycleManager	Handover failed. Creating new session controller.
07-28 11:25:13.297	android_8_0	Debug	2201	EGL_emulation	eglMakeCurrent: 0x9e285540: ver 2 0 (tinfo 0x9e283380)
07-28 11:25:13.290	android_8_0	Warning	1627	Looper	Dispatch took 155ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {2f0b443} cb=android.view.Choreographer$FrameDisplayEventReceiver@63b5ac0 msg=0
07-28 11:25:13.285	android_8_0	Warning	2163	ThreadPoolDumper	Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
07-28 11:25:13.281	android_8_0	Debug	1627	EGL_emulation	eglMakeCurrent: 0x862bc560: ver 2 0 (tinfo 0x81e17180)
07-28 11:25:13.280	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 4714496
07-28 11:25:13.264	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.247	android_8_0	Debug	1627	EGL_emulation	eglCreateContext: 0x862bc560: maj 2 min 0 rcv 2
07-28 11:25:13.244	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.238	android_8_0	Debug	2163	EGL_emulation	eglMakeCurrent: 0x9e286fe0: ver 2 0 (tinfo 0x9e283e40)
07-28 11:25:13.236	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 4714496
07-28 11:25:13.236	android_8_0	Warning	1627	OpenGLRenderer	Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
07-28 11:25:13.235	android_8_0	Debug	1627	OpenGLRenderer	Swap behavior 1
07-28 11:25:13.235	android_8_0	Info	1627	OpenGLRenderer	Initialized EGL, version 1.4
07-28 11:25:13.214	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.208	android_8_0	Debug	1407	SurfaceFlinger	duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
07-28 11:25:13.208	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 4714496
07-28 11:25:13.204	android_8_0	Debug	1800	CarrierSvcBindHelper	No carrier app for: 0
07-28 11:25:13.191	android_8_0	Info	1627	ActivityManager	Force stopping com.backroads.android appid=10095 user=0: from pid 7386
07-28 11:25:13.190	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.174	android_8_0	Info	7244	zygote	WaitForGcToComplete blocked for 11.066ms for cause ProfileSaver
07-28 11:25:13.167	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.163	android_8_0	Info	7244	zygote	Waiting for a blocking GC ProfileSaver
07-28 11:25:13.150	android_8_0	Debug	1397	gralloc_ranchu	gralloc_alloc: Creating ashmem region of size 14749696
07-28 11:25:13.135	android_8_0	Warning	1627	zygote	failed to open /acct/uid_99003/pid_7101/cgroup.procs: No such file or directory
07-28 11:25:13.134	android_8_0	Info	1478	Zygote	Process 7052 exited due to signal (11)
07-28 11:25:13.130	android_8_0	Warning	1627	ActivityManager	setHasOverlayUi called on unknown pid: 7052
07-28 11:25:13.129	android_8_0	Error	1627	KernelCpuSpeedReader	Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
07-28 11:25:13.126	android_8_0	Info	1627	ActivityManager	Killing 7101:com.android.chrome:sandboxed_process0/u0a95i3 (adj 900): isolated not needed
07-28 11:25:13.118	android_8_0	Warning	1627	ActivityManager	android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:748)
	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1522)
	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:2640)
	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:3039)
	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:17916)
	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:5241)
	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:5431)
	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1643)
	at android.os.BinderProxy.sendDeathNotice(Binder.java:828)
07-28 11:25:13.118	android_8_0	Warning	1627	ActivityManager	Exception when unbinding service com.backroads.android/org.chromium.content.app.SandboxedProcessService0
07-28 11:25:13.118	android_8_0	Error	1406	lowmemorykiller	Error opening /proc/7101/oom_score_adj; errno=2
07-28 11:25:13.117	android_8_0	Error	1627	ConnectivityService	RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=27, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
07-28 11:25:13.116	android_8_0	Warning	1627	InputDispatcher	Attempted to unregister already unregistered input channel '2100292 com.backroads.android/md5c4cc18a51e69a63249ddaa1a2a8cabc9.MainActivity (server)'
07-28 11:25:13.116	android_8_0	Info	1627	WindowManager	WIN DEATH: Window{2100292 u0 com.backroads.android/md5c4cc18a51e69a63249ddaa1a2a8cabc9.MainActivity}
07-28 11:25:13.115	android_8_0	Info	1627	ActivityManager	Process com.backroads.android (pid 7052) has died: vis  +99TOP 
07-28 11:25:13.114	android_8_0	Error	1627	ConnectivityService	RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=26, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ]
07-28 11:25:13.112	android_8_0	Error	1627	ConnectivityService	RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=28, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
07-28 11:25:13.111	android_8_0	Debug	1627	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=27, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@7864827)
07-28 11:25:13.111	android_8_0	Debug	1627	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=26, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ], android.os.BinderProxy@edceae6)
07-28 11:25:13.111	android_8_0	Debug	1627	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=28, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@9777541)
07-28 11:25:13.109	android_8_0	Error	1627	InputDispatcher	channel '2100292 com.backroads.android/md5c4cc18a51e69a63249ddaa1a2a8cabc9.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-28 11:25:13.111	android_8_0	Debug	1627	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=2807-28 11:25:13.109 W/InputDispatcher( 1627): channel '2100292 com.backroads.android/md5c4cc18a51e69a63249ddaa1a2a8cabc9.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-28 11:25:13.106	android_8_0	Warning	1627	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
07-28 11:25:13.106	android_8_0	Warning	1627	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
07-28 11:25:13.095	android_8_0	Error	1406	lowmemorykiller	Error writing /proc/7052/oom_score_adj; errno=22
07-28 11:25:13.095	android_8_0	Warning	1627	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
07-28 11:25:13.095	android_8_0	Warning	1627	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
07-28 11:25:13.095	android_8_0	Info	1627	ActivityManager	Showing crash dialog for package com.backroads.android u0
07-28 11:25:13.084	android_8_0	Info	1627	BootReceiver	Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
07-28 11:25:13.082	android_8_0	Error	1505		Tombstone written to: /data/tombstones//tombstone_02
  Force finishing activity com.backroads.android/md5c4cc18a51e69a63249ddaa1a2a8cabc9.MainActivity
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	backtrace:
    #00 pc 000c10cf  /data/app/Mono.Android.DebugRuntime-6BuOz9tWzcf0EtGsipfRhA==/lib/x86/libmonosgen-32bit-2.0.so
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	Cause: null pointer dereference
    eax 6c06c788  ebx 8afa1ff4  ecx ffffffff  edx ffffffff
    esi 6c123080  edi 6c3a2c28
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip 8acc90cf  ebp 00000000  esp bfeb2450  flags 00210246
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	pid: 7052, tid: 7052, name: ckroads.android  >>> com.backroads.android <<<
07-28 11:25:12.739	android_8_0	Error	7376	DEBUG	ABI: 'x86'
07-28 11:25:12.738	android_8_0	Error	7376	DEBUG	Revision: '0'
07-28 11:25:12.738	android_8_0	Error	7376	DEBUG	Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170901.043/4456315:user/release-keys'
07-28 11:25:12.738	android_8_0	Error	7376	DEBUG	*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-28 11:25:12.738	android_8_0	Info	7376	crash_dump32	performing dump of process 7052 (target tid = 7052)
07-28 11:25:12.738	android_8_0	Info	1505		received crash request for pid 7052
07-28 11:25:12.738	android_8_0	Info	7376	crash_dump32	obtaining output fd from tombstoned
07-28 11:25:12.722	android_8_0	Warning	7376	crash_dump32	type=1400 audit(0.0:36): avc: denied { search } for name="com.google.android.gms" dev="dm-0" ino=41107 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
07-28 11:25:12.715	android_8_0	Error	7052	libc	Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7052 (ckroads.android)
07-28 11:25:12.711	android_8_0	Error	7052	mono-rt	64ff0000-65000000 rwxp 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64f7c000-64f7e000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64e00000-64f00000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64d00000-64e00000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64c00000-64d00000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64b00000-64c00000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64a01000-64b00000 rw-p 00000000 00:00 0          [stack:7240]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64a00000-64a01000 ---p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	649ff000-64a00000 ---p 00000000 00:00 0          [anon:thread stack guard page]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64900000-649ff000 rw-p 00000000 00:00 0          [stack:7241]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	648ff000-64900000 ---p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	648fe000-648ff000 ---p 00000000 00:00 0          [anon:thread stack guard page]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	6487c000-648fc000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64844000-64848000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64700000-64800000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64480000-64700000 rw-p 00000000 00:00 0          [anon:libc_malloc]
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	64100000-64200000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	63f00000-64000000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	63d00000-63e00000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	63b00000-63c00000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	622fd000-63aff000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	62100000-62200000 rw-p 00000000 00:00 0 
07-28 11:25:12.710	android_8_0	Error	7052	mono-rt	61d00000-61e00000 rw-p 00000000 00:00 0 
07-28 11:25:12.709	android_8_0	Error	7052	mono-rt	12c00000-5ac00000 rw-p 00000000 00:01 6573       /dev/ashmem/dalvik-main space (region space) (deleted)
07-28 11:25:12.709	android_8_0	Error	7052	mono-rt	/proc/self/maps:
07-28 11:25:12.562	android_8_0	Warning	1391	audio_hw_generic	Not supplying enough data to HAL, expected position 1119894 , only wrote 1119600
07-28 11:25:09.293	android_8_0	Debug	7052	Mono	Assembly Ref addref Sideroads.Android[0x858fd3c0] -> Sideroads.Core.Schema[0x9b9fdfc0]: 4
07-28 11:25:09.293	android_8_0	Debug	7052	Mono	Loading reference 13 of /storage/emulated/0/Android/data/com.backroads.android/files/.__override__/Sideroads.Android.dll asmctx DEFAULT, looking for Sideroads.Core.Schema, Version=3.0.33.0, Culture=neutral, PublicKeyToken=null
07-28 11:25:08.616	android_8_0	Warning	7052	zygote	Checksum mismatch for dex base.apk
07-28 11:25:08.616	android_8_0	Warning	7052	zygote	Checksum mismatch for dex base.apk
07-28 11:25:08.585	android_8_0	Info	7244	zygote	Increasing code cache capacity to 128KB
07-28 11:25:08.585	android_8_0	Info	7244	zygote	After code cache collection, code=29KB, data=23KB
07-28 11:25:08.583	android_8_0	Info	7244	zygote	Do partial code cache collection, code=30KB, data=22KB
07-28 11:25:08.574	android_8_0	Error	7244	YouTube	Caused by: java.lang.InterruptedException
	at aoaw.get(SourceFile:77)
	at abdb.b(SourceFile:22)
	... 8 more
07-28 11:25:08.574	android_8_0	Error	7244	YouTube	abdl: java.lang.InterruptedException
	at abdb.b(SourceFile:23)
	at agwx.a(SourceFile:137)
	at xmn.a(SourceFile:7)
	at com.google.android.libraries.youtube.common.gcm.YouTubeGcmTaskService.a(SourceFile:18)
	at com.google.android.libraries.youtube.common.gcore.gcoreclient.gcm.impl.GcmTaskServiceDelegator.a(SourceFile:11)
	at qlk.run(SourceFile:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
07-28 11:25:08.574	android_8_0	Error	7244	YouTube	Error in sending SendDeviceContextRequest.
07-28 11:25:08.572	android_8_0	Debug	7052	Mono	Found as 'java_interop_jnienv_call_long_method_a'.
07-28 11:25:08.572	android_8_0	Debug	7052	Mono	Probing 'java_interop_jnienv_call_long_method_a'.
07-28 11:25:08.572	android_8_0	Debug	7052	Mono	Searching for 'java_interop_jnienv_call_long_method_a'.
07-28 11:25:08.572	android_8_0	Debug	7052	Mono	DllImport searching in: '__Internal' ('(null)').
07-28 11:25:08.554	android_8_0	Info	7244	CrashMetricService	Startup metric for 'PRIMES_CRASH_MONITORING_INITIALIZED' dropped.
07-28 11:25:08.527	android_8_0	Info	7244	FA	To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app com.google.android.youtube
07-28 11:25:08.525	android_8_0	Info	7244	FA	To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
07-28 11:25:08.524	android_8_0	Info	7244	FA	App measurement is starting up, version: 12780
07-28 11:25:08.518	android_8_0	Info	7244	FA	Collection disabled with firebase_analytics_collection_enabled=0
07-28 11:25:08.487	android_8_0	Info	7244	PrimesTesting	GserviceFlagsSupplier.get()
07-28 11:25:08.477	android_8_0	Info	1947	zygote	Deoptimizing java.lang.String aqnd.a(android.os.Bundle) due to JIT inline cache
07-28 11:25:08.456	android_8_0	Warning	7244	zygote	Skipping duplicate class check due to unrecognized classloader
07-28 11:25:08.417	android_8_0	Warning	7244	Primes	background initialization
07-28 11:25:08.383	android_8_0	Warning	7244	PrimesInit	Primes instant initialization
07-28 11:25:08.368	android_8_0	Debug	7244	NetworkSecurityConfig	Using Network Security Config from resource network_security_config debugBuild: false
07-28 11:25:08.364	android_8_0	Verbose	1392	EmulatedCamera_BaseCamera	getCameraInfo
07-28 11:25:08.364	android_8_0	Verbose	1392	EmulatedCamera_Camera	getCameraInfo
07-28 11:25:08.362	android_8_0	Debug	7244	DynamitePackage	Instantiating com.google.android.gms.ads.adshield.ChimeraAdShieldCreatorImpl
07-28 11:25:08.362	android_8_0	Debug	7244	DynamitePackage	Instantiated singleton DynamitePackage.
07-28 11:25:08.349	android_8_0	Warning	7244	zygote	Skipping duplicate class check due to unrecognized classloader
07-28 11:25:08.314	android_8_0	Info	7244	DynamiteModule	Selected remote version of com.google.android.gms.ads.dynamite, version >= 20300
07-28 11:25:08.314	android_8_0	Info	7244	DynamiteModule	Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:20300
07-28 11:25:08.314	android_8_0	Warning	7244	zygote	Skipping duplicate class check due to unrecognized classloader
07-28 11:25:08.297	android_8_0	Error	7244	GEL_DELAYED_EVENT_DEBUG	Failed delayed event dispatch, no dispatchers.
07-28 11:25:08.186	android_8_0	Warning	7244	YouTube	Fetching the Gservices key 'failsafe_clear_cache_release_13_02' before the end of the bulk initialization
07-28 11:25:08.184	android_8_0	Warning	7244	YouTube	Fetching the Gservices key 'disable_binder_callback_flush' before the end of the bulk initialization
07-28 11:25:08.155	android_8_0	Warning	7244	ResourceType	ResTable_typeSpec entry count inconsistent: given 30, previously 36
07-28 11:25:08.149	android_8_0	Warning	1627	android.os.Debug	failed to get memory consumption info: -1
07-28 11:25:08.149	android_8_0	Error	1627	memtrack	Couldn't load memtrack module
07-28 11:25:08.147	android_8_0	Info	1627	ActivityManager	Start proc 7244:com.google.android.youtube/u0a78 for service com.google.android.youtube/com.google.android.libraries.youtube.common.gcore.gcoreclient.gcm.impl.GcmTaskServiceDelegator
07-28 11:25:08.139	android_8_0	Warning	7244	zygote	Unexpected CPU variant for X86 using defaults: x86
07-28 11:25:08.125	android_8_0	Warning	1627	android.os.Debug	failed to get memory consumption info: -1
07-28 11:25:08.125	android_8_0	Error	1627	memtrack	Couldn't load memtrack module
07-28 11:25:05.016	android_8_0	Info	3337	PlayCommon	[198] afls.d(172): Successfully uploaded logs.
07-28 11:25:04.882	android_8_0	Info	3337	PlayCommon	[198] afls.d(124): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
07-28 11:25:04.882	android_8_0	Warning	3337	PlayCommon	[198] afls.a(1): No account for auth token provided
07-28 11:25:04.881	android_8_0	Info	3337	PlayCommon	[198] afls.d(22): Preparing logs for uploading
```

**Comment by jonathanpeppers** [comment]
@mfeingol can you provide the version of Visual Studio / Xamarin.Android you're using here? Thanks!

**Comment by mfeingol** [comment]
Sorry, should have mentioned: VS 16.2.0 with whatever version of Xamarin Android that comes with.

**Comment by mfeingol** [comment]
And I should verify when I get home, but I'm 87% sure this is a regression in VS 16.2.0.

**Comment by mfeingol** [comment]
Side note: I'm no longer seeing this after updating Xamarin Forms from 3.6 to 4.1.0.618606. Presumably the equilibrium is sufficiently disturbed by this update that whatever underlying cause is there (memory corruption?) is no longer manifesting in this particular page.

**Comment by mfeingol** [comment]
I haven't seen this in a long time. Closing.
