### ISSUE TITLE
"The "LinkAssemblies" task failed ... at Mono.Linker.Steps.MarkStep.ProcessMarkedTypesWithInterfaces()" prevents successfully linking custom libraries that use certain patterns of generic types in combination with the Realm IL weaver

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3419]
### Steps to reproduce

Attempt to build the attached test case in the Release configuration:

```
msbuild -restore -p:Configuration=Release
```

Test case: [InterfacesRealmWeaver.zip](https://github.com/xamarin/xamarin-android/files/3451703/InterfacesRealmWeaver.zip)

(This test case uses the Fody IL manipulation library via Realm. Hitting the issue requires a fairly particular usage of generic types in combination with the Realm weaver. The issue was originally found by the developers of a full app: <https://github.com/toggl/mobileapp>)

### Expected behavior

With Xamarin.Android 9.3, the build completes successfully.

### Actual behavior

The `LinkAssemblies` step fails:

```
(_LinkAssembliesShrink target) ->
error MSB4018: The "LinkAssemblies" task failed unexpectedly.
error MSB4018: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
error MSB4018:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
error MSB4018:    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
error MSB4018:    at System.Collections.Generic.List`1.Enumerator.MoveNext()
error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMarkedTypesWithInterfaces()
error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
error MSB4018:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
error MSB4018:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Partial workaround

Add **ClassLibrary1** to the **Skip linking assemblies** field in the **Android Options** sections of the Visual Studio project property pages for the Android app project. This would allow an existing application to continue linking most of the user assemblies while skipping specific problematic assemblies that by chance hit this combination of factors involving generic types with the Realm weaver.

### Version information

**Expected** behavior: 

Xamarin.Android SDK 9.3.0.23 (d16-1/ebd7bda)

**Actual** behavior:

Xamarin.Android SDK 9.4.0.51 (d16-2/9fa7775)
Xamarin.Android SDK 9.5.0.27 (d16-3/16c4494)

**Comment by brendanzagaeski** [comment]
The same error occurs with the latest `master` build:

OSS Xamarin.Android 10.0.99 (master@676b131b) ([Jenkins build <span>#</span>676](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android/676/Azure/))

I haven't had a chance to test yet, but based on the description of the issue from the Toggl team, I suspect this also affects iOS, so the fix will likely require changes in https://github.com/mono/linker

**Comment by brendanzagaeski** [comment]
Another curious result is that if I just remove the `ISuperInterface` from `ISubInterface`:

```diff
-public interface ISubInterface : ISuperInterface { }
+public interface ISubInterface { }
``` 

... that stops the problem. If I then `ildasm` the before and after versions of *ClassLibrary1.dll*, and `diff` the output *.il* files, the result looks about as I'd expect:

```diff
@@ -42,5 +42,5 @@
 }
 .module ClassLibrary1.dll
-// MVID: {0ABF3F0E-8ABE-45F5-A3E3-5CF3929928C9}
+// MVID: {797772C4-B0C7-4530-8A31-F0E9C4D53F6D}
 .imagebase 0x00400000
 .file alignment 0x00000200
@@ -48,5 +48,5 @@
 .subsystem 0x0003       // WINDOWS_CUI
 .corflags 0x00000001    //  ILONLY
-// Image base: 0x07230000
+// Image base: 0x06770000


@@ -265,5 +265,4 @@

 .class interface public abstract auto ansi ClassLibrary1.ISubInterface
-       implements ClassLibrary1.ISuperInterface
 {
 } // end of class ClassLibrary1.ISubInterface
```

If I run `ilasm` on the "before" *.il* file and reference the output *.dll* file directly in the app project (along with the necessary Realm dependency assemblies), the linker error occurs.

But if I disable Realm and keep the `public interface ISubInterface : ISuperInterface` line unchanged, the linker error does *not* occur, even though the output from `ildasm` in that scenario *does* include the `implements ClassLibrary1.ISuperInterface` line.

**Comment by heytherewill** [comment]
Any news on this? This is quite a big issue for us, since our iOS binaries are bloody huge atm moment (to the point where we are getting iTunes connect warnings).

**Comment by brendanzagaeski** [comment]
@heytherewill , I don't have any updates from the team on this item at the moment, but if it might be helpful for the Toggl Mobile App, you can re-enable linking all assemblies if you add *Toggl.Storage.Realm* to the list of assemblies to skip.

That is, for Android, include *Toggl.Storage.Realm* in the `<AndroidLinkSkip>` property in the *.csproj* file, and for iOS, add a `--linkskip=Toggl.Storage.Realm` argument to the `<MtouchExtraArgs>` property.

I did a quick local check with the Toggl.Droid project to make sure I could hit the problem before this change and build successfully afterward. If you find that this approach still leaves the app size larger than desired or that it doesn't work for the iOS project, let us know back on this issue so the team can take that into consideration. Thanks!
