### ISSUE TITLE
Problems with Android NDK/SDK Downloads with Prepare Target on Windows 10

### ISSUE THREAD

**Issue by kealist** [xamarin/xamarin-android#3439]
### Steps to Reproduce

1. Fresh Clone
2. Run `msbuild Xamarin.Android.sln /t:Prepare`
3. Dies on downloads for Android SDK/NDKs @ around 8%.   

I tested links manually, and they work fine (can download files).

### Expected Behavior

Able to download SDK/NDKs

### Actual Behavior

```
   -> https://dl.google.com/android/repository/android-2.3.3_r02.zip
    -> https://dl.google.com/android/repository/android-15_r05.zip
    -> https://dl.google.com/android/repository/android-16_r05.zip
    -> https://dl.google.com/android/repository/android-17_r03.zip
    -> https://dl.google.com/android/repository/android-18_r03.zip
    -> https://dl.google.com/android/repository/android-19_r04.zip
    -> https://dl.google.com/android/repository/android-20_r02.zip
    -> https://dl.google.com/android/repository/android-21_r02.zip
    -> https://dl.google.com/android/repository/android-22_r02.zip
    -> https://dl.google.com/android/repository/platform-23_r03.zip
    -> https://dl.google.com/android/repository/platform-24_r02.zip
    -> https://dl.google.com/android/repository/platform-25_r03.zip
    -> https://dl.google.com/android/repository/platform-26_r02.zip
    -> https://dl.google.com/android/repository/platform-27_r03.zip
    -> https://dl.google.com/android/repository/platform-28_r04.zip
    -> https://dl.google.com/android/repository/platform-29_r01.zip
    -> https://dl.google.com/android/repository/docs-24_r01.zip
    -> https://dl.google.com/android/repository/android_m2repository_r47.zip
    -> https://dl.google.com/android/repository/sys-img/android/x86-29_r06.zip
    -> https://dl.google.com/android/repository/android-ndk-r20-windows-x86_64.zip
    -> https://dl.google.com/android/repository/build-tools_r29-windows.zip
    -> https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
    -> https://dl.google.com/android/repository/emulator-windows-5598178.zip
      downloading android-2.3.3_r02.zip
      downloading android-15_r05.zip
      downloading android-16_r05.zip
      downloading android-17_r03.zip
      downloading android-18_r03.zip
      downloading android-19_r04.zip
      downloading android-20_r02.zip
      downloading android-21_r02.zip
      downloading android-22_r02.zip
      downloading platform-23_r03.zip
      downloading platform-24_r02.zip
      downloading platform-25_r03.zip
      downloading platform-26_r02.zip
      downloading platform-27_r03.zip
      downloading platform-28_r04.zip
      downloading platform-29_r01.zip
      downloading docs-24_r01.zip
      downloading android_m2repository_r47.zip
      downloading x86-29_r06.zip
      downloading android-ndk-r20-windows-x86_64.zip
      downloading build-tools_r29-windows.zip
      downloading sdk-tools-windows-4333796.zip
      downloading emulator-windows-5598178.zip
  Download progress: 8.59% (307 MB at 307 MB/s)
  Download progress: 8.59% (307 MB at 1.29 KB/s)
  Download progress: 8.59% (307 MB at 22.5 KB/s)
  Download progress: 8.59% (307 MB at 9.04 KB/s)
  Download progress: 8.59% (307 MB at 7.75 KB/s)
  Download progress: 8.59% (307 MB at 3.88 KB/s)
  Download progress: 8.59% (307 MB at 11.6 KB/s)
  Download progress: 8.59% (307 MB at 14.2 KB/s)
  Download progress: 8.59% (307 MB at 3.88 KB/s)
  Download progress: 8.6% (307 MB at 41.8 KB/s)

  Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception.
  System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception
  . ---> System.InvalidOperationException: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: The read operation failed, see inner exception. ---> System.IO.IOException: The read operation fa
  iled, see inner exception. ---> System.Net.WebException: The request was aborted: The request was canceled.
     at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
     at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     --- End of inner exception stack trace ---
     at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at Xamarin.Android.Prepare.Utilities.<DoDownload>d__37.MoveNext() in C
```

### Version Information
Tried with MS build 15 and 16 with same result

Used 2017 VS Dev Console & ConsoleZ with same result.

**Comment by brendanzagaeski** [comment]
By coincidence, I was setting up a new checkout of xamarin-android today on Windows and ran across the same error. In case it might be useful for anyone else, here's the quick-and-dirty local edit I used to work around the error:

```patch
diff --git a/build-tools/xaprepare/xaprepare/Application/Utilities.cs b/build-tools/xaprepare/xaprepare/Application/Utilities.cs
index 155c6693..2f819f7c 100644
--- a/build-tools/xaprepare/xaprepare/Application/Utilities.cs
+++ b/build-tools/xaprepare/xaprepare/Application/Utilities.cs
@@ -465 +465 @@ namespace Xamarin.Android.Prepare
-                       using (var httpClient = new HttpClient ()) {
+                       using (var httpClient = new HttpClient () { Timeout = TimeSpan.FromMinutes (100) } ) {
```

After I made that change, I reran `msbuild Xamarin.Android.sln /t:Prepare`. (The `Prepare` target automatically rebuilds `xaprepare` to include the new change.)

**Comment by grendello** [comment]
While the exception in OP **may** be a timeout (the error verbiage suggests that), it may also be a "legitimate" remote server error which could have closed the connection. However, @brendanzagaeski's idea is a good one and so I opened a PR to that effect. @kealist, would you please test if Brendan's suggestion works for you?

**Comment by kealist** [comment]
@grendello I tested @brendanzagaeski 's patch.  It fixes the issue, so thank you.  

Another comment,  I think the `Download Progress` logging leaves something to be desired, not providing user with interpret-able or useful info (and only is updated once a minute).   However that only affects people for initial run or whenever there is a new SDK/NDK to download

**Comment by grendello** [comment]
@kealist the sparse logging was done this way on purpose - to make our CI logs easier to read with slightly lower signal-to-noise ratio. Fortunately, as you noted, it doesn't show up that often - most of the time you'll watch it on the very first run only and after that only very occasionally.

**Comment by kealist** [comment]
@grendello I understand and saw the sparse idea.  I was referring to it printing out multiple lines at once, such as:

```
 Download progress: 8.59% (307 MB at 307 MB/s)
  Download progress: 8.59% (307 MB at 1.29 KB/s)
  Download progress: 8.59% (307 MB at 22.5 KB/s)
  Download progress: 8.59% (307 MB at 9.04 KB/s)
  Download progress: 8.59% (307 MB at 7.75 KB/s)
  Download progress: 8.59% (307 MB at 3.88 KB/s)
  Download progress: 8.59% (307 MB at 11.6 KB/s)
  Download progress: 8.59% (307 MB at 14.2 KB/s)
  Download progress: 8.59% (307 MB at 3.88 KB/s)
```

which is nonsense.   Maybe it's downloading multiple files at different speeds?  I don't know.
