### ISSUE TITLE
CI build under systemprofile account fails on signing

### ISSUE THREAD

**Issue by cail** [xamarin/xamarin-android#3547]
### Steps to Reproduce

1. build any android apk with signature key
2. for this use CI automation which runs under system account (think this is the key to the problem)
3. see signing failed because of _CreateAndroidDebugSigningKey task

### Expected Behavior

build success

### Actual Behavior

First, its not clear why build system does _CreateAndroidDebugSigningKey even if I build **Release** configuration.
Next, the path for the system account:  
```C:\Windows\system32\config\systemprofile\AppData\Local\Xamarin\Mono for Android```
does not exists.
Next, even if I create this path, the build still fails second time with
```Key pair not generated, alias <androiddebugkey> already exists``` because debug key already generated and keytool will not overwrite it.

### Version Information

VS2019 Community edition, Xamarin

### Log File

```
[00:16:42][Execute app] _CreateAndroidDebugSigningKey:
[00:16:42][Execute app]   C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\keytool.exe -genkeypair -alias androiddebugkey -storepass android -keypass android -keystore "C:\Windows\system32\config\systemprofile\AppData\Local\Xamarin\Mono for Android\debug.keystore" -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -validity 10950 
[00:16:42][Execute app] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(3205,2): error ANDKT0000: keytool error: java.lang.Exception: Key pair not generated, alias <androiddebugkey> already exists [C:\BuildAgent\work\445be90eac994802\app-android\app-android.csproj]
```

**Comment by dellis1972** [comment]
I just looked at the code if '_ApkDebugKeyStore' is not set then we will try to create a key https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L3119.

To work around this issue you can provide your own `AppSettingsDirectory` which will specify where the key will be created , for example.

```
<AppSettingsDirectory>$(MSBuildThisFileDirectory)</AppSettingsDirectory>
```

Checkin or download a `debug.keystore` in that directory which will then be picked up by our build system.

**Comment by cail** [comment]
> Does your Release build contain keystore information?

Yes it does:
```
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>xxx</AndroidSigningKeyStore>
    <AndroidSigningStorePass>xxx</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>xxx</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>xxx</AndroidSigningKeyPass>
  </PropertyGroup>
```

and still it tried to generate debug key in release mode.


> would you be able to use a different user account in CI to work around this problem for now?

Yes, I've ended up with switching to different account for now because I've faced more build issues. But SYSTEM acc is the default config for teamcity - so thats not only me who may findout these issues.

Here is the last issue I've seen (looks like related to compat libraries installation), again into system account Local folder:

```
[00:50:28][Execute xxx] _CompileToDalvikWithDx:
[00:50:28][Execute xxx]   Creating directory "obj\Release\90\proguard".
[00:50:28][Execute xxx]   C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -Dfile.encoding=UTF8 -Xmx1G -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\\lib\dx.jar" --dex --no-strict --input-list=C:\BuildAgent\temp\buildTmp\tmp7517.tmp --output obj\Release\90\android\bin 
[00:51:36][Execute xxx]   
[00:51:36][Execute xxx]   UNEXPECTED TOP-LEVEL EXCEPTION:
[00:51:36][Execute xxx]   java.io.FileNotFoundException: C:\Windows\system32\config\systemprofile\AppData\Local\Xamarin\Xamarin.Android.Support.v7.MediaRouter\23.3.0.0\embedded\classes.jar (The system cannot find the path specified)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.open(Native Method)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:165)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.processOne(Main.java:678)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.main(Main.java:244)
[00:51:36][Execute xxx]   	at com.android.dx.command.Main.main(Main.java:95)
[00:51:36][Execute xxx]   
[00:51:36][Execute xxx]   UNEXPECTED TOP-LEVEL EXCEPTION:
[00:51:36][Execute xxx]   java.io.FileNotFoundException: C:\Windows\system32\config\systemprofile\AppData\Local\Xamarin\Xamarin.Android.Support.v7.MediaRouter\23.3.0.0\embedded\libs\internal_impl-23.3.0.jar (The system cannot find the path specified)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.open(Native Method)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[00:51:36][Execute xxx]   	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:165)
[00:51:36][Execute xxx]   	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.processOne(Main.java:678)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
[00:51:36][Execute xxx]   	at com.android.dx.command.dexer.Main.main(Main.java:244)
[00:51:36][Execute xxx]   	at com.android.dx.command.Main.main(Main.java:95)
[00:51:36][Execute xxx]   2 errors; aborting
[00:51:36][Execute xxx] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2789,3): error MSB6006: "java.exe" exited with code 1. [C:\BuildAgent\work\445be90eac994802\xxxrive-android\xxxrive-android.csproj]
[00:51:38][Execute xxx] Done Building Project "C:\BuildAgent\work\445be90eac994802\xxxrive-android\xxxrive-android.csproj" (SignAndroidPackage target(s)) -- FAILED.
[00:51:38][Execute xxx] 
[00:51:38][Execute xxx] Build FAILED.
```

Not sure if thats really important being able to build under system account - may be just makes sense documenting this somewhere.

**Comment by dellis1972** [comment]
So we implemented a fix where the Debug keystone will NOT be created if `AndroidKeyStore` is set to `True`. 

If anyone wants any further control on where the debug keystore is created you can override the  `AppSettingsDirectory` in you csproj

`<AppSettingsDirectory>$(MSBuildThisFileDirectory)</AppSettingsDirectory>`

or via the command line

`/p:AppSettingsDirectory=.`

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published for macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by captainjono** [comment]
Im not sure what the workaround was supposed to be that im seeing this on `VS2019 16.9` and was required to add
`<AppSettingsDirectory>$(MSBuildThisFileDirectory)</AppSettingsDirectory>` to workaround the issue

**Comment by jonathanpeppers** [comment]
@captainjono the fix here was to not automatically generate a `debug.keystore` file if the project used its own `.keystore`.

Can you setup your own `.keystore` in your project?
