### ISSUE TITLE
Can't deploy from an aab to Samsung tablet Android 4.4.4. VS16.3.0 Preview 3.0

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3602]
From the diagnostic error log.

Cannot restrict modules when the device matches a non-split APK.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Cannot restrict modules when the device matches a non-split APK.
	at com.android.tools.build.bundletool.model.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:83)
	at com.android.tools.build.bundletool.device.ApkMatcher.matchesApk(ApkMatcher.java:232)
	at com.android.tools.build.bundletool.device.ApkMatcher.getMatchingApksFromVariant(ApkMatcher.java:116)
	at com.android.tools.build.bundletool.device.ApkMatcher.getMatchingApks(ApkMatcher.java:97)
	at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:165)
	at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:145)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:156)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

I get exactly the same error with my own version of Install_apks.

The same aab uploaded to the Play Store installs fine on that device though.

**Comment by gmck** [comment]
Tried removing module=_ALL_ 
Got 
The APKs have been extracted in the directory: C:\Users\Graham\AppData\Local\Temp\6422847329696393715
but also included.
[BT:0.10.0] Error: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:106)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at com.google.common.base.Joiner.join(Joiner.java:205)
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1024)
	at com.android.ddmlib.Device.installPackage(Device.java:902)
	at com.android.ddmlib.Device.installPackage(Device.java:880)
	at com.android.ddmlib.Device.installPackage(Device.java:869)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:113)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:94)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:82)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:44)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:165)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

Nothing on the device.
All my other devices Android 5.1.1 (Nexus4),  7.1.1 (Samsung tablet) 8.1.0 (Nexus5x) 9.0 (Samsung S8) and 10.0 (Pixel3a) deploy well. Either directly from VS2019 16.3.0 Prev 3.0 or via Install_Apks.

**Comment by jonathanpeppers** [comment]
Can you attach the diagnostic MSBuild log? Thanks!
