### ISSUE TITLE
Binding libraries do not consider/reference @(AndroidJavaLibrary)

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#3776]
### Steps to Reproduce

1. Create a binding project (jar2xml)
2. Install `Xamarin.Kotlin.StdLib`
3. Build and observe the 

### Expected Behavior
The generator should have a reference to 3 Kotlin libraries:
 - org.jetbrains.kotlin.kotlin-stdlib-common.jar 
 - org.jetbrains.annotations.jar 
 - org.jetbrains.kotlin.kotlin-stdlib.jar 

### Actual Behavior
No references, and I get exceptions like:

```
  java.lang.NoClassDefFoundError: kotlin/jvm/internal/DefaultConstructorMarker
  	at java.lang.Class.getDeclaredConstructors0(Native Method)
  	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
  	at jar2xml.JavaClass.doAppendToDocument(JavaClass.java:630)
  	at jar2xml.JavaClass.appendToDocument(JavaClass.java:561)
  	at jar2xml.JavaPackage.appendToDocument(JavaPackage.java:72)
  	at jar2xml.Start.main(Start.java:134)
  Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.DefaultConstructorMarker
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

### Version Information

Mono 6.4.0 and Android 10.0.3

https://gist.github.com/mattleibow/9981159519aa2e02ce85f72e4190ee42

### Log File

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/3719747/msbuild.binlog.zip)

### Workaround

```xml
<Target Name="_ExportJarToXml_Fixups" BeforeTargets="ExportJarToXml">
  <ItemGroup>
    <ReferenceJar Include="@(AndroidJavaLibrary)" />
  </ItemGroup>
</Target>
```

**Comment by amitrkalghatgi** [comment]
@mattleibow , @grendello is this fixed or still under consideration...? I am using Visual Studio Community 8.6.5.

**Comment by mattleibow** [comment]
Looking at the workaround, just make the before target be something like build... BeforeTargets=Build

That should work. No idea what I was doing there...

**Comment by jonathanpeppers** [comment]
`jar2xml` is deprecated and won't be available in .NET 6, does this issue occur for `class-parse`?

See: https://github.com/xamarin/xamarin-android/blob/799506a9dfb746b8bdc8a4ab77e19eee875f00e3/Documentation/guides/messages/xa4231.md

**Comment by mattleibow** [comment]
I think there is still an issue:
> but Class parser has a issue....

**Comment by DavidMarquezF** [comment]
I'm using class-parser and it appears that this issue is happening. I'm trying to create bindings for AFollestad's MaterialDialogs library (from the aar).
```
Error while processing '[Method] java.time.temporal.Temporal addTo(java.time.temporal.Temporal temporal, long amount)' in '[Class] java.time.temporal.ChronoUnit': Type 'java.time.temporal.Temporal' was not found. (TaskId:60)
1>  Error while processing '[Method] java.time.temporal.Temporal adjustInto(java.time.temporal.Temporal temporal, long newValue)' in '[Class] java.time.temporal.ChronoField': Type 'java.time.temporal.Temporal' was not found. (TaskId:60)
1>  Error while processing '[Constructor] MaterialDialog(android.content.Context p0, com.afollestad.materialdialogs.DialogBehavior p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.MaterialDialog': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] MaterialDialog.Companion(kotlin.jvm.internal.DefaultConstructorMarker $constructor_marker)' in '[Class] com.afollestad.materialdialogs.MaterialDialog.Companion': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] WhichButton.Companion(kotlin.jvm.internal.DefaultConstructorMarker $constructor_marker)' in '[Class] com.afollestad.materialdialogs.WhichButton.Companion': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogActionButton(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.button.DialogActionButton': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogActionButton.Companion(kotlin.jvm.internal.DefaultConstructorMarker $constructor_marker)' in '[Class] com.afollestad.materialdialogs.internal.button.DialogActionButton.Companion': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogActionButtonLayout(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogActionButtonLayout.Companion(kotlin.jvm.internal.DefaultConstructorMarker $constructor_marker)' in '[Class] com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout.Companion': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogRecyclerView(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.list.DialogRecyclerView': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] BaseSubLayout(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.main.BaseSubLayout': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogScrollView(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.main.DialogScrollView': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogTitleLayout(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.main.DialogTitleLayout': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
1>  Error while processing '[Constructor] DialogContentLayout(android.content.Context p0, android.util.AttributeSet p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)' in '[Class] com.afollestad.materialdialogs.internal.message.DialogContentLayout': Type 'kotlin.jvm.internal.DefaultConstructorMarker' was not found. (TaskId:60)
```

Xamarin.Kotlin.StdLib is installed (v1.3.50.1).

This started happening after installing Xamarin.Kotlin.StdLib. Before, there were other errors because I didn't have it installed, but the constructor did get created correctly. After installing the nuget, the other errors were resolved but this one appeared.

**Comment by jpobst** [comment]
Does Kotlin add other "non-default" constructors added that can be used instead?  If so, the best bet would be to use `metadata` to remove these constructors.  

A fix on our side would be to make `kotlin.jvm.internal.DefaultConstructorMarker` `public` in the `Xamarin.Kotlin.StdLib` binding.

However, then users would have to use it like this:
```
var obj = new MyKotlinClass (new DefaultConstructorMarker ());
```

which seems less than ideal.

**Comment by DavidMarquezF** [comment]
I believe that it doesn't, since while inspecting the aar, the MaterialDialog class (for example), only offers one constructor:
`public MaterialDialog(@NotNull Context windowContext, @NotNull DialogBehavior dialogBehavior) `

From their github I can see that the only constructor is (view [here](https://github.com/afollestad/material-dialogs/blob/66582d9993bcf55bfea873b4bf484a429ce3df36/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.kt#L56-L59)):

```
class MaterialDialog(
  val windowContext: Context,
  val dialogBehavior: DialogBehavior = DEFAULT_BEHAVIOR
) : Dialog(windowContext, inferTheme(windowContext, dialogBehavior)) {
```


In the error we can see that the constructor error is `MaterialDialog(android.content.Context p0, com.afollestad.materialdialogs.DialogBehavior p1, int p2, kotlin.jvm.internal.DefaultConstructorMarker p3)` so I'm not really sure what's happening there. I hope this info is of some help.

Again this started happening after installing Kotlin stdlib. Before adding the reference to nuget, the constructor was binded correctly.

**Comment by akalghatgi** [comment]
> I think there is still an issue:
> 
> > but Class parser has a issue....
> 
> @amitrkalghatgi can you confirm? Even with a rebuild?

@mattleibow yes issue is still there...

**Comment by amitrkalghatgi** [comment]
> I think there is still an issue:
> 
> > but Class parser has a issue....
> 
> @amitrkalghatgi can you confirm? Even with a rebuild?

@mattleibow yes.. issue is still there...

**Comment by jpobst** [comment]
> Again this started happening after installing Kotlin stdlib. Before adding the reference to nuget, the constructor was binded correctly.

Did you verify that the constructor was actually bound correctly? Or just did not report an error?

My hunch is that there would have been so many other errors without the Kotlin Stdlib that it probably didn't even make it to trying to bind the constructor.  😉
