### ISSUE TITLE
Can't compile on release mode

### ISSUE THREAD

**Issue by mariohik** [xamarin/xamarin-android#3817]
I'm not being able to compile my project on release mode anymore without "Use Shared Runtime" checked.

![image](https://user-images.githubusercontent.com/38980017/65823053-62288200-e225-11e9-990d-95f02d969e57.png)

> 2>  C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error : The method or operation is not implemented.

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 117

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 50

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute() in D:\a\1\s\source\Xamarin.AndroidX.Migration\BuildTasks\CecilfyFiles.cs:line 35

If I check the option, I can compile, but not deploy to a device.

![image](https://user-images.githubusercontent.com/38980017/65823075-c0556500-e225-11e9-8b63-e893f193f059.png)

> ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by tranb3r** [comment]
Same problem for me too.
It's been introduced in Visual Studio 16.4.0 pre-1 and it's still happening in pre-3 !! No issue when using VS 16.3.7.
It's only happening when android linker is set to "full" or "sdkonly" (no problem when disabling linker).

@mattleibow @Redth Any progress ?

**Comment by kimhongka** [comment]
I am using Visual studio mac and I am facing the same problem.
I was able to build the solution with D8/R8/Linker(sdk only) and "AndroidX" in the current stable Visual studio mac, but not using Visual Studio for Mac 8.4.0.2414. It works if I disabled Linker though. 

I need to use the preview Xamarin.Android version, which contains the fix of the KotlinX-android issue, so I have been using the preview version of VS mac. Please check this issue out.

**Comment by tranb3r** [comment]
Still not fixed in visual studio 16.4.0-pre.5.0

**Comment by tranb3r** [comment]
Still having the same error with xamarin.androidx.migration\1.0.0-preview06 and Visual Studio 16.4.0-pre.6.0.
@Redth Is this issue being investigated ? I hope it will be fixed in Visual Studio 16.4.0 stable release. Thanks

**Comment by Redth** [comment]
@tranb3r do you have a repro solution you can share? I can't reproduce the same errors here, everything works great with r8/d8/linker sdk only with the latest AndroidX packages.
