### ISSUE TITLE
mono.android.runtime.JavaObject cannot be cast to byte[] when using List<byte[]>

### ISSUE THREAD

**Issue by BobbyShoe** [xamarin/xamarin-android#4098]
### Steps to Reproduce

1.   Declare a List<byte[]> in C#.   Pass this to a Java library and the mono.android.runtime.JavaObject cannot be cast to byte[] error is received when the object is accessed in Java.

Here is the sample call from the Java library.  The call to csdBuffer.get throws the exception.

public static void setCsdBuffers(MediaFormat format, List<byte[]> csdBuffers) {
    for (int i = 0; i < csdBuffers.size(); i++) {
      format.setByteBuffer("csd-" + i, ByteBuffer.wrap(csdBuffers.get(i)));
    }
  }

Seems like a similar issue to the java.lang.ClassCastException information mentioned on this page
https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#javalangclasscastexception-monoandroidruntimejavaobject-cannot-be-cast-to

However the work around suggested there states to use the similar Java collection for the inner collection in the generic.  However in this case a byte[] is the inner collection, so is there some comparable Java type that could be used?

### Expected Behavior
A List<byte[]> can be passed between C# and Java code.

### Actual Behavior
ClassCastException is thrown when the Java code attempts to access the byte array.

### Version Information
Xamarin 16.4.000.307

Running on Android 7.1

### Log File
 Caused by: java.lang.ClassCastException: mono.android.runtime.JavaObject cannot be cast to byte[]

**Comment by jonpryor** [comment]
The bug is that `JavaConvert.LocalJniHandleConverters` doesn't special-case array types: https://github.com/xamarin/xamarin-android/blob/38a10a17eaf16b052e3c5ffbee502565acc688f5/src/Mono.Android/Java.Interop/JavaConvert.cs#L310-L356

Consider this Java method:

```java
public class Gxa4098 {
	public static int genericListMarshaling (List<byte[]> bytes) {
		int count = 0;
		for (byte[] value : bytes ) {
			count += value.length;
		}
		return count;
	}
}
```

Which results in the binding:

```
[Register ("genericListMarshaling", "(Ljava/util/List;)I", "")]
public static unsafe int GenericListMarshaling (global::System.Collections.Generic.IList<byte[]> p0)
{
	const string __id = "genericListMarshaling.(Ljava/util/List;)I";
	IntPtr native_p0 = global::Android.Runtime.JavaList<byte[]>.ToLocalJniHandle (p0);
	try {
		JniArgumentValue* __args = stackalloc JniArgumentValue [1];
		__args [0] = new JniArgumentValue (native_p0);
		var __rm = _members.StaticMethods.InvokeInt32Method (__id, __args);
		return __rm;
	} finally {
		JNIEnv.DeleteLocalRef (native_p0);
	}
}
```

Which calls `Android.Runtime.JavaList<byte[]>.ToLocalJniHandle()`: https://github.com/xamarin/xamarin-android/blob/38a10a17eaf16b052e3c5ffbee502565acc688f5/src/Mono.Android/Android.Runtime/JavaList.cs#L949-L961

Which hits the `JavaList<T>` constructor, which calls `JavaList<T>.Add()`: https://github.com/xamarin/xamarin-android/blob/38a10a17eaf16b052e3c5ffbee502565acc688f5/src/Mono.Android/Android.Runtime/JavaList.cs#L712

Which calls `JavaConvert.WithLocalJniHandle()`: https://github.com/xamarin/xamarin-android/blob/38a10a17eaf16b052e3c5ffbee502565acc688f5/src/Mono.Android/Android.Runtime/JavaList.cs#L800-L812

Because `JavaConvert.LocalJniHandleConverters` doesn't special-case arrays, we hit the "fallback" path, which wraps the array into a `JavaObject`: https://github.com/xamarin/xamarin-android/blob/38a10a17eaf16b052e3c5ffbee502565acc688f5/src/Mono.Android/Java.Interop/JavaConvert.cs#L353-L356

*A* fix to consider would be to add array types to `JavaConvert.LocalJniHandleConverters`, but we might want to instead consider using following the "recursive type" approach used around `JNIEnv.NewArray(Array, Type)`.

**Comment by jonpryor** [comment]
Patch for possible unit test:

```diff
diff --git a/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs b/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
index d6cb60db..c53be34a 100644
--- a/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
+++ b/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
@@ -1,4 +1,5 @@
 using System;
+using System.Collections.Generic;
 
 using NUnit.Framework;
 
@@ -201,6 +202,19 @@ namespace Xamarin.Android.JcwGenTests {
 			var m = e.Message;
 			Assert.IsTrue (e.GetMessageInvoked);
 		}
+
+		// Context: https://github.com/xamarin/xamarin-android/issues/4098
+		[Test]
+		public void GenericListMarshaling ()
+		{
+			var list = new List<byte[]> {
+				new byte[]{ 1, 2, 3 },
+				new byte[]{ 4, 5 },
+				new byte[]{ 6 },
+			};
+			int count = Com.Xamarin.Android.Gxa4098.GenericListMarshaling (list);
+			Assert.AreEqual (6, count);
+		}
 	}
 
 	class ConstructorTest : Com.Xamarin.Android.CallMethodFromCtor {
diff --git a/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj b/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj
index 044fe4bd..4826e56b 100644
--- a/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj
+++ b/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj
@@ -97,6 +97,9 @@
     <TestJarEntry Include="java\com\xamarin\android\DataListener.java">
       <OutputFile>Jars/xamarin-test.jar</OutputFile>
     </TestJarEntry>
+    <TestJarEntry Include="java\com\xamarin\android\Gxa4098.java">
+      <OutputFile>Jars/xamarin-test.jar</OutputFile>
+    </TestJarEntry>
     <TestJarEntry Include="java\com\xamarin\android\Logger.java">
       <OutputFile>Jars/xamarin-test.jar</OutputFile>
     </TestJarEntry>
diff --git a/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/Gxa4098.java b/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/Gxa4098.java
new file mode 100644
index 00000000..79ee5f06
--- /dev/null
+++ b/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/Gxa4098.java
@@ -0,0 +1,13 @@
+package com.xamarin.android;
+
+import java.util.List;
+
+public class Gxa4098 {
+	public static int genericListMarshaling (List<byte[]> bytes) {
+		int count = 0;
+		for (byte[] value : bytes ) {
+			count += value.length;
+		}
+		return count;
+	}
+}
```

**Comment by BenBtg** [comment]
I have a Android binding for the Pointr SDK which is impacted by this issue and causes the following exception to be thrown.
`java.lang.ClassCastException: mono.android.runtime.JavaObject cannot be cast to float[]
	at com.qozix.tileview.paths.BasicPathView.onDraw(BasicPathView.java:131)
	at android.view.View.draw(View.java:21975)`

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android SDK version 11.0.99.9.

Fix included on Windows in Visual Studio 2019 version 16.8 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.8 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update)

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.1.0.17.

Fix included on Windows in Visual Studio 2019 version 16.8. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.8. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by dkexception** [comment]
I'm getting `"**mono.android.runtime.JavaObject cannot be cast to java.util.Collection**"` related to this problem. Trying to add a Kotlin AAR file (using bindings library project) and it contains a method which accepts a Kotlin Map<String, List<List<String>>, which gets converted to IDictionary<IList<IList<string>> in Xamarin. @brendanzagaeski can you please suggest
