### ISSUE TITLE
Build the Xamarin from source

### ISSUE THREAD

**Issue by kant2002** [xamarin/xamarin-android#4257]
### Steps to Reproduce
I have somewhat old (couple month) checkout

1. git pull
2. Open Developer Command Prompt for VS2019
3. msbuild Xamarin.Android.sln /t:Prepare

### Expected Behavior

MSBuild task completed without error. Some instructions how to solve that/or

### Actual Behavior

```
  Step Xamarin.Android.Prepare.Step_InstallCorrettoOpenJDK failed: 7zip executable 'D:\d\kant\GitHub\xamarin-android\packages\7-zip.commandline\18.1.0\tools\x64\7za.exe' not found
  System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_InstallCorrettoOpenJDK failed: 7zip executable 'D:\d\kant\GitHub\xamarin-android\packages\7-zip.commandline\18.1.0\tools\x64\7za.exe' not found ---> System.InvalidOpe
  rationException: 7zip executable 'D:\d\kant\GitHub\xamarin-android\packages\7-zip.commandline\18.1.0\tools\x64\7za.exe' not found
     at Xamarin.Android.Prepare.ToolRunner..ctor(Context context, Log log, String toolPath) in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\ToolRunners\ToolRunner.cs:line 57
     at Xamarin.Android.Prepare.SevenZipRunner..ctor(Context context, Log log, String toolPath) in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\ToolRunners\SevenZipRunner.cs:line 19
     at Xamarin.Android.Prepare.Utilities.<Unpack>d__17.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Application\Utilities.cs:line 196
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Xamarin.Android.Prepare.Step_InstallCorrettoOpenJDK.<Execute>d__2.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Steps\Step_InstallCorrettoOpenJDK.cs:line 48
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Xamarin.Android.Prepare.Step.<Run>d__17.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Application\Step.cs:line 42
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Xamarin.Android.Prepare.Scenario.<Run>d__14.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Application\Scenario.cs:line 33
     --- End of inner exception stack trace ---
     at Xamarin.Android.Prepare.Scenario.<Run>d__14.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Application\Scenario.cs:line 44
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Xamarin.Android.Prepare.Context.<Execute>d__200.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Application\Context.cs:line 790
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Xamarin.Android.Prepare.App.<Run>d__3.MoveNext() in D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare\Main.cs:line 164
```

### Version Information

From master

### additional info
Content of `packages` folder
```
Irony.0.9.1
Microsoft.Build.Framework.14.3.0
Microsoft.Build.Tasks.Core.14.3.0
Microsoft.Build.Utilities.Core.14.3.0
Microsoft.Web.Xdt.2.1.1
Microsoft.Xml.SgmlReader.1.8.14
Mono.Options-PCL.2.0.40
Mono.Options.5.3.0.1
Mono.Posix.NETStandard.1.0.0
Newtonsoft.Json.6.0.4
NodaTime.2.4.5
NUnit.3.11.0
NUnit.Console.3.9.0
NUnit.ConsoleRunner.3.9.0
NUnit.Extension.NUnitProjectLoader.3.6.0
NUnit.Extension.NUnitV2Driver.3.7.0
NUnit.Extension.NUnitV2ResultWriter.3.6.0
NUnit.Extension.TeamCityEventListener.1.0.2
NUnit.Extension.VSProjectLoader.3.6.0
NUnit3TestAdapter.3.12.0
System.Collections.4.0.11
System.Runtime.4.1.0
System.Runtime.InteropServices.4.1.0
Unofficial.Ionic.Zip.1.9.1.8
Xamarin.Build.AsyncTask.0.3.4
Xamarin.LibZipSharp.1.0.5
```

Running 
```
msbuild D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare.sln
```
does not helps.

`7-zip.commandline` of version 18.1 in the Nuget global cache, but not in packages.

What I can do make it work?

**Comment by grendello** [comment]
@kant2002 7zip comes from a nuget, which is probably not restored properly on your machine, try:

```
msbuild /t:Restore D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare.sln
```

And if it still doesn't help, clear the nuget cache and try again. Please let me know if that helped.

**Comment by kant2002** [comment]
@grendello thanks. Initially I manage to pass the original issue by copying Nuget package from my local Nuget cache to `packages` folder. but after some time, it fails on the installation for `Step Xamarin.Android.Prepare.Step_ThirdPartyNotices failed: License file D:\d\kant\GitHub\xamarin-android\packages\xamarin.libzipsharp\1.0.8\Licences\libzip\LICENSE does not exist`

I decide to "optimize" a bit, and instead of cleanup Nuget cache which is quite expensive I simply nuke `packages` folder. after that nothing restored in that folder. 

```
msbuild /t:Restore D:\d\kant\GitHub\xamarin-android\build-tools\xaprepare\xaprepare.sln
```
does not populates local `packages` folder. Any idea?

**Comment by kant2002** [comment]
@grendello I somehow manage to build, but you probably want to look at #4275 to better understand what kind of issues I experience.

**Comment by grendello** [comment]
@kant2002 glad it worked in the end. #4275 is the actual issue it seems, but I'll let @dellis1972 and @jonathanpeppers review it since it relates more to the build system than to `xaprepare` itself. I'm going to close this issue as it appears to be resolved, please reopen if you think otherwise :)

**Comment by kant2002** [comment]
This issue is issue with building Xamarin, not using Xamarin. But I suspect it’s an issue which appear with same condition. #4275 is for using Xamarin and I want to build Xamarin for trying out solution. This is where I discover this build problems

**Comment by grendello** [comment]
@kant2002 the underlying cause appears to be the same (since XA itself uses nugets and it's the nugets that give you trouble),  and since #4275 has a much better description of the problem, this issue here is not needed

**Comment by kant2002** [comment]
Make sense. I was confused. Thanks
