### ISSUE TITLE
16.5.0 Preview 2.0 System.IO.IOException: The process cannot access the file  because it is being used by another process.

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4274]
Preview 2.0 is giving these errors on nearly every build if not cleaned between builds. Edit an xml file be it a style, theme, dimen or a layout etc, almost guarantees the IOException. Clean and then build and all is ok.  Something is locking the files between builds. Don't know if it makes any difference but it is an AndroidX app now running the release version of libs, but it was doing the same previously with release candidate versions. The exception rarely ever relates to the file that was just edited.

**Comment by grendello** [comment]
@gmck could you attach a full diagnostic log of the failed build or, if not possible, full exception trace when the issue happens?

**Comment by gmck** [comment]
Here is an example - just commented out the following from styles.xml as a test.
<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>

Note that the named file was not changed. Could you please comment on what a .xml.bk file is? Can't ever remember seeing the bk extension tacked onto an xml file before this started.

Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.IOException: The process cannot access the file 'D:\ProjectsVS2019Preview\OBDNowProto\obj\Debug\100\res\layout\fragment_supported_pids.xml.bk' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Monodroid.AndroidResource.UpdateXmlResource(String res, String filename, Dictionary`2 acwMap, IEnumerable`1 additionalDirectories, Action`2 logMessage, Action`2 registerCustomView)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(ITaskItem item, Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	OBDNowProto	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Aapt2.targets	121

**Comment by gmck** [comment]
That did come out well.

`<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

**Comment by gmck** [comment]
Accidently closed

**Comment by jonathanpeppers** [comment]
@gmck can you share a sample project hitting this? Or a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!

Looking at the error offhand, this change that just landed in master would fix it...

https://github.com/xamarin/xamarin-android/pull/4395

But I think I want to understand how you are hitting this. Is it only happening while using the designer?

**Comment by gmck** [comment]
@jonathanpeppers  This was over a month ago, so trying to reproduce it now is pretty much impossible.  At the time it was happening just about every time I tried to build/deploy.  Since then I've moved on through a couple of previews (now on 16.6.0 - 1.0 and it now doesn't happen as often. It happened just changing stuff in the designer or even just editing a style, basically anything xml. 

Re your question re the designer. For this particular project, every single layout is screwed in the designer as reported in #4317. No change when I swapped to 16.6.0 - 1.0. Just watched the video between Jeremie and James about the designer. Would be nice if my designer worked that way.

There has to be something basically wrong with it when Device, Version and Theme combos don't work. Actually just noticed that the Themes combo is now working in 16.6.0 - 1.0, but the other two look to be disabled or just not populating. I've got no idea what is causing that, so I just do my layouts in AS and import them.

**Comment by jonathanpeppers** [comment]
> I just do my layouts in AS and import them

@gmck so I don't follow what your workflow is exactly, but does Android Studio have the same file open as Visual Studio?

Otherwise, it might be an issue fixed in the designer in 16.5 P3/P4/GA. It used to run the MSBuild targets in parallel and you could get file locking issues like this.

@garuma do you know when that fix shipped?

**Comment by gmck** [comment]
@jonathanpeppers  I've always used the AS designer doing any new layout just because it is way better than the Xamarin one. When I'm done with the layout I used to just create a new file (axml) in VS and then just copy/paste into that. When VS swapped to xml for layouts, it became even easier. I just use "add existing item" and bring it in from the AS folder where ever that is. So they are two separate files, so I don't see how there is any conflict even if AS is still open, which it normally is.

In this particular test project, some of the layouts were added from my existing production version of the app and some new ones were added from AS, so that doesn't explain why the designer totally fails for each layout with the System.Collections.Generic.KeyNotFoundException.
