### ISSUE TITLE
16.5.0 Preview 2.0 Android Designer problem

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4317]
I have one project that will not open any layout file in the designer, without the designer giving the following error below.  The device, version and theme dropdowns are also all disabled. The common denominator is that all the layouts have been imported or copy/pasted from Android Studio.

They all compile fine and the app builds and runs fine.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Roslyn.Utilities.ObjectWriter.WriteKnownType(Type type) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\Serialization\StreamObjectWriter.cs:line 281
   at Roslyn.Utilities.ObjectWriter.WriteObjectHeader(Object instance, UInt32 memberCount) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\Serialization\StreamObjectWriter.cs:line 345
   at Roslyn.Utilities.ObjectWriter.WriteObjectInternal(IObjectWritable instance) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\Serialization\StreamObjectWriter.cs:line 325
   at Xamarin.AndroidDesigner.Resources.Ast.ResourceRepositorySerializer.SerializeResourcesForJava(IEnumerable`1 resources, Int32 originalCount, Stream stream, IEnumerable`1 qualifiersToMatch) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\ResourceRepositorySerializer.cs:line 177
   at Xamarin.AndroidDesigner.Resources.Ast.ResourceRepository.SerializeForJavaTo(Stream stream, IEnumerable`1 toMatch) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\ResourceRepository.cs:line 349
   at Xamarin.AndroidDesigner.Resources.Ast.ResourceProvisionator.SerializeRepositoryToFilePath(ResourceRepository repository, String path, IEnumerable`1 qualifiers) in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\ResourceProvisionator.cs:line 101
   at Xamarin.AndroidDesigner.Resources.Ast.ResourceProvisionator.<>c__DisplayClass5_1.<CreateSerializationTasks>b__0() in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\ResourceProvisionator.cs:line 78
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidDesigner.Resources.Ast.ResourceProvisionator.<ProvisionResources>d__4.MoveNext() in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Resources.Ast\ResourceProvisionator.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidDesigner.ResourceProvisionatorExtensions.<ProvisionResources>d__0.MoveNext() in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\ResourceProvisionatorExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidDesigner.AndroidRenderSession.<InitSession>d__115.MoveNext() in E:\A\_work\283\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\AndroidRenderSession.cs:line 782
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by gugavaro** [comment]
@garuma who should I assign designer issues?

**Comment by garuma** [comment]
@gugavaro I'm a good proxy, thanks!

**Comment by gmck** [comment]
@garuma  @gugavaro. I was wondering if you got the test project I uploaded which demonstrates this problem with the designer. It was copied to @jonathanpeppers and @grendello awhile back. I can send it again. if required. Since I sent it, I've added several layouts to the project and every one of them gives this error. Makes no difference to the build as it runs fine, but it be much better if the designer didn't give the error. Most of the layouts come in as layouts that were for the support libs and then are converted to their androidx equivalents. The device and version combos of the designer are also disabled.

**Comment by dellis1972** [comment]
@BretJohnson do you know who is leading the Designer effort these days? Are you able to re-route this to and appropriate person?
