### ISSUE TITLE
net5 & Delegate.CreateDelegate() changes

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#4394]
Context: https://github.com/dotnet/runtime/issues/33531
Context: https://github.com/mono/mono/issues/19207
Context: https://github.com/xamarin/xamarin-android/commits/test-net5-drop

### Steps to Reproduce

1. Bribe @pjcollins to get a xamarin-android build environment which uses a (very) preview .NET 5 runtime & mono package.
2. Run a Xamarin.Forms app, e.g. our integration test, or from a default template.

### Expected Behavior

It works!

### Actual Behavior

It fails:

```
UNHANDLED EXCEPTION:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true. (Parameter 'target')
   at System.Delegate.CreateDelegate(Type type, Type target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Type target, String method)
   at Android.Runtime.AndroidTypeManager.RegisterNativeMembers(JniType nativeClass, Type type, String methods)
   at Android.Runtime.JNIEnv.RegisterJniNatives(IntPtr typeName_ptr, Int32 typeName_len, IntPtr jniClass, IntPtr methods_ptr, Int32 methods_len)
   at Java.Interop.JniEnvironment.Object.AllocObject(JniObjectReference type)
   at Java.Interop.JniType.AllocObject()
   at Java.Interop.JniPeerMembers.JniInstanceMethods.StartCreateInstance(String constructorSignature, Type declaringType, JniArgumentValue* parameters)
   at Xamarin.Forms.Platform.Android.FormsViewGroup..ctor(Context p0)
   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(Context context)
   at Xamarin.Forms.Platform.Android.PageRenderer..ctor(Context context)
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate(Type type, Object source, Type visualType, Object[] args)
   at Xamarin.Forms.Internals.Registrar`1[[Xamarin.Forms.IRegisterable, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].GetHandler(Type type, Object source, IVisual visual, Object[] args)
   at Xamarin.Forms.Internals.Registrar`1[[Xamarin.Forms.IRegisterable, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].GetHandlerForObject[IVisualElementRenderer](Object obj, Object[] args)
   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)
   at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild(Page page, Boolean layout)
   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal(Page newRoot)
   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage(Page newRoot)
   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage(Page page)
   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage()
   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication(Application application)
   at formstest.Droid.MainActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
```

### Discussion

The .NET 5 drop we're using shows behavior incompatibilities between mono -- which Xamarin.Android has been using for ~10+ years now -- and .NET Framework/.NET Core, in particular dotnet/runtime#33531 vs. mono/mono#19207.

What's happening is as follows:

 1. [`PageRenderer`](https://github.com/xamarin/Xamarin.Forms/blob/7a52542d50797ccc69ae1d8dd84259190d96bdb4/Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs) inherits from `VisualElementRenderer<Page>`.
 2. [`VisualElementRenderer<T>`](https://github.com/xamarin/Xamarin.Forms/blob/1532d46f5fb6f219594015b80f8e5a2476512882/Xamarin.Forms.Platform.Android/VisualElementRenderer.cs) is (1) generic, and (2) inherits the (non-generic) `FormsViewGroup`.
 3. At packaging time, Java Callable Wrappers for these types is generated, akin to:

    ```java
    package crc643f46942d9dd1fff9;

    public abstract class VisualElementRenderer_1 extends com.xamarin.forms.platform.android.FormsViewGroup implements mono.android.IGCUserPeer {
    	public static final String __md_methods;
    	static {
    		__md_methods = ...;
    		mono.android.Runtime.register ("Xamarin.Forms.Platform.Android.VisualElementRenderer`1, Xamarin.Forms.Platform.Android", VisualElementRenderer_1.class, __md_methods);
    	}
    }
    
    public class PageRenderer extends crc643f46942d9dd1fff9.VisualElementRenderer_1 implements mono.android.IGCUserPeer {
    	public static final String __md_methods;
    	static {
    		__md_methods = ...;
    		mono.android.Runtime.register ("Xamarin.Forms.Platform.Android.PageRenderer, Xamarin.Forms.Platform.Android", PageRenderer.class, __md_methods);
    	}
    }
    ```

 4. At runtime, "something" does `new PageRenderer()` from C#, which causes the `crc643f46942d9dd1fff9.PageRenderer` Java class to be instantiated.
 5. But before `crc643f46942d9dd1fff9.PageRenderer` can be instantiated, the  `crc643f46942d9dd1fff9.PageRenderer` class constructor must execute.
 6. But before the `crc643f46942d9dd1fff9.PageRenderer` class constructor must execute, the `crc643f46942d9dd1fff9.VisualElementRenderer_1` class constructor must execute (...).
 7. (6) causes a `Runtime.register()`/`JNIEnv.RegisterJniNatives()` invocation for the *generic type definition* for `VisualElementRenderer<T>`, which attempts to register native methods for `VisualElementRenderer<T>`.

(7) is how we get to `System.Delegate.CreateDelegate()`.

Simplifying, what (7) does is:

```csharp
using System;

class FormsViewGroup {
    public static void M () {
        Console.WriteLine ("Base.M");
    }
}

class VisualElementRenderer<T> : Base {
}

class App {
    public static void Main ()
    {
        var d = (Action) Delegate.CreateDelegate (typeof(Action), typeof(VisualElementRenderer<>), "M");
        d ();
    }
}
```

With mono, (7) works, *because* the "generic-ness" of the type is irrelevant, *so long as* the method that we're looking up *isn't **itself*** in a generic class, which isn't the case here.

With .NET 5, (7) *fails*, because the generic-ness of `VisualElementRenderer<T>` *does* matter.

### Solutions?

There are at least three separate solutions to this problem.

1. Fix the BCL
2. Fix `Android.Runtime.AndroidTypeManager.RegisterNativeMembers()`
3. Fix Java Callable Wrappers

#### Fix the BCL

https://github.com/dotnet/runtime/issues/33531

There's some push back on this, so it isn't necessarily a plausible answer.

#### Fix `Android.Runtime.AndroidTypeManager.RegisterNativeMembers()`

There are at least two plausible fixes that could be done within `AndroidTypeManager.RegisterNativeMembers()`

1. Bail and do nothing if the type is a generic type definition, or
2. If a type is a generic type definition, use it's *base* class instead.

#### Fix Java Callable Wrappers

Should there *be* a `Runtime.register()` invocation *at all* when the corresponding type is generic?  ¯\_(ツ)_/¯

**Comment by jonpryor** [comment]
My gut feeling is that (2)(b) is the appropriate fix: look for non-generic base types when registering methods.

**Comment by grendello** [comment]
Wouldn't 3. be the fastest fix, wrt runtime performance? We simply wouldn't generate the `Runtime.register` call for the open generic type but instead just for its base?

**Comment by jonpryor** [comment]
@grendello: While (3) would be "fastest" regarding runtime performance, I fear repercussions without additional testing, and I'm not entirely certain I can imagine all scenarios that it may break, or convince myself that there are no scenarios it could break.  (It's also the hardest to *integrate*, as Java Callable Wrappers are in a separate repo.)

I'm not saying it's bad, but I'm not *not* saying that either?

**Comment by jonpryor** [comment]
After thinking about it, 2(a) and (3) are not viable solutions, not with how we currently do Java `native` method registration.

Consider:

```csharp
// C#
class FooHolder<T> : Java.Lang.Object, ISomeJavaInterface {
    public void SomeJavaMethod () {…}
}
```

would result in the Java Callable Wrapper:

```java
// Java
public class FooHolder_1 extends Object implements SomeJavaInterface {
    static { Runtime.register (…); }
    public void someJavaMethod() { n_someJavaMethod (); }
    native void n_someJavaMethod();
}
```

In this scenario, in order to do `new FooHolder<int>()` and have *Java* invoke methods on the `FooHolder_1` instance — via the `SomeJavaInterface` interface — the native method `FooHolder_1.n_someJavaMethod()` method *must* be registered, and the only way to do that is if we actually register the generic type definition for `FooHolder<T>`.

2(a) and (3) avoid/remove the `Runtime.register()` invocation, and thus would break this scenario.

The only viable answer is 2(b), as done in PR #4398.

**Comment by grendello** [comment]
@jonp with `FooHolder<int>` we wouldn't see the problem. The restriction is valid for open generic types only. So maybe we could make JCW generator avoid registering only the abstract generic types (which is what happened in this case)?

**Comment by jonpryor** [comment]
@grendello: we absolutely would see a problem with `FooHolder<int>`, because the *Java side* of `FooHolder<int>` is `FooHolder_1`, of which There Is Only One, and `FooHolder_1`'s static initializer calls `Runtime.register()` for the generic type definition, because that's all it *can* register.

If we don't register the native methods on `FooHolder_1`, things will break.

> So maybe we could make JCW generator avoid registering only the abstract generic types (which is what happened in this case)?

Would not help the `FooHolder<T>` example which implements a Java interface.  The interface methods need to be declared in the Java Callable Wrapper and registered within `Runtime.register()`.
