### ISSUE TITLE
[Bug] Errors After AndroidX Update

### ISSUE THREAD

**Issue by developersimsek** [xamarin/xamarin-android#4856]
### Description
Hi,
I had to update the project to AndroidX because a nougat AndroidX packages wanted my app installed on Google Play. The project is not debugged after the update. Can you please help urgently to solve the error?

### Steps to Reproduce

1. The Xamarin.Forms package has been upgraded to the latest version.
2. The project was migrated to AndroidX with Migrate To AndroidX option.
3. Latest versions of all libraries in the application, including AndroidX libraries, have been installed.
4. Bin / obj and nuget folders have been cleared.

### Expected Behavior

Debugging the project without errors

### Actual Behavior

- Exception in thread "main" java.lang.IllegalArgumentException
- at java.util.concurrent.ThreadPoolExecutor.(ThreadPoolExecutor.java:1314)
- at java.util.concurrent.ThreadPoolExecutor.(ThreadPoolExecutor.java:1202)
- at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
- at com.xamarin.androidx.jetifierWrapper.Main.executeJetifier(Main.java:222)
- at com.xamarin.androidx.jetifierWrapper.Main.main(Main.java:142)

### Basic Information

Xamarin Forms: 4.7.0.968

Microsoft Visual Studio Enterprise 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

ASP.NET and Web Tools 2019 16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services 16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019 16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0 16.6.948.25768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools 16.6.948.25768
Azure Functions and Web Jobs Tools

C# Tools 3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DevExpress Reporting Extension 1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress Reporting Tools Extension 1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool 1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension 1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus 1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitLab Extension for Visual Studio 1.0.189
A Visual Studio Extension that brings the GitLab Flow into Visual Studio.

IntelliCode Extension 1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools 2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio 0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager 2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers 1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio 16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager 5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension 1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools 16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools 16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7 16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview) 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog 1.0
Information about my package

VisualStudio.Foo 1.0
Information about my package

VisualStudio.Mac 1.0
Mac Extension for Visual Studio

VisualSVN 7.2.0
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2019 VisualSVN Software Ltd. All rights reserved.

Xamarin 16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
Mono: 165f4b0
Java.Interop: xamarin/java.interop@2cab35c
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK 13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots
![ErrorList](https://user-images.githubusercontent.com/23637417/85385126-9a59b880-b54a-11ea-9b89-61919f76ee80.PNG)

### Reproduction Link

[Output.txt](https://github.com/xamarin/Xamarin.Forms/files/4818370/Output.txt)

**Comment by mattleibow** [comment]
I see this in the log:

```
NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
 Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.GooglePlayServices.Ads.Identifier 71.1600.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
 Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
 Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Firebase.Messaging 71.1740.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
 Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
```

It looks like somewhere there is a really old Android Support package. Make sure you are on 28.0.0.3+

**Comment by developersimsek** [comment]
> Bunu günlükte görüyorum:
> 
> ```
> NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
>  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.GooglePlayServices.Ads.Identifier 71.1600.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
>  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
> NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
>  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Firebase.Messaging 71.1740.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
>  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
> ```
> 
> Gerçekten eski bir Android Destek paketi olan bir yere benziyor. 28.0.0.3+ sürümünde olduğunuzdan emin olun

Thanks for the answer. Which package will I update? So no update appears in any package. All packages are in the latest version. Will I downgrade the package?

**Comment by developersimsek** [comment]
> > Bunu günlükte görüyorum:
> > ```
> > NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
> >  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.GooglePlayServices.Ads.Identifier 71.1600.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
> >  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
> > NU1605: Detected package downgrade: Xamarin.Android.Support.v4 from 28.0.0.1 to 26.0.2. Reference the package directly from the project to select a different version. 
> >  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Firebase.Messaging 71.1740.0 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 (>= 28.0.0.1) 
> >  Uyumsoft.Android -> Com.OneSignal 3.9.0 -> Xamarin.Android.Support.v4 (>= 26.0.2)
> > ```
> > 
> > 
> > Gerçekten eski bir Android Destek paketi olan bir yere benziyor. 28.0.0.3+ içerinde başlamakdan emin olun
> 
> Cevap için teşekkürler. Hangi paketi güncelleyeceğim? Dolayısıyla hiçbir pakette güncelleme görünmüyor. Tüm paketler en son sürümdedir. Paketi eski sürüme geçirecek miyim?

Also; I created zero projects and added the project. The output document belongs to the original project. Therefore, it may not be complete. Could you please base the project in MaliTakvim.zip?
Thank you,
good work...

**Comment by mattleibow** [comment]
Maybe try the latest version of `Xamarin.GooglePlayServices.Basement` and even the latest `Xamarin.Firebase.Messaging` and Xamarin.GooglePlayServices.Ads.Identifier`

This is because the `Com.OneSignal` project is based on an older support, but also newer.

**Comment by developersimsek** [comment]
> Maybe try the latest version of `Xamarin.GooglePlayServices.Basement` and even the latest `Xamarin.Firebase.Messaging` and Xamarin.GooglePlayServices.Ads.Identifier`
> 
> This is because the `Com.OneSignal` project is based on an older support, but also newer.

This error is received when the newly created / zero project is updated to AndroidX. So I don't think it has anything to do with packages. Would you please check the zero project? The packages in your reply are not in this project, but the same error is received. https://github.com/xamarin/xamarin.forms/files/4818575/malitakvim.zip
Thank you,
Good work...

**Comment by developersimsek** [comment]
> > Belki de en yeni sürümünü `Xamarin.GooglePlayServices.Basement`ve hatta en yeni sürümünü `Xamarin.Firebase.Messaging`ve Xamarin'i deneyin.GooglePlayServices.Ads.Identifier`
> > Bunun nedeni, `Com.OneSignal`projenin daha eski bir desteğe, aynı zamanda daha yeni bir desteğe dayandırılmış olmasıdır.
> 
> Bu hata, yeni oluşturulan / sıfır projesi AndroidX olarak güncellendiğinde alınır. Bu yüzden paketlerle ilgisi olduğunu düşünmüyorum. Lütfen sıfır projesini kontrol eder misiniz? Yanıtınızdaki paketler bu projede değil, aynı hata alındı. https://github.com/xamarin/xamarin.forms/files/4818575/malitakvim.zip
> Teşekkür ederim,
> İyi çalışmalar ...

  
I had a chance to check the project @mattleibow

**Comment by mattleibow** [comment]
I opened a PR to update the NuGet, but updating the dependencies in your project will fix it:
https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/206

**Comment by developersimsek** [comment]
> [NuGet'i](https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/206) güncellemek için bir PR açtım, ancak projenizdeki bağımlılıkları güncellemek sorunu çözecektir:
> [OneSignal / OneSignal-Xamarin-SDK # 206](https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/206)


Thank you very much indeed. However, I could not understand what to do or what to update. Can you give details?

**Comment by mattleibow** [comment]
I just need to understand this issue a bit better...

I downloaded "MaliTakvim.zip" and ran that. It compiles and runs just fine for me. What error are you getting on that sample?
I will point out that the sample can already be AndroidX if you update the target versions to Android 10 or API 29. Xamarin.Forms is already using AndroidX, just only when you pick Android 10 as a compile target.

Your error that you originally posted is the migration process crashing because in the other app, you have too old support version. Either install the later version (which is most likely the fix) or upgrade them if they are already installed.

Install the latest stable versions of:
 - Xamarin.GooglePlayServices.Basement
 - Xamarin.Firebase.Messaging 
 - Xamarin.GooglePlayServices.Ads.Identifier

**Comment by developersimsek** [comment]
> * Xamarin.GooglePlayServices.Basement
> * Xamarin.Firebase.Messaging
> * Xamarin.GooglePlayServices.Ads.Identifier

Packages you have submitted;
- xamarin.googleplayservices.basement
- xamarin.firebase.messaging
- Xamarin.GooglePlayServices.Ads.Identifier 
was not installed in the project. I tried again by installing the latest stable versions. I also completely removed the previous OneSignal package. However, the error continues. I think the AndroidX transition is early. For this reason, removing the nuget that forces my transition to AndroidX and finding a different nuget suggests that I will find a solution in a shorter time.

Thank you,
Good work...

**Comment by brendanzagaeski** [comment]
Taking a fresh look at this, I believe that until the proposed changes to the OneSignal package from <https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/206> are available in a new version of the OneSignal NuGet package, the original _Uyumsoft.Android.csproj_ project should add all of those dependency NuGet packages explicitly.

So the `<ItemGroup>` that contains `<PackageReference>` elements in _Uyumsoft.Android.csproj_ would need to be edited to add the following lines:

```
<PackageReference Include="Xamarin.Android.Support.v4">
  <Version>28.0.0.3</Version>
</PackageReference>
<PackageReference Include="Xamarin.Android.Support.v7.CardView">
  <Version>28.0.0.3</Version>
</PackageReference>
<PackageReference Include="Xamarin.Android.Support.CustomTabs">
  <Version>28.0.0.3</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.Ads.Identifier">
  <Version>71.1600.0</Version>
</PackageReference>
<PackageReference Include="Xamarin.Firebase.Messaging">
  <Version>71.1740.0</Version>
</PackageReference>
```

One way to do this would be to use the NuGet package manager to explicitly install each of these package versions into _Uyumsoft.Android.csproj_. Antoher way would be to edit the _.csproj_ file [in Visual Studio](https://docs.microsoft.com/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#edit-project-files-in-visual-studio) or another text editor and add the lines by hand.

If this does not resolve the issue, then if you could attach a new build output that shows the remaining errors, that would be perfect. Thanks in advance!

**Comment by developersimsek** [comment]
> Buna yeni bir göz atarak, [OneSignal / OneSignal-Xamarin-SDK # 206'dan](https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/206) OneSignal paketinde önerilen değişiklikler, OneSignal NuGet paketinin yeni bir sürümünde mevcut olana kadar, orijinal _Uyumsoft.Android.csproj_ projesi eklenmelidir. tüm bu bağımlılık NuGet paketleri açıkça.
> 
> Yani `<ItemGroup>`içerdiğini `<PackageReference>`öğeleri _Uyumsoft.Android.csproj_ düzenlenebilir gerekir aşağıdaki satırları ekleyin:
> 
> ```
> <PackageReference Include="Xamarin.Android.Support.v4">
>   <Version>28.0.0.3</Version>
> </PackageReference>
> <PackageReference Include="Xamarin.Android.Support.v7.CardView">
>   <Version>28.0.0.3</Version>
> </PackageReference>
> <PackageReference Include="Xamarin.Android.Support.CustomTabs">
>   <Version>28.0.0.3</Version>
> </PackageReference>
> <PackageReference Include="Xamarin.GooglePlayServices.Ads.Identifier">
>   <Version>71.1600.0</Version>
> </PackageReference>
> <PackageReference Include="Xamarin.Firebase.Messaging">
>   <Version>71.1740.0</Version>
> </PackageReference>
> ```
> 
> Bunu yapmanın bir yolu, bu paket sürümlerinin her birini _Uyumsoft.Android.csproj'a_ açıkça yüklemek için _NuGet_ paket yöneticisini kullanmak olacaktır . Bunun yolu [, Visual Studio'da](https://docs.microsoft.com/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#edit-project-files-in-visual-studio) veya başka bir metin düzenleyicisinde _.csproj_ dosyasını düzenlemek ve satırları elle eklemek olacaktır.[](https://docs.microsoft.com/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#edit-project-files-in-visual-studio)
> 
> Bu sorunu çözmezse, kalan hataları gösteren yeni bir derleme çıktısı ekleyebilirseniz, bu mükemmel olur. Şimdiden teşekkürler!

Hi,
As you said, I made PackageReference additions to Uygsoft.Android.csproj document. However, the result has not changed. I share the compilation output. Thank you for your interest.
Good work...
[NewOutput.txt](https://github.com/xamarin/xamarin-android/files/4828426/NewOutput.txt)

**Comment by mattleibow** [comment]
I see a reference to `XamarinBuildDownloadRestoreAssemblyAar` in the log, so either you are not targeting Android 28/29 or you have an old version of the support packages installed. Could you attach the `obj/project.assets.json`?

**Comment by developersimsek** [comment]
> `XamarinBuildDownloadRestoreAssemblyAar`Günlükte bir referans görüyorum , bu nedenle Android 28/29'u hedeflemiyorsunuz veya destek paketlerinin eski bir sürümü yüklü. Takar mısınız `obj/project.assets.json`?

Tabiki. project.assets.json ektedir.

[project.assets.zip](https://github.com/xamarin/xamarin-android/files/4828529/project.assets.zip)

**Comment by mattleibow** [comment]
I am unable to reproduce this... I have attached a new project with all your packages in it. Does this build for you?
[App9.zip](https://github.com/xamarin/xamarin-android/files/4828788/App9.zip)

**Comment by developersimsek** [comment]
> I am unable to reproduce this... I have attached a new project with all your packages in it. Does this build for you?
> [App9.zip](https://github.com/xamarin/xamarin-android/files/4828788/App9.zip)

I'm sorry I didn't understand what to do. The same errors were received when I debug the project called App9 that you submitted. I have to understand that the project you submitted is compiled without errors?

**Comment by developersimsek** [comment]
> > I am unable to reproduce this... I have attached a new project with all your packages in it. Does this build for you?
> > [App9.zip](https://github.com/xamarin/xamarin-android/files/4828788/App9.zip)
> 
> The Uyumsoft PackageReference you added to the App9 project was giving a separate error because it was not found. (This way a package was not added anyway in the original project) When I delete and compile that PackageReference, I get the same error again. I add the build log for App9.
[App9Output.txt](https://github.com/xamarin/xamarin-android/files/4829925/App9Output.txt)

**Comment by Redth** [comment]
I'm also unable to produce this with the App9.zip attachment in Visual Studio 2019 16.6.2.  The project compiles, deploys, and runs fine.

**Comment by developersimsek** [comment]
> I'm also unable to produce this with the App9.zip attachment in Visual Studio 2019 16.6.2. The project compiles, deploys, and runs fine.


I think the problem seems to be from incompatible packages?

**Comment by mattleibow** [comment]
Did the "App9.zip" sample work for you? It worked for both of us.

**Comment by developersimsek** [comment]
> Did the "App9.zip" sample work for you? It worked for both of us.


No, I keep getting the same errors in App9 project. I added the compilation log, I add it again.
[App9Output.txt](https://github.com/xamarin/xamarin-android/files/4831897/App9Output.txt)

**Comment by mattleibow** [comment]
are you able to run this on the command line with a binary log?

```
msbuild /r /bl App9.sln
```

Just send over the msbuild.binlog and we can see exactly what is going on in your machine.

**Comment by developersimsek** [comment]
> are you able to run this on the command line with a binary log?
> 
> ```
> msbuild /r /bl App9.sln
> ```
> 
> Just send over the msbuild.binlog and we can see exactly what is going on in your machine.


Of course msbuild.binlog is attached.
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/4833533/msbuild.zip)

**Comment by mattleibow** [comment]
@developersimsek thanks for that binlog!

I managed to find out the issue! It is because Java seems to be having issues with the characters in your username "YunusŞimşek" which is most unfortunate.

You probably don't notice this in most cases because the general Android tooling is in the "C:\Program Files" path.

To fix this, I would suggest temporarily moving your NuGet cache by setting the `NUGET_PACKAGES` environment variable. And, just make sure that your source lives in a location that has no special characters.

We are looking into this to see if there is some fix we can do.

Thanks for reporting and sticking it out.
