### ISSUE TITLE
Unable to find application Mono.Android.Platform.ApiLevel_29!

### ISSUE THREAD

**Issue by dogukandemir** [xamarin/xamarin-android#4936]
While I’m trying to run app on Android 10 device, I’m getting error in the title. “Android SDK Platform 29” is installed when I check SDK manager. Also I check platforms folder in my sdk folder and android-29 folder is exists (not empty folder). In Visual Studio -> About Visual Studio -> Show Details, Supported Android Versions doesn’t list API level 29. When I disable “Use Shared Mono Runtime” option, I can run app.

![image](https://user-images.githubusercontent.com/5173991/87932028-1b916600-ca8b-11ea-95f3-a4638d7753dc.png)

### Steps to Reproduce
There is no specific steps to reproduce.

### Expected Behavior
No crash. Deploy app to phone and run it in debug mode.

### Actual Behavior
Crashing.

### Version Information
Device: Samsung Galaxy S20 5G (SM-G981U1)
Device Version: Android 10

Following version information is Visual Studio for Mac Preview but same behavior also happens on stable version.

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.7 Preview (8.7 build 1916)
Installation UUID: 1afb739a-a7a5-4f10-85a2-b0b80286793a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000082

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.82 (2020-02/109b4b6f445) (64-bit)
	Package version: 612000082

=== Xamarin Designer ===

Version: 16.7.0.486
Hash: d92fc32c1
Branch: remotes/origin/d16-7
Build date: 2020-06-24 00:37:00 UTC

=== Roslyn (Language Service) ===

3.7.0-4.20330.10+1f3fa3ff7330cf6d2631a230e42e93a85aa7d338

=== NuGet ===

Version: 5.7.0.6653

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.301/Sdks
SDK Versions:
	3.1.301
	3.1.300
	3.1.202
	3.1.200
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.5
	3.1.4
	3.1.2
	2.1.19
	2.1.18
	2.1.17

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.20.1.44 (Visual Studio Community)
Hash: 28cab0985
Branch: d16-7
Build date: 2020-07-07 15:04:11-0400

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/dogukandemir/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.3
SDK Build Tools Version: 30.0.1

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dogukandemir/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7
Build date: 2020-07-01 01:57:56 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-01 01:58:18 UTC

=== Xamarin.iOS ===

Version: 13.20.1.44 (Visual Studio Community)
Hash: 28cab0985
Branch: d16-7
Build date: 2020-07-07 15:04:12-0400

=== Build Information ===

Release ID: 807001916
Git revision: 09353f048fe630201eb8eabf01e88fbf918f6465
Build date: 2020-07-10 07:01:08-04
Build branch: release-8.7
Xamarin extensions: 09353f048fe630201eb8eabf01e88fbf918f6465

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
```

### Log File
You can find ide and more detailed logcat logs here: [https://gist.github.com/dogukandemir/7114613f33376e671f7718dbb37a3c6f](https://gist.github.com/dogukandemir/7114613f33376e671f7718dbb37a3c6f)

```
    --------- beginning of crash
2020-07-20 12:46:28.085 22386-22386/{AppPackageName} E/AndroidRuntime: FATAL EXCEPTION: main
    Process: {AppPackageName}, PID: 22386
    java.lang.RuntimeException: Unable to get provider mono.MonoRuntimeProvider: java.lang.RuntimeException: Unable to find application Mono.Android.Platform.ApiLevel_29!
        at android.app.ActivityThread.installProvider(ActivityThread.java:7618)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7158)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7021)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6989)
        at android.app.ActivityThread.access$1600(ActivityThread.java:272)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.RuntimeException: Unable to find application Mono.Android.Platform.ApiLevel_29!
        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:38)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7613)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7158) 
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7021) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6989) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:272) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8016) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
     Caused by: android.content.pm.PackageManager$NameNotFoundException: Mono.Android.Platform.ApiLevel_29
        at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:490)
        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:471)
        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7613) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7158) 
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7021) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6989) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:272) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8016) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
```

**Comment by dellis1972** [comment]
This is related to a change in the way android allows apps to use other packages. See https://github.com/xamarin/xamarin-android/pull/4846. #4846 will fix the issue and I think it is in the next Preview release.

**Comment by dogukandemir** [comment]
I've had a conversation about this with @jonathanpeppers before. He also mentioned #4846 and when I try it didn't help because #4846 is related with api level 30. not 29. Also if you check xamarin-android version information that I add, I'm using xamarin-android/d16-7 which includes #4846.

Could you please reopen this issue?

**Comment by dellis1972** [comment]
@dogukandemir I reopened. We are going to need the diagnostic build and deployment logs for this in order to investigate though. FYI the Mono.Android.Platform.ApiLevel_29 is referring to an apk which should be installed along side the shared runtime as part of the deployment process. For some reason that package is missing in your case.

**Comment by dogukandemir** [comment]
2 of my colleagues have same issue. As I've mentioned in issue, I have android-29 folder inside of android-sdk-macosx folder and it's not empty. Also when I try on another phone which is Samsung Galaxy Note 10 (SM-NF970F - Android 10), there is no problem.

Somehow api 29 is not being installed on phone in deployment process. If there is any other log that I can share to make investigation easier, please let me know.

**Comment by jonathanpeppers** [comment]
@dogukandemir if you have the right preview version, Xamarin.Android 11.x or higher.

Try deleting `C:\Users\jopepper\AppData\Local\Xamarin.Android\Cache\` or `~/Library/Caches/Xamarin.Android/` and try again?

If the old `.apk` files were signed with `jarsigner`, they won't work on an Android 10 device. The fix will sign them properly when you deploy again, but I think you will have to delete the old files.

**Comment by jonathanpeppers** [comment]
Attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) if it doesn't work.

**Comment by dogukandemir** [comment]
As you've suggested, removing files under `~/Library/Caches/Xamarin.Android/` helped. After I remove ApiLevel_28 and 29 apk and xml files, while I'm running on debug mode, new files has been created and now everything works fine without disabling `Use Shared Mono Runtime` option.

I don't know it's already doing or not but maybe while updating VS or xamarin-android, it can be deleted automatically to be sure it will not happen again.

Thanks for help @jonathanpeppers!

**Comment by jonathanpeppers** [comment]
@dogukandemir it depends on the timing if we add something to delete these files, we are getting close to removing the `Use Shared Mono Runtime` option entirely. It relies on graylisted Android APIs, so we have revamped things.
