### ISSUE TITLE
Exception is thrown in the Xamarin/Java http stack

### ISSUE THREAD

**Issue by alexander-papen** [xamarin/xamarin-android#5084]
### Steps to Reproduce

1. Use the MSAL (Microsoft.Identity.Client v4.14 or v4.15) component and call the method AqcuireTokenSilentAsync()
2. Wait for response, somtimes the exception is thrown, most times its ok

### Expected Behavior
The expected behavior is that the MSAL component will setup a webrequest to acquire a token, that token will be returned eventually by the AquireTokenSilent metod.

### Actual Behavior
Note, that in most cases the AcquireTokenSilent, does return a valid token.
However, an exception has been thrown a few times.
In production we currently use MSAL 4.14 and 4.15 in different versions of the same application.
In both versions the exception has been thrown. Because the callstack in the exception is not identical, for both MSAL versions the logging is added.

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.954.58314
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.6.954.58314
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

Note that there is no logging available from logcat.

Logging for application with MSAL 4.14:

```
2020-07-29 07:15:50.2516 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50] Deserialized 1 items to token cache.
2020-07-29 07:15:50.2543 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] MSAL MSAL.Xamarin.Android with assembly version '4.14.0.0'. CorrelationId(887cd467-2770-456c-8b5f-f9165181c03c)
2020-07-29 07:15:50.2579 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] === AcquireTokenSilent Parameters ===
2020-07-29 07:15:50.2595 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] LoginHint provided: False
2020-07-29 07:15:50.2610 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Account provided: True
2020-07-29 07:15:50.2624 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] ForceRefresh: False
2020-07-29 07:15:50.2648 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] 
=== Request Data ===
Authority Provided? - True
Scopes - api://<*removed*>/.default offline_access
Extra Query Params Keys (space separated) - 

2020-07-29 07:15:50.2664 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
2020-07-29 07:15:50.2682 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Looking up access token in the cache.
2020-07-29 07:15:50.2712 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Filtering by tenant id item count before 1 after 1
2020-07-29 07:15:50.2729 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Filtering by home account id item count before 1 after 1
2020-07-29 07:15:50.2743 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Filtering by token type item count before 1 after 1
2020-07-29 07:15:50.2757 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Matching entry count - 1
2020-07-29 07:15:50.2774 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Filtering by scopes item count before 1 after 1
2020-07-29 07:15:50.2794 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Access token has expired or about to expire. [Current time (07/29/2020 05:15:50) - Expiration Time (07/29/2020 05:18:37 +00:00) - Extended Expiration Time (07/29/2020 05:18:37 +00:00)]
2020-07-29 07:15:50.2825 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Refresh token found in the cache? - True
2020-07-29 07:15:50.2850 Info  3459 MSAL Info False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:15:50 - 887cd467-2770-456c-8b5f-f9165181c03c] Resolving authority endpoints... Already resolved? - TRUE
2020-07-29 07:20:39.6565 Error 3461 MSAL Error False (False) MSAL 4.14.0.0 MSAL.Xamarin.Android 19 [07/29/2020 05:20:39 - 887cd467-2770-456c-8b5f-f9165181c03c] Exception type: Java.IO.IOException

  at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <2cf3b6713d4f47bab26b2a9fc4e5375e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <2cf3b6713d4f47bab26b2a9fc4e5375e>:0 
  at Java.Net.HttpURLConnection.get_ResponseCode () [0x0000a] in <f10b261e224f49ae8dc5cbf2e7f62818>:0 
  at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass46_0.<DoProcessRequest>b__2 () [0x00000] in <f10b261e224f49ae8dc5cbf2e7f62818>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <7675e239ab70496f89f07b8d043c0155>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <7675e239ab70496f89f07b8d043c0155>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x0036c] in <f10b261e224f49ae8dc5cbf2e7f62818>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002c7] in <f10b261e224f49ae8dc5cbf2e7f62818>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <74304af6b1b549478867083afed9e28a>:0 
  at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method) [0x000c5] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Boolean doNotThrow, System.Boolean retry) [0x0013b] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, Microsoft.Identity.Client.Core.ICoreLogger logger) [0x0008b] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Collections.Generic.IDictionary`2[TKey,TValue] bodyParameters, Microsoft.Identity.Client.Core.ICoreLogger logger) [0x00099] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T] (System.Uri endPoint, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Core.RequestContext requestContext, System.Boolean expectErrorsOn200OK, System.Boolean addCommonHeaders) [0x0015e] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync (System.Uri endPoint, Microsoft.Identity.Client.Core.RequestContext requestContext, System.Boolean addCommonHeaders) [0x00084] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync (System.String tokenEndpoint) [0x000c8] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.String scopeOverride, System.String tokenEndpointOverride, System.Threading.CancellationToken cancellationToken) [0x000fc] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync (System.String tokenEndpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.Threading.CancellationToken cancellationToken) [0x000a3] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.RefreshAccessTokenAsync (Microsoft.Identity.Client.Cache.Items.MsalRefreshTokenCacheItem msalRefreshTokenItem, System.Threading.CancellationToken cancellationToken) [0x00112] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.RefreshRtOrFailAsync (System.Threading.CancellationToken cancellationToken) [0x0016c] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x00329] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0016e] in <62c5f81aa08b40f6a5628154f09a4f0a>:0 
  --- End of managed Java.IO.IOException stack trace ---
java.io.EOFException
	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318)
	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
	at dalvik.system.NativeStart.run(Native Method)
```

Logging for application with MSAL 4.15:

```
2020-08-07 22:36:19.5706 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19] Deserialized 1 items to token cache.
2020-08-07 22:36:19.5766 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] MSAL MSAL.Xamarin.Android with assembly version '4.15.0.0'. CorrelationId(1358eb5c-732b-4d62-823c-ffa2f4bf4c18)
2020-08-07 22:36:19.5790 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] === AcquireTokenSilent Parameters ===
2020-08-07 22:36:19.5805 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] LoginHint provided: False
2020-08-07 22:36:19.5819 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Account provided: True
2020-08-07 22:36:19.5833 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] ForceRefresh: False
2020-08-07 22:36:19.5856 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] 
=== Request Data ===
Authority Provided? - True
Scopes - api://<*removed*>/.default offline_access
Extra Query Params Keys (space separated) - 

2020-08-07 22:36:19.5872 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
2020-08-07 22:36:19.5888 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Attempting to acquire token using using local cache...
2020-08-07 22:36:19.5906 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Looking up access token in the cache.
2020-08-07 22:36:19.5936 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Filtering by tenant id item count before 1 after 1
2020-08-07 22:36:19.5952 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Filtering by home account id item count before 1 after 1
2020-08-07 22:36:19.5968 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Filtering by token type item count before 1 after 1
2020-08-07 22:36:19.5983 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Matching entry count - 1
2020-08-07 22:36:19.6000 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Filtering by scopes item count before 1 after 1
2020-08-07 22:36:19.6019 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Access token has expired or about to expire. [Current time (08/07/2020 20:36:19) - Expiration Time (08/07/2020 20:36:07 +00:00) - Extended Expiration Time (08/07/2020 20:36:07 +00:00)]
2020-08-07 22:36:19.6049 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Refresh token found in the cache? - True
2020-08-07 22:36:19.6073 Info  427  MSAL Info False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:36:19 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Resolving authority endpoints... Already resolved? - TRUE
2020-08-07 22:36:28.3850 Info  379  PushService.ConnectionOnStateChanged() from Connected to Disconnected.
2020-08-07 22:36:28.3867 Info  379  Account.EnsureValidTokenSilentAsync(): initiate SilentTokenRequest >>
2020-08-07 22:36:28.3879 Info  379  Account.LoginSilentAsync(RoleCount 0): initiate SilentTokenRequest
2020-08-07 22:36:28.3890 Info  379  Account.LoginServiceBase.Execute()
2020-08-07 22:37:59.5422 Error 379  MSAL Error False (False) MSAL 4.15.0.0 MSAL.Xamarin.Android 19 [08/07/2020 20:37:59 - 1358eb5c-732b-4d62-823c-ffa2f4bf4c18] Exception type: Java.IO.IOException

  at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <e12090061e9543f78670b707342f74aa>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <e12090061e9543f78670b707342f74aa>:0 
  at Java.Net.HttpURLConnection.get_ResponseCode () [0x0000a] in <6546ee6e35934592aba6a8abe6a8ea31>:0 
  at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass46_0.<DoProcessRequest>b__2 () [0x00000] in <6546ee6e35934592aba6a8abe6a8ea31>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <9d6fd9f223064a5a82eb5faaf0c2a30c>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <9d6fd9f223064a5a82eb5faaf0c2a30c>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x0036c] in <6546ee6e35934592aba6a8abe6a8ea31>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002c7] in <6546ee6e35934592aba6a8abe6a8ea31>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <27e9d596031b4c3191ebf40dda35a22d>:0 
  at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method) [0x000c5] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Core.ICoreLogger logger, System.Boolean doNotThrow, System.Boolean retry) [0x0013b] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Net.Http.HttpContent body, Microsoft.Identity.Client.Core.ICoreLogger logger) [0x0008b] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync (System.Uri endpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] headers, System.Collections.Generic.IDictionary`2[TKey,TValue] bodyParameters, Microsoft.Identity.Client.Core.ICoreLogger logger) [0x00099] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T] (System.Uri endPoint, System.Net.Http.HttpMethod method, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean expectErrorsOn200OK, System.Boolean addCommonHeaders) [0x0011c] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync (System.Uri endPoint, Microsoft.Identity.Client.Internal.RequestContext requestContext, System.Boolean addCommonHeaders) [0x00084] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync (System.String tokenEndpoint) [0x000c8] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.String scopeOverride, System.String tokenEndpointOverride, System.Threading.CancellationToken cancellationToken) [0x000fc] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync (System.String tokenEndpoint, System.Collections.Generic.IDictionary`2[TKey,TValue] additionalBodyParameters, System.Threading.CancellationToken cancellationToken) [0x000a3] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.RefreshAccessTokenAsync (Microsoft.Identity.Client.Cache.Items.MsalRefreshTokenCacheItem msalRefreshTokenItem, System.Threading.CancellationToken cancellationToken) [0x0011c] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.RefreshRtOrFailAsync (System.Threading.CancellationToken cancellationToken) [0x0016c] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x0023b] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x0009b] in <5379e12126bf461d83f6959d6b241d45>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0016e] in <5379e12126bf461d83f6959d6b241d45>:0 
  --- End of managed Java.IO.IOException stack trace ---
java.io.EOFException
	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318)
	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
	at dalvik.system.NativeStart.run(Native Method)

```

**Comment by alexander-papen** [comment]
Please note that initial I addressed this issue at the MSAL team:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2007
