### ISSUE TITLE
Xamarin app crashes in release mode

### ISSUE THREAD

**Issue by akhterm** [xamarin/xamarin-android#5483]
In Debug version, application is working good but after changing it to release mode, app starts to crashes. 

Please find the attached AndroidManifest.xml, Android Options, logs and version.
In this regards, please advise how to fix this issue. 

![AndroidOption_1](https://user-images.githubusercontent.com/48507683/104090672-c42dbf00-5291-11eb-9a84-7194f876f897.png)
![AndroidOption_2](https://user-images.githubusercontent.com/48507683/104090675-c5f78280-5291-11eb-91ee-616759edeb51.png)
[IssueLogs.txt](https://github.com/xamarin/xamarin-android/files/5790781/IssueLogs.txt)
[VersionDetails.txt](https://github.com/xamarin/xamarin-android/files/5790783/VersionDetails.txt)

**Comment by pjcollins** [comment]
Looking at the logs I am not seeing anything that immediately stands out. There's some information about a couple of exceptions related to hot reload but these don't appear to be fatal. Would you be able to attach a project which reproduces the issue you're encountering?

Does this issue only occur when switching from Debug to Release mode? Please try the following steps to capture more device log information:

1) Open the "Tools" -> "Android" -> "Device Log" window.
2) At the top of the "Device Log" window, select the device you are deploying to from the dropdown menu and then click the "Clear All" button.
3) Click "Debug" -> "Start Without Debugging"
4) After the application crashes click on the "Device Log" window and press 'ctrl+a' and 'ctrl+c' to copy the device log content.
5) Paste this log information into a file and upload it here.

**Comment by akhterm** [comment]
Dear,
Please find the device logs attached here with.
Will try to create a sample application with same issue. Kindly check device logs and if anything then kindly advise



[DeviceLogs.txt](https://github.com/xamarin/xamarin-android/files/5797583/DeviceLogs.txt)

**Comment by pjcollins** [comment]
This _looks_ to be the relevant crash information:
```
01-11 22:16:50.320	Samsung SM-G975F	Info	20011	MonoDroid	android.runtime.JavaProxyThrowable: Xamarin.Forms.Xaml.XamlParseException: Position 14:17. Can't resolve TextWrappingProperty on Label
  at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.SetPropertyValue (System.Object xamlelement, Xamarin.Forms.Xaml.XmlName propertyName, System.Object value, System.Object rootElement, Xamarin.Forms.Xaml.INode node, Xamarin.Forms.Xaml.HydrationContext context, System.Xml.IXmlLineInfo lineInfo) [0x0013b] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit (Xamarin.Forms.Xaml.ValueNode node, Xamarin.Forms.Xaml.INode parentNode) [0x00090] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ValueNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00000] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00044] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00079] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.FillResourceDictionariesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x000f9] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00012] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00079] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.XamlLoader.Visit (Xamarin.Forms.Xaml.RootNode rootnode, Xamarin.Forms.Xaml.HydrationContext visitorContext, System.Boolean useDesignProperties) [0x00085] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml, System.Reflection.Assembly rootAssembly, System.Boolean useDesignProperties) [0x000eb] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml, System.Reflection.Assembly rootAssembly) [0x00000] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.String xaml, System.Reflection.Assembly rootAssembly) [0x00000] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.Xaml.ResourcesLoader.CreateFromResource[T] (System.String resourcePath, System.Reflection.Assembly assembly, System.Xml.IXmlLineInfo lineInfo) [0x000b9] in <0a1dd947c7b74f34b9ecd601095d04b6>:0 
  at Xamarin.Forms.ResourceDictionary.SetAndLoadSource (System.Uri value, System.String resourcePath, System.Reflection.Assembly assembly, System.Xml.IXmlLineInfo lineInfo) [0x0006a] in <9fe9b646a92b40c98637ddaab40bf818>:0 
  at DmsMobileClient.Portable.App.InitializeComponent () [0x002e2] in <a86dc1ab3f4a4c63a8635f3b670004e9>:0 
  at DmsMobileClient.Portable.App..ctor () [0x00008] in <a86dc1ab3f4a4c63a8635f3b670004e9>:0 
  at DmsMobileClient.Android.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001c] in <2815f8ecceb94bba845c20f544e1a249>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <a54fd02a94254b8f91efc9ea3cec736c>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
	at crc64a143f65770e37e3e.MainActivity.n_onCreate(Native Method)
	at crc64a143f65770e37e3e.MainActivity.onCreate(MainActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
01-11 22:16:50.320	Samsung SM-G975F	Info	20011	MonoDroid	Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
```

If this only happens during Release mode I wonder if it may have to do with some Release specific settings. If you change the Android Options -> Linking option to None does the error still occur?

**Comment by akhterm** [comment]
Dear, 
After doing following changes, still have same error 
Android Options -> Linking option to None
Please find the sample app attached here with, having same issue is attached app as well. 
Please advise 

[TakeOffApp.zip](https://github.com/xamarin/xamarin-android/files/5798146/TakeOffApp.zip)

**Comment by akhterm** [comment]
Dear,
Waiting for your response. 

Regards,

**Comment by kvpt** [comment]
@akhterm What is strange in your app is that your style H1TextStyle in the file 001DefaultStyle.xaml mention TextWrapping and TextTrimming properties.
From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.label?view=xamarin-forms), those doesn't exist, so the error seems correct.
Why the issue only occur in release, I don't know.

**Comment by pjcollins** [comment]
Thanks for the feedback @kvpt. The error you're seeing during a Release deployment is valid, as the properties you're referencing aren't available. I was able to get the app to run by modifying the relevant `Style` block to only include the following:

```xaml
    <Style x:Key="H1TextStyle" TargetType="{x:Type Label}">
        <Setter Property="FontFamily" Value="{DynamicResource FontFamily}"/>
        <Setter Property="FontSize" Value="{DynamicResource H1FontSize}"/>
        <Setter Property="VerticalTextAlignment" Value="Center"/>
    </Style>
```

As to why this is doesn't manifest in Debug mode, this appears to only affect the IDE deployment path. Attempting to install and run this app in Debug mode from command line does result in the same exception mentioned above. @joj is this something you can help track down? Here's a more simple repro:

[TestInvalidRes.zip](https://github.com/xamarin/xamarin-android/files/5844903/TestInvalidRes.zip)

**Comment by akhterm** [comment]
> @akhterm What is strange in your app is that your style H1TextStyle in the file 001DefaultStyle.xaml mention TextWrapping and TextTrimming properties.
> From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.label?view=xamarin-forms), those doesn't exist, so the error seems correct.
> Why the issue only occur in release, I don't know.

Thanks for pointing out the issue. 
Really appreciate your support.

**Comment by smhasan** [comment]
> Looking at the logs I am not seeing anything that immediately stands out. There's some information about a couple of exceptions related to hot reload but these don't appear to be fatal. Would you be able to attach a project which reproduces the issue you're encountering?
> 
> Does this issue only occur when switching from Debug to Release mode? Please try the following steps to capture more device log information:
> 
> 1. Open the "Tools" -> "Android" -> "Device Log" window.
> 2. At the top of the "Device Log" window, select the device you are deploying to from the dropdown menu and then click the "Clear All" button.
> 3. Click "Debug" -> "Start Without Debugging"
> 4. After the application crashes click on the "Device Log" window and press 'ctrl+a' and 'ctrl+c' to copy the device log content.
> 5. Paste this log information into a file and upload it here.

@pjcollins Dear Thanks for your suggestion, I was facing the same said issue by @akhterm, in my case it the issue was getting file version from assembly, which was not an error in Debug mode, but was killing my app in Release mode, I figure out the issue from these line and fixed
at eVStore.ViewModels.LoginPageViewModel..ctor () [0x00013] in <7e67d7c8606e4e60ab0923477a682501>:0 
  at eVStore.Views.LoginPage..ctor () [0x0000c] in <7e67d7c8606e4e60ab0923477a682501>:0 
in ViewModel the issue was in below code 
App_Version = "Version " + FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion;

Thanks to all, I fixed my issue now app is working fine

**Comment by akhterm** [comment]
Closing the issue
