### ISSUE TITLE
Custom BroadcastReceiver for ActionBootCompleted (BootReceiver) Crash - System.TypeLoadException 

### ISSUE THREAD

**Issue by todorspetkov** [xamarin/xamarin-android#5614]
### Steps to Reproduce

1. I have an ActionBootCompleted broadcast receiver that has to perform some operations when the user's phone is rebooted. The xamarin android code is as follows (JunkerBootReceiver.cs):
        
```
        [BroadcastReceiver(Enabled = true)]
        [IntentFilter(new []{ Intent.ActionBootCompleted })]
        public class JunkerBootReceiver : BroadcastReceiver
        {
                public override void OnReceive (Context context , Intent intent)
                {
                        // device rebooted - do your stuff here 
                }
       }           
```

2. In firebase crashlytics I observe the following exception on some devices (62% on Android 10 devices):

```
Fatal Exception: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type 'Junker.Droid.Services.JunkerBootReceiver' from assembly 'Junker.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at (wrapper managed-to-native) System.RuntimeTypeHandle.internal_from_name(string,System.Threading.StackCrawlMark&,System.Reflection.Assembly,bool,bool,bool)
  at System.RuntimeTypeHandle.GetTypeByName (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark, System.Boolean loadTypeFromPartialName) [0x0008d] in <6bb86c3de8ca48108afad6fbeae44d18>:0 
  at System.RuntimeType.GetType (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark) [0x0000e] in <6bb86c3de8ca48108afad6fbeae44d18>:0 
  at System.Type.GetType (System.String typeName, System.Boolean throwOnError) [0x00002] in <6bb86c3de8ca48108afad6fbeae44d18>:0 
  at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) [0x00075] in <84c1e66ad9084759894c705e0effb343>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr,intptr,intptr,intptr,intptr)
       at mono.android.TypeManager.n_activate(TypeManager.java)
       at mono.android.TypeManager.Activate(TypeManager.java:7)
       at crc6482ae51f11c3df076.JunkerBootReceiver.<init>(JunkerBootReceiver.java:23)
       at java.lang.Class.newInstance(Class.java)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3769)
       at android.app.ActivityThread.-wrap18()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2100)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

```
### Expected Behavior
No exception and OnReceive method called

### Actual Behavior
Crash as descibed above

### Version Information

Visual Studio Community 2019 for Mac
Version 8.7.8 (build 4)
Installation UUID: 69833a91-0eac-4ae5-b6a6-d5db1c20fbb4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

Mono Framework MDK
Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

Roslyn (Language Service)
3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

NuGet
Version: 5.7.0.6702

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.301
	3.1.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.5
	3.1.4
	2.1.22
	2.1.19
	2.1.18

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

Xamarin Designer
Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/todor/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.1
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Microsoft OpenJDK for Mobile
Java SDK: /Users/todor/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

Android Device Manager
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

Build Information
Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

Operating System
Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jan 12 22:13:05 PST 2021
    root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

**Comment by jpobst** [comment]
Not entirely sure who to assign to. Please forward it on if it needs to be someone else.

**Comment by grendello** [comment]
It's some managed land issue, but there's not enough information.

@todorspetkov  - we'd need either a full logcat to get some context or, preferably, a small app with which you're able to reproduce this issue.

**Comment by todorspetkov** [comment]
@grendello - I will try to concot something but as I mentioned the bug info arrives from Firebase Crashlytics. I don't know if it is possible to get the full log from firebase...

**Comment by grendello** [comment]
@todorspetkov yeah, I understand, but alas - with the information in hand it's not possible to say what's going wrong. Would you be able to tell from Firebase what devices see the problem?

**Comment by todorspetkov** [comment]
@grendello - firebase reports this problem on the following (short list):

Galaxy A71 - Android 10
Galaxy A6 - Android 10
Galaxy S20 5G - Android 11
Galaxy J6 - Android 10
Galaxy A5(2016) - Android 7

Unfortunately I do not have any Galaxy phone in order to debug this on real hardware...
