### ISSUE TITLE
VS 16.9.0 Preview 4, Project Properties did not show any content and Deployment failed

### ISSUE THREAD

**Issue by yzbai** [xamarin/xamarin-android#5626]
In Version 16.9.0 Preview 4, here are the steps to recreate the problem:
1, Create a New xamarin android Project.
2, Close and reopen it.
3, Open Project Properties Window, it shows nothing.
4, Hit F5, output shows deploy failed.

**Comment by MagicAndre1981** [comment]
Any update? I see this in 16.9 and 16.10 preview 2 and I can't build the application:
 
![VS2019_16_10_Preview2_android](https://user-images.githubusercontent.com/8274816/115509237-7fe19000-a27e-11eb-99a2-9458aa5b2c6f.png)

But the csproj, of course, includes all data

**Comment by joj** [comment]
Does this happen if you map the network share to a drive letter (say, Z:)?

**Comment by MagicAndre1981** [comment]
> Does this happen if you map the network share to a drive letter (say, Z:)?

yes. But after some more testings it doesn't work even project is on local drive inside the VM.

The log shows some exceptions:

```C#
Xamarin|Information|0|Xamarin - 16.9.000.273-d16-9+1bba9e0
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing AndroidStarted event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify canceled => solution is not ready
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify canceled => solution is not ready
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.VisualStudio.Android.RemoveUseLatestSdkUsageHandler|Error|0|PSService!5492 HR: E_Exception
Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Clide.Adapters.MsBuildAdapter.Adapt(ProjectNode from) in E:\A\_work\349\s\src\Clide.Core.Windows\Adapters\MsBuildAdapter.cs:line 48
   at lambda_method(Closure , IAdapter , Object )
   at Clide.AdapterService.Adapt[TSource,TTarget](TSource source) in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 113
   at Clide.AdapterService.Adaptable`1.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 199
   at Clide.ProjectNode.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 143
   at Adapters.AsMsBuildProject(IProjectNode project) in E:\A\_work\349\s\src\Clide.Windows\Adapters\SolutionAdapterFacade.cs:line 195
   at Xamarin.VisualStudio.Android.RemoveUseLatestSdkUsageHandler.ExecuteAsync(RemoveUseLatestSdkUsageCommand command, CancellationToken cancellation) in C:\A\1\315\s\src\Core\VisualStudio.Android\CommandHandlers\RemoveUseLatestSdkUsageHandler.cs:line 62
Xamarin.VisualStudio.TastyFlavoredProject|Warning|0|An error occurred processing project references @ SolutionReady
Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Clide.Adapters.MsBuildAdapter.Adapt(ProjectNode from) in E:\A\_work\349\s\src\Clide.Core.Windows\Adapters\MsBuildAdapter.cs:line 48
   at lambda_method(Closure , IAdapter , Object )
   at Clide.AdapterService.Adapt[TSource,TTarget](TSource source) in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 113
   at Clide.AdapterService.Adaptable`1.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 199
   at Clide.ProjectNode.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 143
   at Adapters.AsMsBuildProject(IProjectNode project) in E:\A\_work\349\s\src\Clide.Windows\Adapters\SolutionAdapterFacade.cs:line 195
   at Xamarin.VisualStudio.Shell.XamarinFlavoredProject.GetReferenceProjectItem(Reference projectRef) in C:\A\1\315\s\src\Core\VisualStudio.Shell\FlavorProjects\XamarinFlavoredProject.cs:line 149
   at Xamarin.VisualStudio.Shell.XamarinFlavoredProject.ProcessProjectReference(Reference projectRef) in C:\A\1\315\s\src\Core\VisualStudio.Shell\FlavorProjects\XamarinFlavoredProject.cs:line 117
   at Xamarin.VisualStudio.Shell.XamarinFlavoredProject.ProcessProjectReferences(IEnumerable`1 references) in C:\A\1\315\s\src\Core\VisualStudio.Shell\FlavorProjects\XamarinFlavoredProject.cs:line 98
   at Xamarin.VisualStudio.TastyFlavoredProject.OnSolutionReady(Object sender, EventArgs e) in C:\A\1\315\s\src\Core\VisualStudio\FlavorProject\TastyFlavoredProject.cs:line 406
Xamarin.VisualStudio.UnhandledExceptionsManager|Error|0|An unhandled error occurred. Details: PSService!5492 HR: E_Exception

Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Xamarin.VisualStudio.Shell.ComponentsProject..ctor(String projectFilename) in C:\A\1\315\s\src\Core\VisualStudio.Shell\FlavorProjects\ComponentsProject.cs:line 17
   at Xamarin.VisualStudio.Shell.XamarinFlavoredProject.<<ShowMissingComponentsFeatureNotification>b__10_0>d.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio.Shell\FlavorProjects\XamarinFlavoredProject.cs:line 73
Xamarin.VisualStudio.Devices.DeviceManager|Error|0|lastDebugActiveProfile: 
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase|Error|0|PSService!5492 HR: E_Exception
Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Clide.Adapters.MsBuildAdapter.Adapt(ProjectNode from) in E:\A\_work\349\s\src\Clide.Core.Windows\Adapters\MsBuildAdapter.cs:line 48
   at lambda_method(Closure , IAdapter , Object )
   at Clide.AdapterService.Adapt[TSource,TTarget](TSource source) in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 113
   at Clide.AdapterService.Adaptable`1.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 199
   at Clide.ProjectNode.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 143
   at Adapters.AsMsBuildProject(IProjectNode project) in E:\A\_work\349\s\src\Clide.Windows\Adapters\SolutionAdapterFacade.cs:line 195
   at Clide.UserProjectProperties..ctor(ProjectNode project) in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\UserProjectProperties.cs:line 25
   at Clide.ProjectNode.get_UserProperties() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 115
   at Xamarin.VisualStudio.Devices.ActiveDebugProfileExtensions.SetActiveDebugProfile(IProjectNode projectNode, String deviceName) in C:\A\1\315\s\src\Core\Xamarin.VisualStudio.Interfaces\Extensions\ActiveDebugProfileExtensions.cs:line 30
   at Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase.<SaveSelectedDeviceUserPreferencesAsync>d__32.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\ProjectSystem\ProjectPropertiesBase.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase.<SetSelectedDeviceAsync>d__31.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\ProjectSystem\ProjectPropertiesBase.cs:line 80
Xamarin.VisualStudio.Devices.DeviceManager|Error|0|lastDebugActiveProfile: 
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase|Error|0|PSService!5492 HR: E_Exception
Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Clide.Adapters.MsBuildAdapter.Adapt(ProjectNode from) in E:\A\_work\349\s\src\Clide.Core.Windows\Adapters\MsBuildAdapter.cs:line 48
   at lambda_method(Closure , IAdapter , Object )
   at Clide.AdapterService.Adapt[TSource,TTarget](TSource source) in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 113
   at Clide.AdapterService.Adaptable`1.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\AdapterService.cs:line 199
   at Clide.ProjectNode.As[T]() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 143
   at Adapters.AsMsBuildProject(IProjectNode project) in E:\A\_work\349\s\src\Clide.Windows\Adapters\SolutionAdapterFacade.cs:line 195
   at Clide.UserProjectProperties..ctor(ProjectNode project) in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\UserProjectProperties.cs:line 25
   at Clide.ProjectNode.get_UserProperties() in E:\A\_work\349\s\src\Clide.Core.Windows\Solution\ProjectNode.cs:line 115
   at Xamarin.VisualStudio.Devices.ActiveDebugProfileExtensions.SetActiveDebugProfile(IProjectNode projectNode, String deviceName) in C:\A\1\315\s\src\Core\Xamarin.VisualStudio.Interfaces\Extensions\ActiveDebugProfileExtensions.cs:line 30
   at Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase.<SaveSelectedDeviceUserPreferencesAsync>d__32.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\ProjectSystem\ProjectPropertiesBase.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase.<SetSelectedDeviceAsync>d__31.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\ProjectSystem\ProjectPropertiesBase.cs:line 80
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: verify android sdk installed
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation|Information|0|androidsdksetup: removing android sdk errors
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Error|0|PSService!5492 HR: E_Exception
Microsoft.VisualStudio.ProjectServices.Hosting.SharedMemoryPipeException: PSService!5492 HR: E_Exception
   at Microsoft.VisualStudio.ProjectServices.Hosting.IProjectCollectionRemoterProxy.GetLocalLoadedProjects(String projectFile)
   at Microsoft.VisualStudio.ProjectServices.Hosting.ProjectCollectionLinker.GetLoadedProjects(String filePath)
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(Boolean includeExternal, String fullPath)
   at Xamarin.VisualStudio.Build.BuildRunner.CreateRequestData(IProjectNode project, String target, IDictionary`2 properties) in C:\A\1\315\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 201
   at Xamarin.VisualStudio.Build.BuildRunner.CreateSubmission(IProjectNode project, String target, IDictionary`2 globalProperties, ILogger defaultLogger) in C:\A\1\315\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 239
   at Xamarin.VisualStudio.Build.BuildRunner.<RunAsync>d__10.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Build.BuildCoordinator.<EnqueueAsync>d__12.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\Build\BuildCoordinator.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at Xamarin.VisualStudio.Build.BuildCoordinator.<EnqueueAsync>d__12.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio\Build\BuildCoordinator.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Services.AndroidToolsBuildService.<GetAndroidDependenciesAsync>d__10.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio.Android\Services\AndroidToolsBuildService.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Setup.AutoSdk.<GetProjectDependenciesAsync>d__14.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio.Android\Services\Setup\AutoSdk.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Setup.AutoSdk.<VerifyAsync>d__13.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio.Android\Services\Setup\AutoSdk.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup.<VerifyAsync>d__23.MoveNext() in C:\A\1\315\s\src\Core\VisualStudio.Android\Services\Setup\AndroidSdkSetup.cs:line 170

```

I opened Android SDK Manager, installed some updates but nothing changed.

**Comment by MagicAndre1981** [comment]
I just noticed I had the [same issue last year](https://github.com/xamarin/xamarin-android/issues/4922) and it was suddenly fixed. Now it came back after it worked for a longer time.

**Comment by joj** [comment]
I don't want to call it a known issue but the network path issue does ring a bell. We usually don't recommend that for performance reasons, but for some it is a very valid scenario and I think mapping the network path and using the mapped drive as a path will definitely help.

**Comment by MagicAndre1981** [comment]
I map the network share as drive ((\\vmware-host\shared folders and here the share name) and work this way for years and VS2017 never had any issues. A different[ issue was fixed](https://github.com/xamarin/xamarin-android/issues/5218) and I was able to use VS2019 fine. Now suddenly I get the issue again. 

And as I said in a comment, I now also get this error on local drive inside the VM. Properties are here also empty. Right after I created the new project everything was fine. When I now open that Xamarin.Forms App (flyout) again without any changes the issue shows up.

So it is not related to network. I see this in 16.9 and 16.10 Preview 2.

**Comment by MagicAndre1981** [comment]
ok, I created a new VM with VS2019 16.9.4 and here it works all time. Local projects, from network drive, old or new projects. 

So something broke the 2 installations, now I need to find out what. I'll do that tomorrow.

**Comment by MagicAndre1981** [comment]
ok, I looked at the log from the VS inside the new VM and here I see no `SharedMemoryPipeException`. 

Is there any way to see more details what fails here? @joj

**Comment by joj** [comment]
You can try attaching a second VS to your first one, and making it break on all exceptions, then try to open properties. You will not get a lot of information there (it's mostly all private) but I should be able to tell with the class and method names if they show.

**Comment by MagicAndre1981** [comment]
> You can try attaching a second VS to your first one, and making it break on all exceptions, then try to open properties. You will not get a lot of information there (it's mostly all private) but I should be able to tell with the class and method names if they show.

I used Perfview to capture `Microsoft-Windows-DotNETRuntime` events with `ExceptionKeyword` and the new Visual Studio install in the fresh VM has no `SharedMemoryPipeException` events in the trace. 

I can also see Pipe closed System.IO.Exception from `Microsoft.ServiceHub.Controller` in the broken VS installation.

**Comment by MagicAndre1981** [comment]
ok, I also failed to see more details in the ETL (ETW always misses details about variables in events. I saw messages about service not implemented, but not which service. This is why I always create my own EventSource Exception logger which shows more details).

So I ended up doing a [repair of the VS installation](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019) and this worked. Now I see the values again in the properties dialog of the android application @joj 

@yzbai also try this please

![image](https://user-images.githubusercontent.com/8274816/115879050-840dd900-a449-11eb-94bd-1034ba82ea31.png)

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
