### ISSUE TITLE
IsolatedStorageFile.GetUserStoreForApplication throws "Initialization failed." on net6

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#5705]
### Steps to Reproduce

1. Call `IsolatedStorageFile.GetUserStoreForApplication()`

### Expected Behavior

No crash and the correct result.

### Actual Behavior

```
 android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> System.TypeInitializationException: The type initializer for 'Microsoft.Maui.Controls.UriImageSource' threw an exception.
  ---> System.IO.IsolatedStorage.IsolatedStorageException: Initialization failed.
    at System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash(Object& identity, String& hash, Char separator)
    at System.IO.IsolatedStorage.IsolatedStorage.InitStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
    at System.IO.IsolatedStorage.IsolatedStorageFile..ctor(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication()
```

### Version Information

TFM: `net6.0-android`

**Comment by jpobst** [comment]
@steveisok Should this be in some sort of `dotnet` or `mono` repo?

**Comment by mattleibow** [comment]
Moved to https://github.com/dotnet/runtime/issues/52332
