### ISSUE TITLE
JnienvTest.CreateTypeWithExportedMethods fails on .NET 6

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#5800]
After the resolution of #5286, the [JnienvTest.CreateTypeWithExportedMethods](https://github.com/xamarin/xamarin-android/blob/9fdf6c46fc4f01e55b74bd6a0bf73b9ff731e766/tests/Mono.Android-Tests/Java.Interop/JnienvTest.cs#L223) test is still failing on .NET 6:

```
03-30 13:56:04.281  4247  4271 I NUnit   : CreateTypeWithExportedMethods 
03-30 13:56:04.282  4247  4271 I monodroid-timing: Typemap.managed_to_java: end, total time; elapsed: 0s:0::21800
03-30 13:56:04.282  4247  4271 I DOTNET  : # ContainsExportedMethods: constructed! Handle=0x2aa6
03-30 13:56:04.283  4247  4271 W monodroid: MonodroidRuntime::monodroid_pinvoke_override ("java-interop", "java_interop_jnienv_exception_clear")
03-30 13:56:04.284  4247  4271 I monodroid-timing: p/invoke cache lookup for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::17200
03-30 13:56:04.284  4247  4271 I monodroid-timing: p/invoke override for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::54600
03-30 13:56:04.284  4247  4271 W monodroid: Found java-interop@java_interop_jnienv_exception_clear in internal p/invoke map (0xbe0612d0)
03-30 13:56:04.284  4247  4271 W monodroid: MonodroidRuntime::monodroid_pinvoke_override ("java-interop", "java_interop_jnienv_exception_clear")
03-30 13:56:04.284  4247  4271 I monodroid-timing: p/invoke cache lookup for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::22100
03-30 13:56:04.284  4247  4271 I monodroid-timing: p/invoke override for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::62700
03-30 13:56:04.284  4247  4271 W monodroid: Found java-interop@java_interop_jnienv_exception_clear in internal p/invoke map (0xbe0612d0)
03-30 13:56:04.285  4247  4271 W monodroid: MonodroidRuntime::monodroid_pinvoke_override ("java-interop", "java_interop_jnienv_exception_clear")
03-30 13:56:04.286  4247  4271 I monodroid-timing: p/invoke cache lookup for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::15300
03-30 13:56:04.286  4247  4271 I monodroid-timing: p/invoke override for 'java_interop_jnienv_exception_clear' (internal); elapsed: 0s:0::48500
03-30 13:56:04.286  4247  4271 W monodroid: Found java-interop@java_interop_jnienv_exception_clear in internal p/invoke map (0xbe0612d0)
03-30 13:56:04.287  4247  4271 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::47900
03-30 13:56:04.346  4247  4271 E NUnit   : 	[FAIL]
03-30 13:56:04.360  4247  4271 E NUnit   :  : Java.Lang.NoSuchMethodError : no non-static method "Lcrc641855b07eca6dcc03/ContainsExportedMethods;.Exported()V"
03-30 13:56:04.362  4247  4271 E NUnit   :    at Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, String name, String signature)
03-30 13:56:04.362  4247  4271 E NUnit   :    at Android.Runtime.JNIEnv.GetMethodID(IntPtr kls, String name, String signature)
03-30 13:56:04.362  4247  4271 E NUnit   :    at Java.InteropTests.JnienvTest.CreateTypeWithExportedMethods()
03-30 13:56:04.362  4247  4271 E NUnit   :    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
03-30 13:56:04.362  4247  4271 E NUnit   :   --- End of managed Java.Lang.NoSuchMethodError stack trace ---
03-30 13:56:04.362  4247  4271 E NUnit   : java.lang.NoSuchMethodError: no non-static method "Lcrc641855b07eca6dcc03/ContainsExportedMethods;.Exported()V"
03-30 13:56:04.362  4247  4271 E NUnit   : 	at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
03-30 13:56:04.362  4247  4271 E NUnit   : 	at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(Unknown Source:0)
03-30 13:56:04.362  4247  4271 E NUnit   : 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)```

**Comment by pjcollins** [comment]
Oops I missed a preprocessor directive that was causing this to break, closing.
