### ISSUE TITLE
One .NET: Remove BinaryFormatters support

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#5944]
`BinaryFormatter` has been deprecated, and is no longer part of the mobile profile in .NET 6; see also: https://github.com/dotnet/designs/blob/8bff552b2bf5d9a36d39db58d106e2b2d34a510a/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md

As of https://discordapp.com/channels/732297728826277939/732297837953679412/844981772445024306 this change has caused our `JsonDeserializationCreatesJavaHandle` unit test to start failing: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4770105&view=ms.vss-test-web.build-test-results-tab&runId=21773130&resultId=100082&paneView=debug

```
Output did contain TestJsonDeserializationCreatesJavaHandle!
Expected: False
But was:  True
```

`logcat-failed.txt` contains:

```
--------- beginning of crash
05-18 03:12:13.988 10832 10832 E AndroidRuntime: FATAL EXCEPTION: main
05-18 03:12:13.988 10832 10832 E AndroidRuntime: Process: com.xamarin.jsondeserializationcreatesjavahandle, PID: 10832
05-18 03:12:13.988 10832 10832 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
05-18 03:12:13.988 10832 10832 E AndroidRuntime:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph) in System.Runtime.Serialization.Formatters.dll:token 0x600013c+0x5
05-18 03:12:13.988 10832 10832 E AndroidRuntime:    at UnnamedProject.MainActivity.TestBinaryDeserialization(Person p) in UnnamedProject.dll:token 0x6000003+0xd
05-18 03:12:13.988 10832 10832 E AndroidRuntime:    at UnnamedProject.MainActivity.TestJsonDeserializationCreatesJavaHandle() in UnnamedProject.dll:token 0x6000004+0x1d
05-18 03:12:13.988 10832 10832 E AndroidRuntime:    at UnnamedProject.MainActivity.OnCreate(Bundle bundle) in UnnamedProject.dll:token 0x6000001+0x4b
05-18 03:12:13.988 10832 10832 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in Mono.Android.dll:token 0x60150af+0xf
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at com.xamarin.jsondeserializationcreatesjavahandle.MainActivity.n_onCreate(Native Method)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at com.xamarin.jsondeserializationcreatesjavahandle.MainActivity.onCreate(MainActivity.java:29)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7802)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7791)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-18 03:12:13.988 10832 10832 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

We should disable the `TestJsonDeserializationCreatesJavaHandle` unit test when target .NET 6, and remove the infrastructure within `Mono.Android.dll` which was used to make this work.

**Comment by akoeplinger** [comment]
I think disabling `TestBinaryDeserialization` should be enough.
