### ISSUE TITLE
Project suddenly failing at linker - XALNK7000 - System.ArgumentNullException

### ISSUE THREAD

**Issue by alexhardwicke** [xamarin/xamarin-android#6040]
### Steps to Reproduce

1. Ensure linker is set to Sdk only
2. Build project

Sadly I don't seem to have much more to go on than that, I have no idea what the cause is and I don't have a repro project - it's happening in an enterprise XF app. I've added some information at the bottom.

### Expected Behavior
Project builds successfully.

### Actual Behavior
Build fails at linker stage.

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.10.2
VisualStudio.16.Release/16.10.2+31410.357
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA819
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.10.526.50910
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanBinAndObjCommand Extension   1.1.0
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Code Cleanup On Save   1.0.12
Automatically run one of the Code Clean profiles when saving the document. This ensures your code is always formatted correctly and follows your coding style conventions.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

I Hate #Regions   1.0
Regions Suck.  You need this.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

Switch Startup Project   4.1.71
Provides a toolbar dropdown box  to switch between startup projects.

ToastNotifier   1.0
Show Toast Notification when Bulid completed.

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VsVim   2.9.0.0
VsVim is a Vim emulator for Visual Studio

Xamarin   16.10.000.231 (d16-10@8111164)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.10 (0e35b2e0b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

I've attached an msbuild log at diagnostic level. The template instructions are asking for adb logs but that's obviously not relevant here.

The project consists of five .NET Standard projects (two are .NET Standard 2.0, three are .NET Standard 2.1), an Android head and an iOS head that can be ignored.

I've tried doing git bisect from a known good commit and get inconsistent results, which is baffling. It's failing on all computers we've tried, over multiple geographic regions including via Azure DevOps so it doesn't seem to be a configuration thing.

At first I thought the problem was caused by one of the projects gaining a reference to System.Threading.Tasks.DataFlow (5.0.0.0), but removing it has made no difference.

What I have noticed is that when all of the various DLLs drop into "obj\Release\110\android\assets" directory as linking is happening, the DLL that fails has a filesize of 0kb. I'm not sure if that's because of the exception, or the cause of it. If I manually copy the DLL there myself and then choose to build again (no clean or rebuild) then VS completes the build successfully. That's not something I can or want to do on a build server, though.

```The top of the call stack and previous line in msbuild are:
6>  Output action:     Save assembly: Mobigo.Mobile.Core, Version=7.7.0.0, Culture=neutral, PublicKeyToken=null (TaskId:302)
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000: Mono.Linker.OutputException: Failed to write 'S:\Mobigo\Mobigo.Mobile.vNext\Mobigo.Mobile.vNext.Android\obj\Release\110\android\assets\Mobigo.Mobile.Core.dll ---> System.ArgumentNullException: Value cannot be null.
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000: Parameter name: key
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Cecil.Cil.CodeWriter.CopyBranchStackSize(Dictionary`2& stack_sizes, Instruction target, Int32 stack_size) in
```

I'm happy to dig deeper and try to figure out what the problem is, I'm aware aside from the log there's not much to go on but I have no idea what the cause could be so have no idea how to make a repro project.

**Comment by dellis1972** [comment]
@alexhardwicke  do you have the full diagnostic log you mentioned? I can't see it attached to this issue anywhere?

**Comment by alexhardwicke** [comment]
Whoops! Looks like I forgot the file. Or rather, looks like I didn't notice that Github won't let me attach a 61MB (!) text file.

I've uploaded it to https://www.alexhardwicke.com/msbuildlog.txt

**Comment by jonathanpeppers** [comment]
The stack trace seems like Mono.Cecil is failing on some (maybe unexpected?) IL when saving your assembly:
```
error XALNK7000: Mono.Linker.OutputException: Failed to write 'S:\Mobigo\Mobigo.Mobile.vNext\Mobigo.Mobile.vNext.Android\obj\Release\110\android\assets\Mobigo.Mobile.Core.dll ---> System.ArgumentNullException: Value cannot be null.
error XALNK7000: Parameter name: key
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at Mono.Cecil.Cil.CodeWriter.CopyBranchStackSize(Dictionary`2& stack_sizes, Instruction target, Int32 stack_size) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 417
at Mono.Cecil.Cil.CodeWriter.CopyBranchStackSize(Instruction instruction, Dictionary`2& stack_sizes, Int32 stack_size) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 399
at Mono.Cecil.Cil.CodeWriter.ComputeStackSize(Instruction instruction, Dictionary`2& stack_sizes, Int32& stack_size, Int32& max_stack) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 387
at Mono.Cecil.Cil.CodeWriter.ComputeHeader() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 340
at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 106
at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.Cil/CodeWriter.cs:line 54
at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1664
at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1656
at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1446
at Mono.Cecil.MetadataBuilder.AddNestedTypes(TypeDefinition type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1598
at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1461
at Mono.Cecil.MetadataBuilder.AddTypes() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1418
at Mono.Cecil.MetadataBuilder.BuildTypes() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1266
at Mono.Cecil.MetadataBuilder.BuildModule() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1036
at Mono.Cecil.MetadataBuilder.BuildMetadata() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1006
at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 144
at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 971
at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 143
at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 119
at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 78
at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 1160
at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
--- End of inner exception stack trace ---
at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```
If you drop `Mobigo.Mobile.Core.dll` into a new blank project, do you hit the same issue?

Are you using any IL-rewriting tooling like Fody?

**Comment by alexhardwicke** [comment]
@jonathanpeppers You're a life-saver. Seems to be ConfigureAwait.Fody - if I remove that everything seems to work perfectly. Can't believe I didn't think about Fody.

Thanks a lot for the help. :)
