### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty"

### ISSUE THREAD

**Issue by akalghatgi** [xamarin/xamarin-android#6219]
Using the Binding in App fails with "Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty"" even when reference for "Xamarin.Kotlin.Stdlib(1.4.21)" is referenced in Binding and App.

Steps:
 1.  Created the Binding with reference
 2. Add to App as Nuget 
 3. Run the App... Crashes on Launch with above Error

### Error Message or Issue
Error Stack:
2021-08-22 15:21:20.228 31045-31045/com.airwatch.sample.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airwatch.sample.app, PID: 31045
    java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;
        at com.airwatch.app.AWSDKApplicationDelegate.<clinit>(Unknown Source:3)
        at com.airwatch.app.AWApplication.<init>(Unknown Source:3)
        at crc64f6db8ad893f51f95.SampleApplication.<init>(SampleApplication.java:24)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1298)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7419)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7392)
        at android.app.ActivityThread.access$1400(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty" on path: DexPathList[[zip file "/data/app/~~P1KHYzmxSl9ORsSBPnKmEw==/com.airwatch.sample.app-_H7rrVG5F4guahP8RpFngQ==/base.apk"],

### Version Information

<details>
=== Visual Studio Community 2019 for Mac ===

Version 8.10.7 (build 17)
Installation UUID: fe7969a9-be35-4c19-9a0c-f5c9ebb3f9aa
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.302
	2.1.811
	2.1.809
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.2
	5.0.1
	5.0.0
	5.0.0-rc.2.20475.5
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.6
	2.1.23
	2.1.22
	2.1.21
	2.1.20

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/akalghatgi@vmware.com/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/akalghatgi@vmware.com/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:48:52 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:49:10 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19161.15)
Build 13A5155e

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810070017
Git revision: 503b9b053dff2e7f136e96b362a629c199f78a42
Build date: 2021-08-05 12:48:29-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Fri Mar  5 01:14:14 PST 2021
    root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64

</details>

### Log File

[LogFile.txt](https://github.com/xamarin/xamarin-android/files/7027089/LogFile.txt)

### Other Helpful Info

NOTE: If I add the kotlin.stdlib-1.4.21.jar to Jars folder with "EmbeddedReferenceJar" in Binding it works fine and App runs but my Forms Nuget will fail in App with error
Error in obj/Release/androidx/jl/7a63b069-1bc9-4128-8454-de45e382de23.jar:kotlin/collections/ArraysUtilJVM.class:
    Type kotlin.collections.ArraysUtilJVM is defined multiple times: obj/Release/androidx/jl/7a63b069-1bc9-4128-8454-de45e382de23.jar:kotlin/collections/ArraysUtilJVM.class, obj/Release/lp/6/jl/__reference__kotlin-stdlib.jar:kotlin/collections/ArraysUtilJVM.class
    Compilation failed
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(51,5): error MSB6006: "java" exited with code 1.
  Done executing task "R8" -- FAILED.

Is there any solution to this.., or Am I doing anything wrong.?

**Comment by jpobst** [comment]
You might want to look at the workarounds listed in these issues to see if it fixes it for you:

- https://github.com/xamarin/xamarin-android/issues/6201
- https://github.com/xamarin/xamarin-android/issues/6172

**Comment by jpobst** [comment]
We think this is because the Kotlin package needs the `.targets` file in the `build` folder when building with `packages.config`.  So another way to fix this would be to migrate to `<PackageReference>` instead of `packages.config`.

https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

We'll look into updating the package(s) to work with `packages.config` by default as well.
