### ISSUE TITLE
VS2022 17.0.0 Preview 4.0 and 4.1 

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6345]
Are you guys aware that the Android Designer doesn't load? 
Open any layout file and all you get is the XML. It was reported via VS's Help, Send Feedback for 4.0, but obviously, nothing got fixed for 4.1.

The following is from the Xamarin/logs/17.0 from the .ide file. 
Ironically after not being able to open any layout file without an error in VS since Feb last year I now can!!

 

```
Xamarin Information: 0 : Xamarin - 17.0.0.266-d17-0+56a1e79: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.0186584Z: 09/29/2021 04:52:25Z
Xamarin Information: 0 : !Xamarin - 17.0.0.266-d17-0+56a1e79: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.0196552Z: 09/29/2021 04:52:25Z
Xamarin.VisualStudio.Android.XamarinAndroidPackage Warning: 0 : Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.0655015Z: 09/29/2021 04:52:25Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: processing AndroidStarted event: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.5751394Z: 09/29/2021 04:52:25Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.5781620Z: 09/29/2021 04:52:25Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: verify canceled => solution is not ready: 09/29/2021 04:52:25Z
    DateTime=2021-09-29T04:52:25.5781620Z: 09/29/2021 04:52:25Z
Xamarin.Designer Information: 0 : 
[2021-09-29 14:52:32.1] ERROR: : Couldn't update deploy enabled state
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.AndroidTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0cb85e4f39dfce87' or one of its dependencies. The system cannot find the file specified.
File name: 'Mono.AndroidTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0cb85e4f39dfce87'
   at Xamarin.Android.Deploy.DeployService.CanDeployAsync()
   at Xamarin.VisualStudio.Android.Deploy.Commands.DeployCommand.<UpdateDeployEnabledAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Designer.Tasks.<IgnoreIfFaulted>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
: 09/29/2021 04:52:32Z
    DateTime=2021-09-29T04:52:32.1601184Z: 09/29/2021 04:52:32Z
Xamarin.VisualStudio.ProjectSystem.ProjectsTracker Error: 0 : An item with the same key has already been added.: 09/29/2021 04:52:32Z
    DateTime=2021-09-29T04:52:32.7016416Z: 09/29/2021 04:52:32Z
Xamarin.VisualStudio.Devices.DeviceManager Error: 0 : lastDebugActiveProfile: : 09/29/2021 04:52:32Z
    DateTime=2021-09-29T04:52:32.7654682Z: 09/29/2021 04:52:32Z
Xamarin.VisualStudio.Devices.DeviceManager Error: 0 : lastDebugActiveProfile: Google Pixel 3a: 09/29/2021 04:52:32Z
    DateTime=2021-09-29T04:52:32.8642058Z: 09/29/2021 04:52:32Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: verify android sdk installed: 09/29/2021 04:52:34Z
    DateTime=2021-09-29T04:52:34.0151279Z: 09/29/2021 04:52:34Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: removing android sdk errors: 09/29/2021 04:52:34Z
    DateTime=2021-09-29T04:52:34.0171218Z: 09/29/2021 04:52:34Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: verify error: : 09/29/2021 04:52:38Z
    DateTime=2021-09-29T04:52:38.3679413Z: 09/29/2021 04:52:38Z

```

**Comment by bddckr** [comment]
I believe this is expected, see [here](https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning#jdk-11-caused-regressions). I get the same issue, so perhaps that Wiki page just needs an update to mention the same issue applies to VS _2022_?

**Comment by dellis1972** [comment]
@gmck the team who maintain the designer are aware it does not work at the moment. There are issues with the designer needing JDK 1.8 to work , but our build system needs JDK 11 . Those issues are being worked on. 

It isn't our team which deals with this.

**Comment by jonathanpeppers** [comment]
We have some information about the designer here:

https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning#jdk-11-caused-regressions

You are generally better off reporting designer issues using the `Send Feedback` button in Visual Studio. This particular issue they know about, and hopefully should be fixed in the next preview.
