### ISSUE TITLE
System.Reflection being removed when using "Link SDK only" setting

### ISSUE THREAD

**Issue by drasticactions** [xamarin/xamarin-android#6366]
In past versions of Xamarin.Android, whenever we set "Link SDK Only" as the Linker setting for a project, we would have access to System.Reflection. This seems to be stripped in newer versions, and it's causing issues for Xamarin.Forms XAML Hot Reload.

https://developercommunity.visualstudio.com/t/XAML-Hot-Reload-Not-Working-on-Android-P/1400467

This user set their Xamarin.Forms Android project to use "Link SDK Only" for the Linker. When XAML Hot Reload tries to inject, it blows up:

```
Mono.Debugging.Evaluation.EvaluatorException: Method `Load' not found in type `System.Reflection.Assembly'.
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.OverloadResolveMulti(SoftEvaluationContext ctx, TypeMirror type, String methodName, ArgumentType[] genericTypeArgs, TypeMirror returnType, ArgumentType[] argTypes, List`1 candidates, Boolean throwIfNotFound, Boolean tryCasting) in C:\A\1\216\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2619
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.OverloadResolveMulti(SoftEvaluationContext ctx, TypeMirror type, String methodName, ArgumentType[] genericTypeArgs, TypeMirror returnType, ArgumentType[] argTypes, Boolean allowInstance, Boolean allowStatic, Boolean throwIfNotFound, Boolean tryCasting) in C:\A\1\216\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2511
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues, Boolean enableOutArgs, Object[]& outArgs) in C:\A\1\216\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2304
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues) in C:\A\1\216\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2281
   at Xamarin.HotReload.HotReloadSharedBridge.InjectAndLoadAssembly(IProject project, SoftEvaluationContext context, String assemblyPath) in D:\a\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadSharedBridge.cs:line 359
```

This, I believe, is caused by System.Reflection.Assembly or System.Refelection being removed. We can tell our users to use "Don't Link" and that does work, but for this user, for whatever reason, they can't. 

I'm not sure if this affects .NET 6 projects as well, as I'm not sure how to change the linker settings in the csproj, but I think we need to keep System.Reflection around.

**Comment by jonpryor** [comment]
The "real" question is this: why is a *Debug configuration build* enabling *any* linking at all?

The intent for the Debug config is "fast turnaround time" for the "inner dev loop".  Linking *is not* and *cannot* be "fast", and is *not* intended for use in the inner dev loop.  Why is linking enabled for the Debug configuration *at all*?

Additionally, that "yellow bar" shouldn't mention "Link SDK Assemblies Only".  It should *only* mention "Don't Link".

**Comment by jpobst** [comment]
The XAML Hot Reload documentation says "Don't Link" should be selected:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload

I think this probably just needs the yellow bar updated to remove that suggestion.

**Comment by jpobst** [comment]
Updated the internal issue to our resolution that the yellow bar should be updated to only suggest "Don't Link".

Nothing more for SDK.
