### ISSUE TITLE
XABBA7000 build error: "Renaming temporary file failed: Permission denied"

### ISSUE THREAD

**Issue by jeremy-bridges** [xamarin/xamarin-android#6467]
### Steps to Reproduce

1. Build in release mode, with the following settings in the Xamarin.Android project.
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <LangVersion>latest</LangVersion>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <BundleAssemblies>false</BundleAssemblies>
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidLinkMode>None</AndroidLinkMode>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidSupportedAbis />
    <AndroidPackageFormat>aab</AndroidPackageFormat>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    <AndroidAddKeepAlives>false</AndroidAddKeepAlives>
  </PropertyGroup>

### Expected Behavior

Build works.

### Actual Behavior

This error is seen:
XABBA7000: Xamarin.Tools.Zip.ZipException: Renaming temporary file failed: Permission denied
   at Xamarin.Tools.Zip.ZipArchive.Close() in /Users/runner/work/1/s/ZipArchive.cs:line 874
   at Xamarin.Android.Tasks.ZipArchiveEx.Flush()
   at Xamarin.Android.Tasks.BuildApk.AddAssemblies(ZipArchiveEx apk, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
   at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
   at Xamarin.Android.Tasks.BuildApk.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17

### Version Information

VS 2019 for Windows (16.11.5)

### Log File

See attached file:

[vs.2021.11.04.log.zip](https://github.com/xamarin/xamarin-android/files/7479191/vs.2021.11.04.log.zip)

**Comment by jonathanpeppers** [comment]
Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of the error? Thanks!

**Comment by moov123** [comment]
any solution to this?

**Comment by jonathanpeppers** [comment]
@moov123 if you can give more info that would help, looking for a build log: https://github.com/xamarin/xamarin-android/issues/6467#issuecomment-961888477

**Comment by soniiic** [comment]
Command used was: `msbuild.exe -verbosity:diag /p:Configuration=Release /t:Build;PackageForAndroid Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj`

This is the part of the msbuild where the zip exception happens:


	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Buffers.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Core.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.IO.Compression.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.IO.Compression.FileSystem.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Net.Http.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Numerics.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Runtime.CompilerServices.Unsafe.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Runtime.Serialization.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Xml.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Xml.Linq.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Data.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Drawing.Common.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.ComponentModel.Composition.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.ComponentModel.DataAnnotations.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\Mono.Security.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.ServiceModel.Internals.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\obj\Release\100\android\lz4\System.Threading.Tasks.Extensions.dll.lz4 as the archive file is out of date. (TaskId:853)
	  Adding native library: obj\Release\100\app_shared_libraries\armeabi-v7a\libxamarin-app.so (APK path: lib/armeabi-v7a/libxamarin-app.so) (TaskId:853)
	  Adding native library: obj\Release\100\app_shared_libraries\x86\libxamarin-app.so (APK path: lib/x86/libxamarin-app.so) (TaskId:853)
	  Adding native library: obj\Release\100\app_shared_libraries\x86_64\libxamarin-app.so (APK path: lib/x86_64/libxamarin-app.so) (TaskId:853)
	  Adding native library: obj\Release\100\app_shared_libraries\arm64-v8a\libxamarin-app.so (APK path: lib/arm64-v8a/libxamarin-app.so) (TaskId:853)
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000: Xamarin.Tools.Zip.ZipException: Renaming temporary file failed: Permission denied [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000:    at Xamarin.Tools.Zip.ZipArchive.Close() in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs:line 874 [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000:    at Xamarin.Android.Tasks.ZipArchiveEx.Flush() [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000:    at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo) [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000:    at Xamarin.Android.Tasks.BuildApk.RunTask() [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1975,3): error XABLD7000:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17 [c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj]
	Done executing task "BuildApk" -- FAILED. (TaskId:853)
	Done building target "_BuildApkEmbed" in project "Foobar.Mobile.Android.csproj" -- FAILED.: (TargetId:1160)
	Done Building Project "c:\nobackup\SC\Foobarmobile\Foobar.Mobile\Foobar.Mobile.Android\Foobar.Mobile.Android.csproj" (Build;PackageForAndroid target(s)) -- FAILED.

**Comment by jonathanpeppers** [comment]
It looks like the failure is here:

https://github.com/xamarin/LibZipSharp/blob/8e22fe1b249db2452e64c5d0a8d0b57875169b36/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs#L939-L940

A Windows native library, `libzip.dll`, returned the error message here. It appears to write to a temporary file and rename it to the final destination?

The thing that comes to mind is an antivirus like Windows Defender. If you add a Windows Defender exclusion to your project/solution directory, does that solve the problem? Might also try the same with `%TEMP%`.
