### ISSUE TITLE
building xamarin-android in linux

### ISSUE THREAD

**Issue by Joilnen** [xamarin/xamarin-android#6523]
I got this error:
---
Updating external repositories
  • monodroid
    🔗 cloning from xamarin/monodroid
Cloning into 'monodroid'...
  Error: Process '/sbin/git --no-pager -C "/home/joilnen/xamarin-android/external" clone --progress "https://github.com:/xamarin/monodroid"' timed out after 00:30:00
Password for 'https://@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/xamarin/monodroid/'

**Comment by Joilnen** [comment]
in the second time I tried got this:
---
Updating external repositories
  • monodroid
    🔗 fetching changes from xamarin/monodroid
fatal: could not read Username for 'https://github.com': Success
error: Could not fetch origin
Elapsed: 00:00:10.7026808
  Error: fatal: could not read Username for 'https://github.com': Success
  Error: error: Could not fetch origin
  Error: Failed to fetch changes for monodroid
  • mono
Generating bin/BuildDebug/MonoGitHash.props
Step Xamarin.Android.Prepare.Step_PrepareExternalGitDependencies failed
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_PrepareExternalGitDependencies failed
   at Xamarin.Android.Prepare.Scenario.Run(Context context, Log log) in /home/joilnen/xamarin-android/build-tools/xaprepare/xaprepare/Application/Scenario.cs:line 50
   at Xamarin.Android.Prepare.Context.Execute() in /home/joilnen/xamarin-android/build-tools/xaprepare/xaprepare/Application/Context.cs:line 831
   at Xamarin.Android.Prepare.App.Run(String[] args) in /home/joilnen/xamarin-android/build-tools/xaprepare/xaprepare/Main.cs:line 171

make: *** [Makefile:215: prepare-external-git-dependencies] Error 1

**Comment by grendello** [comment]
Updating external dependencies is for MS team members only (as per [this document](https://github.com/xamarin/xamarin-android/blob/main/Documentation/building/unix/instructions.md#building-xamarinandroid), item `5.`). Just run `make prepare` with all the dependencies present.
