### ISSUE TITLE
Xamarin.VisualStudio.UnhandledExceptionsManager Error: 0 : An unhandled error occurred. Details: Unknown property key for value list directories in which to look for classes!

### ISSUE THREAD

**Issue by fgonc124** [xamarin/xamarin-android#6586]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2019

### Description

Hi

After I upgraded VStudio from 16.11.3. to 16.11.6 I get the following error when I open/create a xamarin project

In ide.log I found thie error msg

**_Xamarin.VisualStudio.UnhandledExceptionsManager Error: 0 : An unhandled error occurred. Details: Unknown property key for value list directories in which to look for classes!

System.InvalidOperationException: Unknown property key for value list directories in which to look for classes!
at Xamarin.Android.Tools.JdkInfo.<>c__DisplayClass46_0.b__0(Object o, DataReceivedEventArgs e) in D:\a_work\1\s\External\androidtools\external\xamarin-android-tools\src\Xamarin.Android.Tools.AndroidSdk\JdkInfo.cs:line 263_**

I get the same error with recent versions 16.11.7 and 16.11.8 . Even with VStudio 2022 I eget the same error.
If I install 16.11.3 everything works fine.

Do you have any idea of waht's causing this error. I've beeing struglling with this error for 2 months. Microsoft didn't help.

Thanks

### Steps to Reproduce

Install VStudio 16.11.4 / 5/6 /7 /8 or Vstudio 2022

Create/open  a Xamarin Project
VStudio starts creating/opening the project and suddenly  it closes.

Checking C:\Users\<username>\AppData\Local\Xamarin\Logs\17.0\ide.log i found the error msg shown above

Microsoft didn't provide any workaorund.

If I install 16.11.3 everything works fine

### Did you find any workaround?

No I didn't find any workarond

### Relevant log output

```shell
Xamarin Information: 0 : Xamarin - 17.0.0.343-d17-0+fb07a17: 12/17/2021 16:46:37Z
    DateTime=2021-12-17T16:46:37.3080304Z: 12/17/2021 16:46:37Z
Xamarin Information: 0 : !Xamarin - 17.0.0.343-d17-0+fb07a17: 12/17/2021 16:46:37Z
    DateTime=2021-12-17T16:46:37.3090201Z: 12/17/2021 16:46:37Z
Xamarin.VisualStudio.Android.XamarinAndroidPackage Warning: 0 : Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage: 12/17/2021 16:46:37Z
    DateTime=2021-12-17T16:46:37.4490220Z: 12/17/2021 16:46:37Z
Xamarin.VisualStudio.UnhandledExceptionsManager Error: 0 : An unhandled error occurred. Details: Unknown property key for value                       list directories in which to look for classes!

System.InvalidOperationException: Unknown property key for value                       list directories in which to look for classes!
   at Xamarin.Android.Tools.JdkInfo.<>c__DisplayClass46_0.<GetJavaProperties>b__0(Object o, DataReceivedEventArgs e) in D:\a\_work\1\s\External\androidtools\external\xamarin-android-tools\src\Xamarin.Android.Tools.AndroidSdk\JdkInfo.cs:line 263
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch(): 12/17/2021 16:46:38Z
    DateTime=2021-12-17T16:46:38.8120913Z: 12/17/2021 16:46:38Z
```

**Comment by jpobst** [comment]
I think this issue has been fixed here:
https://github.com/xamarin/xamarin-android-tools/commit/0a229578ea0a2dbacffbc4d1ffc48c04bc46625a

However, the fix is probably too recent to be in a "release" version of Visual Studio yet.

It will hopefully be fixed in VS2022 17.1 Preview 2 when it is available.

https://visualstudio.microsoft.com/vs/preview

**Comment by fgonc124** [comment]
HI jpobst 

I'll wait for the Vs2022 17.1 Preview 2 to try that fix.

Will that fix be available to VS2019?
Thanks

**Comment by jpobst** [comment]
> Will that fix be available to VS2019?

I doubt it.  VS2019 no longer receives updates other than critical priority fixes.

**Comment by jpobst** [comment]
VS2022 17.1 Preview 2 is available:
https://devblogs.microsoft.com/visualstudio/visual-studio-17-1-preview-2-is-now-available/

**Comment by fgonc124** [comment]
Thanks Jpobst

**Comment by jpobst** [comment]
I'm assuming the preview has resolved this issue.  Closing issue.

**Comment by fgonc124** [comment]
HI. yes Vs2022 17.1 Preview solved the problem. Vs2019 sitll with problem

**Comment by fgonc124** [comment]
Thanks
