### ISSUE TITLE
Xamarin Forms Android linker problem in VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6730]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Forms-Android-linker-problem-in-/1647172)._

---
[regression] [worked-in:VS2019 version 16.11.9]
While trying to Archive a Xamarin Android project using VS 2022 Version 17.0.5 with linker set to "SDK Assemblies Only" I get the error XALNK7004. If I set linker to None, the apk is built successfully. It seems the same problem in Xamarin Forms Android Linker problem after upgrading MsBuild version.

This is logged:
Touching "obj\Release\110\stamp\_AndroidXCecilfy.stamp".
XALNK7004: System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at MonoDroid.Tuner.MarkJavaObjects.GetTypesInModule(ModuleDefinition module)
at MonoDroid.Tuner.MarkJavaObjects.FindType(TypeDefinition type, String fullname)
at MonoDroid.Tuner.MarkJavaObjects.PreserveInvoker(TypeDefinition type)
at MonoDroid.Tuner.MarkJavaObjects.ProcessType(TypeDefinition type)
at Mono.Tuner.SubStepDispatcher.DispatchType(TypeDefinition type)
at Mono.Tuner.SubStepDispatcher.BrowseTypes(ICollection types)
at Mono.Tuner.SubStepDispatcher.BrowseTypes(ICollection types)
at Mono.Tuner.SubStepDispatcher.BrowseAssemblies(IEnumerable`1 assemblies)
at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
Done building project "OfficeTrack.Droid.csproj" -- FAILED.
Build FAILED.

---
#### Feedback Bot on 1/26/2022, 02:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment]
Jones Abramoff would you be able to attach an [MSBuild diagnostic log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Then we can look into this further, thanks!
