### ISSUE TITLE
Cannot locate symbol ANativeWindow_setBuffersGeometry

### ISSUE THREAD

**Issue by RobbeDecraemer** [xamarin/xamarin-android#6765]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.0.1

### Description

I've a xamarin android project where I want to include a library. This library has been compiled with the NDK 22.x and I'm targeting an API level of above 26 since it contains a reference to the method ANativeWindow_setBuffersGeometry from the NDK's NativeWindow API. The project itself is alsot at minimum level 26 and the emulator is at 30.

When using DllImport it says the library is not found, which can mean many things. So I tried `JavaSystem.LoadLibrary("mylib");` and with that the library is found but it throws that it cannot locate symbol ANativeWindow_setBuffersGeometry. It explains why DllImport wasn't working, but I can't find out why this symbol is not found. It should be part of the NDK.

### Steps to Reproduce

1. New Android App
2. Use a library that references ANativeWindow_setBuffersGeometry
3. Include the line `JavaSystem.LoadLibrary("lib");` in the Activity
4. Debug on emulator
5. The line from step 3 throws an error

### Did you find any workaround?

No, tested in Xamarin.Android and MAUI to see if there was any difference, same result.

### Relevant log output

```shell
Java.Lang.LinkageError: dlopen failed: cannot locate symbol "ANativeWindow_setBuffersGeometry" referenced by "/data/app/~~boilTbxCvrOjQMStV5eIxg==/demo.SampleApp-_wvDpbHiKm___Fd5Xy1KTA==/lib/x86/libwgpu.so"...
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <5105dea2ae7e4193abaa62333b528359>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <5105dea2ae7e4193abaa62333b528359>:0 
  at Java.Lang.JavaSystem.LoadLibrary (System.String libname) [0x0001f] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Java.Lang.JavaSystem.cs:457 
  at SampleApp.DemoActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00020] in D:\Projects\monodroid-samples\SanAngeles_NDK\SanAngeles_NDK\MainActivity.cs:67 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.Activity.cs:3057 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr,intptr)
  --- End of managed Java.Lang.LinkageError stack trace ---
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ANativeWindow_setBuffersGeometry" referenced by "/data/app/~~boilTbxCvrOjQMStV5eIxg==/demo.SampleApp-_wvDpbHiKm___Fd5Xy1KTA==/lib/x86/libwgpu.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at crc64ad5f528fd2cb43c0.DemoActivity.n_onCreate(Native Method)
	at crc64ad5f528fd2cb43c0.DemoActivity.onCreate(DemoActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by grendello** [comment]
@RobbeDecraemer this doesn't appear to be a Xamarin.Android issue, so we won't be able to fix it, but perhaps I can point you to a workaround/fix. The symbol that's not found lives in the `libnativewindow.so` shared library which is a system library in Android:

```shell
raven:/ $ ls -l /system/lib64/libnativewindow.so
-rw-r--r-- 1 root root 27664 2009-01-01 01:00 /system/lib64/libnativewindow.so
```

Firs thing you need to do is to check whether `libwgpu.so` references `libnativewindow.so`. If you have access to the source code, look for `-lnativewindow` in the build system. If you don't have sources for the library, extract it from the apk file and
use the `llvm-readelf` tool from the Android NDK like so:

```shell
$ llvm-readelf -a libwgpu.so > libwgpu.txt
```

And then look for a line which looks similar to:

```
 0x0000000000000001 (NEEDED)       Shared library: [libnativewindow.so]
```

If it's not there, then the native library wasn't built properly and it needs to have `-lnativewindow` added to its link command.  If the `NEEDED` record is there, then you can try loading `libnativewindow.so` before `libwgpu.so` using `JavaSystem.LoadLibrary` - this will make its symbols present in the process memory and `libwgpu.so` **should** be able to resolve them.

Hope it helps!

**Comment by RobbeDecraemer** [comment]
This was exactly what I was looking for, you fixed my problem thanks!
