### ISSUE TITLE
Using HttpClient in a Xamarin Android Release app crashes

### ISSUE THREAD

**Issue by eerhardt** [xamarin/xamarin-android#6895]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Maui main

### Description

I'm getting a crashing app when using HttpClient in a Release build. It appears that the `FromJniHandle` method is getting trimmed in `JavaList<T>`, causing the app to crash.

### Steps to Reproduce

1. `dotnet new android`
2. Write the following code in the MainActivity:

```C#
namespace XamarinAndroid;

[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : Activity
{
    protected override async void OnCreate(Bundle? savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        // Set our view from the "main" layout resource
        SetContentView(Resource.Layout.activity_main);

        HttpClient client = new HttpClient();
        client.BaseAddress = new Uri("https://www.bing.com");
        string results = await client.GetStringAsync("search?q=maui");


        AlertDialog.Builder dialog = new AlertDialog.Builder(this);
        var alert = dialog.Create();
        alert.SetTitle($"results Length: {results.Length}");

        alert.Show();
    }
}
```

3. Run the app in Release mode.

### Expected results

The app should work the same as it does in Debug mode.

### Actual results

The app crashes. See the below logcat output.

### Did you find any workaround?

You can manually preserve the method by adding a `<TrimmerRootDescriptor Include="ILLInk.Descriptors.xml" />` with contents:

```xml
<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Android.Runtime.JavaList`1">
      <method name="FromJniHandle" />
    </type>
  </assembly>
</linker>
```

### Relevant log output

```shell
04-05 11:28:40.105  9171  9171 D AndroidRuntime: Shutting down VM
04-05 11:28:40.105  9171  9171 E AndroidRuntime: FATAL EXCEPTION: main
04-05 11:28:40.105  9171  9171 E AndroidRuntime: Process: com.companyname.XamarinAndroid, PID: 9171
04-05 11:28:40.105  9171  9171 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, method
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at System.Delegate.CreateDelegate(Type , MethodInfo , Boolean )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at System.Delegate.CreateDelegate(Type , MethodInfo )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Interop.JavaConvert.GetJniHandleConverterForType(Type )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Interop.JavaConvert.GetJniHandleConverter(Type )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership , Boolean& )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Android.Runtime.JavaDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.IList`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Get(String )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Android.Runtime.JavaDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.IList`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(String )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Xamarin.Android.Net.AndroidMessageHandler.CopyHeaders(HttpURLConnection , HttpResponseMessage )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage , URL , HttpURLConnection , CancellationToken , RequestRedirectionState )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at XamarinAndroid.MainActivity.OnCreate(Bundle savedInstanceState)
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Lang.Thread.RunnableImplementor.Run()
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
04-05 11:28:40.105  9171  9171 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-05 11:28:40.105  9171  9171 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by grendello** [comment]
@eerhardt it might be related to https://github.com/xamarin/xamarin-android/pull/6891 but @jonathanpeppers is currently away, so it might be a few days before he can take a look

**Comment by eerhardt** [comment]
I was trying to reproduce https://github.com/dotnet/runtime/issues/67402 (which spawned the creation of #6891) without using Maui. Trying to narrow down what that problem is.

In trying to localize the repro, I noticed this extra issue. When using Maui the above JavaList method is preserved. But when just using plain Xamarin Android, it isn't causing this crash.

https://github.com/dotnet/runtime/issues/67402 is a crash in the Mono runtime, and appears to be related to Profiled AOT as well. This issue is just that JavaList.FromJniHandle isn't getting preserved correctly.

**Comment by jonathanpeppers** [comment]
I think this is what makes it work in Xamarin.Android:

https://github.com/xamarin/xamarin-android/blob/0ab3db079d43d47ad1bc522e28e65204542fea60/src/Xamarin.Android.Build.Tasks/Linker/PreserveLists/Mono.Android.xml#L28

Will look through and see if there is a better way than preserving the entire type.

**Comment by eerhardt** [comment]
The best way is to use `[DynamicDependency]`, if you can. I think you can add a few of them here:

https://github.com/xamarin/xamarin-android/blob/af2875138afada68a870cc803c3e8dcd2e85ff6f/src/Mono.Android/Java.Interop/JavaConvert.cs#L56-L92

You can add `[DynamicDependency]` to the `FromJniHandle` methods on `JavaDictionary<,>`, `JavaList<>`, and `JavaCollection<>`.

The other thought would be to try to add `[DynamicallyAccessedMembers]` to the `Type t` of that method. The trimmer _should_ be able to see that those 3 types are passed in to `GetJniHandleConverterForType`, but I'm not 100% sure. Also, using this route will mean all public methods on those 3 types will be preserved (which is maybe what you want anyway).
