### ISSUE TITLE
[net6] dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load"

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#7000]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Started with RC3

### Description

When building an app with `RunAOTCompilation` in release, the following error occurs:

```
05-13 10:29:00.693 28981 28981 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load" referenced by "/data/app/~~oM9XL6F3AUAWGQ9veMr7Hg==/com.nventive.uno.ui.demo.canary-YAeXR3Id7M4fikadiZaCgg==/lib/arm64/libmonodroid.so"...
```
Adding `<AndroidAotEnableLazyLoad>false</AndroidAotEnableLazyLoad>` does not seem to help.

### Steps to Reproduce

Build an vanilla android app using net6 and RC3 installed.

### Did you find any workaround?

No

### Relevant log output

```shell
05-13 11:30:03.931 10021 10021 I DOTNET  : JNI_OnLoad: JNI_OnLoad in pal_jni.c
05-13 11:30:03.933 10021 10021 D AndroidRuntime: Shutting down VM
05-13 11:30:03.933 10021 10021 E AndroidRuntime: FATAL EXCEPTION: main
05-13 11:30:03.933 10021 10021 E AndroidRuntime: Process: com.nventive.uno.ui.demo.canary, PID: 10021
05-13 11:30:03.933 10021 10021 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load" referenced by "/data/app/~~Uv2n9SrNm5Wr0vpkNHXoTw==/com.nventive.uno.ui.demo.canary-Kraib-u61GzU7uIyhmQNtw==/lib/arm64/libmonodroid.so"...
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:102)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7306)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6847)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread.access$1400(ActivityThread.java:238)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1925)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7724)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-13 11:30:03.933 10021 10021 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

========================================================

Installed workloads:

022-05-13T14:57:41.4770291Z Installing workload manifest microsoft.net.sdk.android version 32.0.300-rc.3.45…
2022-05-13T14:57:41.7357315Z Installing workload manifest microsoft.net.sdk.ios version 15.4.300-rc.3.83…
2022-05-13T14:57:42.0192970Z Installing workload manifest microsoft.net.sdk.maccatalyst version 15.4.300-rc.3.83…
2022-05-13T14:57:42.8317881Z Installing workload manifest microsoft.net.sdk.tvos version 15.4.300-rc.3.83…
2022-05-13T14:57:43.0745193Z Installing workload manifest microsoft.net.sdk.macos version 12.3.300-rc.3.83…
2022-05-13T14:57:43.3072473Z Installing workload manifest microsoft.net.workload.mono.toolchain version 6.0.4…
2022-05-13T14:57:43.6332372Z Installing workload manifest microsoft.net.workload.emscripten version 6.0.4…
2022-05-13T14:57:43.9404634Z Installing pack Microsoft.Android.Sdk version 32.0.300-rc.3.45...
2022-05-13T14:57:50.5155552Z Writing workload pack installation record for Microsoft.Android.Sdk version 32.0.300-rc.3.45...
2022-05-13T14:57:50.5433476Z Installing pack Microsoft.Android.Ref.31 version 32.0.300-rc.3.45...
2022-05-13T14:57:51.5412314Z Writing workload pack installation record for Microsoft.Android.Ref.31 version 32.0.300-rc.3.45...
2022-05-13T14:57:51.5426346Z Installing pack Microsoft.Android.Ref.32 version 32.0.300-rc.3.45...
2022-05-13T14:57:52.8278831Z Writing workload pack installation record for Microsoft.Android.Ref.32 version 32.0.300-rc.3.45...
2022-05-13T14:57:52.8318198Z Installing pack Microsoft.Android.Runtime.32.android-arm version 32.0.300-rc.3.45...
2022-05-13T14:57:54.0332197Z Writing workload pack installation record for Microsoft.Android.Runtime.32.android-arm version 32.0.300-rc.3.45...
2022-05-13T14:57:54.0351284Z Installing pack Microsoft.Android.Runtime.32.android-arm64 version 32.0.300-rc.3.45...
2022-05-13T14:57:54.7081798Z Writing workload pack installation record for Microsoft.Android.Runtime.32.android-arm64 version 32.0.300-rc.3.45...
2022-05-13T14:57:54.7093713Z Installing pack Microsoft.Android.Runtime.32.android-x86 version 32.0.300-rc.3.45...
2022-05-13T14:57:56.1618149Z Writing workload pack installation record for Microsoft.Android.Runtime.32.android-x86 version 32.0.300-rc.3.45...
2022-05-13T14:57:56.1632626Z Installing pack Microsoft.Android.Runtime.32.android-x64 version 32.0.300-rc.3.45...
2022-05-13T14:57:57.2425553Z Writing workload pack installation record for Microsoft.Android.Runtime.32.android-x64 version 32.0.300-rc.3.45...
2022-05-13T14:57:57.2464166Z Installing pack Microsoft.Android.Templates version 32.0.300-rc.3.45...
2022-05-13T14:57:57.4407474Z Writing workload pack installation record for Microsoft.Android.Templates version 32.0.300-rc.3.45...
2022-05-13T14:57:57.4421164Z Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm version 6.0.4...
2022-05-13T14:58:03.0769880Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-arm version 6.0.4...
2022-05-13T14:58:03.0786816Z Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm64 version 6.0.4...
2022-05-13T14:58:08.2241280Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-arm64 version 6.0.4...
2022-05-13T14:58:08.2261460Z Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x64 version 6.0.4...
2022-05-13T14:58:14.1185430Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-x64 version 6.0.4...
2022-05-13T14:58:14.1196920Z Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x86 version 6.0.4...
2022-05-13T14:58:18.7008104Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-x86 version 6.0.4...
2022-05-13T14:58:18.7052681Z Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.4...
2022-05-13T14:58:19.0212518Z Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.4...
2022-05-13T14:58:19.0225400Z Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 6.0.4...
2022-05-13T14:58:19.9467311Z Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk version 6.0.4...
2022-05-13T14:58:19.9487682Z Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.android-x86 version 6.0.4...
2022-05-13T14:58:21.4081060Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-x86 version 6.0.4...
2022-05-13T14:58:21.4111296Z Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.android-x64 version 6.0.4...
2022-05-13T14:58:22.8063828Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-x64 version 6.0.4...
2022-05-13T14:58:22.8086955Z Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm version 6.0.4...
2022-05-13T14:58:24.4938843Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm version 6.0.4...
2022-05-13T14:58:24.4950456Z Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm64 version 6.0.4...
2022-05-13T14:58:25.6677860Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm64 version 6.0.4...
2022-05-13T14:58:25.6705392Z Installing pack Microsoft.iOS.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:58:29.1823708Z Writing workload pack installation record for Microsoft.iOS.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:58:29.1870854Z Installing pack Microsoft.iOS.Windows.Sdk.Aliased version 15.4.300-rc.3.83...
2022-05-13T14:58:33.5129733Z Writing workload pack installation record for Microsoft.iOS.Windows.Sdk.Aliased version 15.4.300-rc.3.83...
2022-05-13T14:58:33.5137124Z Installing pack Microsoft.iOS.Ref version 15.4.300-rc.3.83...
2022-05-13T14:58:33.8664312Z Writing workload pack installation record for Microsoft.iOS.Ref version 15.4.300-rc.3.83...
2022-05-13T14:58:33.8680417Z Installing pack Microsoft.iOS.Runtime.ios-arm version 15.4.300-rc.3.83...
2022-05-13T14:58:34.7672948Z Writing workload pack installation record for Microsoft.iOS.Runtime.ios-arm version 15.4.300-rc.3.83...
2022-05-13T14:58:34.7686783Z Installing pack Microsoft.iOS.Runtime.ios-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:58:35.5800839Z Writing workload pack installation record for Microsoft.iOS.Runtime.ios-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:58:36.9631590Z Installing pack Microsoft.iOS.Runtime.iossimulator-x86 version 15.4.300-rc.3.83...
2022-05-13T14:58:37.8077671Z Writing workload pack installation record for Microsoft.iOS.Runtime.iossimulator-x86 version 15.4.300-rc.3.83...
2022-05-13T14:58:37.8093647Z Installing pack Microsoft.iOS.Runtime.iossimulator-x64 version 15.4.300-rc.3.83...
2022-05-13T14:58:38.8020778Z Writing workload pack installation record for Microsoft.iOS.Runtime.iossimulator-x64 version 15.4.300-rc.3.83...
2022-05-13T14:58:38.8039889Z Installing pack Microsoft.iOS.Runtime.iossimulator-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:58:40.1686746Z Writing workload pack installation record for Microsoft.iOS.Runtime.iossimulator-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:58:40.1785430Z Installing pack Microsoft.iOS.Templates version 15.4.300-rc.3.83...
2022-05-13T14:58:40.3806802Z Writing workload pack installation record for Microsoft.iOS.Templates version 15.4.300-rc.3.83...
2022-05-13T14:58:40.3814357Z Installing pack Microsoft.NETCore.App.Runtime.Mono.ios-arm version 6.0.4...
2022-05-13T14:58:46.1849582Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.ios-arm version 6.0.4...
2022-05-13T14:58:46.1865185Z Installing pack Microsoft.NETCore.App.Runtime.Mono.ios-arm64 version 6.0.4...
2022-05-13T14:58:50.9222409Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.ios-arm64 version 6.0.4...
2022-05-13T14:58:50.9238366Z Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64 version 6.0.4...
2022-05-13T14:58:55.4768556Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64 version 6.0.4...
2022-05-13T14:58:55.4784260Z Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64 version 6.0.4...
2022-05-13T14:59:00.6193222Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64 version 6.0.4...
2022-05-13T14:59:00.6231368Z Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86 version 6.0.4...
2022-05-13T14:59:05.6479910Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86 version 6.0.4...
2022-05-13T14:59:05.6511132Z Installing pack Microsoft.MacCatalyst.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:59:07.2653332Z Writing workload pack installation record for Microsoft.MacCatalyst.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:59:07.2677816Z Installing pack Microsoft.MacCatalyst.Ref version 15.4.300-rc.3.83...
2022-05-13T14:59:07.5939848Z Writing workload pack installation record for Microsoft.MacCatalyst.Ref version 15.4.300-rc.3.83...
2022-05-13T14:59:07.6030724Z Installing pack Microsoft.MacCatalyst.Runtime.maccatalyst-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:08.3598565Z Writing workload pack installation record for Microsoft.MacCatalyst.Runtime.maccatalyst-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:08.3618134Z Installing pack Microsoft.MacCatalyst.Runtime.maccatalyst-x64 version 15.4.300-rc.3.83...
2022-05-13T14:59:09.4749668Z Writing workload pack installation record for Microsoft.MacCatalyst.Runtime.maccatalyst-x64 version 15.4.300-rc.3.83...
2022-05-13T14:59:09.4798435Z Installing pack Microsoft.MacCatalyst.Templates version 15.4.300-rc.3.83...
2022-05-13T14:59:09.6626921Z Writing workload pack installation record for Microsoft.MacCatalyst.Templates version 15.4.300-rc.3.83...
2022-05-13T14:59:09.6633573Z Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64 version 6.0.4...
2022-05-13T14:59:14.5534244Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64 version 6.0.4...
2022-05-13T14:59:14.5549140Z Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64 version 6.0.4...
2022-05-13T14:59:19.2976520Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64 version 6.0.4...
2022-05-13T14:59:19.3012933Z Installing pack Microsoft.tvOS.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:59:21.5730814Z Writing workload pack installation record for Microsoft.tvOS.Sdk version 15.4.300-rc.3.83...
2022-05-13T14:59:21.5754612Z Installing pack Microsoft.tvOS.Ref version 15.4.300-rc.3.83...
2022-05-13T14:59:22.0476194Z Writing workload pack installation record for Microsoft.tvOS.Ref version 15.4.300-rc.3.83...
2022-05-13T14:59:22.0486656Z Installing pack Microsoft.tvOS.Runtime.tvos-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:22.8174416Z Writing workload pack installation record for Microsoft.tvOS.Runtime.tvos-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:22.8188126Z Installing pack Microsoft.tvOS.Runtime.tvossimulator-x64 version 15.4.300-rc.3.83...
2022-05-13T14:59:23.8156328Z Writing workload pack installation record for Microsoft.tvOS.Runtime.tvossimulator-x64 version 15.4.300-rc.3.83...
2022-05-13T14:59:23.8370191Z Installing pack Microsoft.tvOS.Runtime.tvossimulator-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:25.2672678Z Writing workload pack installation record for Microsoft.tvOS.Runtime.tvossimulator-arm64 version 15.4.300-rc.3.83...
2022-05-13T14:59:25.2718935Z Installing pack Microsoft.tvOS.Templates version 15.4.300-rc.3.83...
2022-05-13T14:59:25.4860887Z Writing workload pack installation record for Microsoft.tvOS.Templates version 15.4.300-rc.3.83...
2022-05-13T14:59:25.4967265Z Installing pack Microsoft.NETCore.App.Runtime.Mono.tvos-arm64 version 6.0.4...
2022-05-13T14:59:33.3985556Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.tvos-arm64 version 6.0.4...
2022-05-13T14:59:33.3992724Z Installing pack Microsoft.NETCore.App.Runtime.Mono.tvossimulator-arm64 version 6.0.4...
2022-05-13T14:59:41.8773686Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.tvossimulator-arm64 version 6.0.4...
2022-05-13T14:59:41.8787119Z Installing pack Microsoft.NETCore.App.Runtime.Mono.tvossimulator-x64 version 6.0.4...
2022-05-13T14:59:49.9467509Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.tvossimulator-x64 version 6.0.4...
2022-05-13T14:59:49.9477692Z Installing pack Microsoft.macOS.Sdk version 12.3.300-rc.3.83...
2022-05-13T14:59:50.9597348Z Writing workload pack installation record for Microsoft.macOS.Sdk version 12.3.300-rc.3.83...
2022-05-13T14:59:50.9613376Z Installing pack Microsoft.macOS.Ref version 12.3.300-rc.3.83...
2022-05-13T14:59:51.3699256Z Writing workload pack installation record for Microsoft.macOS.Ref version 12.3.300-rc.3.83...
2022-05-13T14:59:51.3714451Z Installing pack Microsoft.macOS.Runtime.osx-arm64 version 12.3.300-rc.3.83...
2022-05-13T14:59:52.3054024Z Writing workload pack installation record for Microsoft.macOS.Runtime.osx-arm64 version 12.3.300-rc.3.83...
2022-05-13T14:59:52.3066391Z Installing pack Microsoft.macOS.Runtime.osx-x64 version 12.3.300-rc.3.83...
2022-05-13T14:59:53.2120172Z Writing workload pack installation record for Microsoft.macOS.Runtime.osx-x64 version 12.3.300-rc.3.83...
2022-05-13T14:59:53.2126936Z Installing pack Microsoft.macOS.Templates version 12.3.300-rc.3.83...
2022-05-13T14:59:53.6964428Z Writing workload pack installation record for Microsoft.macOS.Templates version 12.3.300-rc.3.83...
2022-05-13T14:59:53.6975384Z Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.4...
2022-05-13T14:59:55.0356531Z Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.4...
2022-05-13T14:59:55.0370926Z Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 6.0.4...
2022-05-13T15:00:00.4200231Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 6.0.4...
2022-05-13T15:00:00.4209516Z Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 6.0.4...
2022-05-13T15:00:00.9415073Z Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 6.0.4...
2022-05-13T15:00:00.9488731Z Installing pack Microsoft.NET.Runtime.Emscripten.Node version 6.0.4...
2022-05-13T15:00:02.1729328Z Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Node version 6.0.4...
2022-05-13T15:00:02.2771259Z Installing pack Microsoft.NET.Runtime.Emscripten.Python version 6.0.4...
2022-05-13T15:00:13.1598313Z Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Python version 6.0.4...
2022-05-13T15:00:13.1614804Z Installing pack Microsoft.NET.Runtime.Emscripten.Sdk version 6.0.4...
2022-05-13T15:01:13.8052207Z Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Sdk version 6.0.4...
2022-05-13T15:01:14.0609975Z Garbage collecting for SDK feature band(s) 6.0.300...
2022-05-13T15:01:14.1379871Z 
2022-05-13T15:01:14.1386538Z Successfully installed workload(s) android ios maccatalyst tvos macos wasm-tools.
```

**Comment by jonathanpeppers** [comment]
I would first verify you have the 6.0.5 version of these packs:

    C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.android-*\6.0.5

If you do, had you installed nightly builds of MAUI using `dotnet workload` commands? You might need to delete those folders and install the workload again.

**Comment by jeromelaban** [comment]
Thanks, the hint for 6.0.5 helped troubleshoot and AOT is now working properly. 

The issue here is that the root of everything pulling those 6.0.5 sub-packages is `"microsoft.net.workload.mono.toolchain": "6.0.5",` in the rollback file. This was previously failing as part of the 6.0.300 preview releases, but this is a critical pieced to pulling everything to the right versions.
