### ISSUE TITLE
App is failing after resign

### ISSUE THREAD

**Issue by ili** [xamarin/xamarin-android#7007]
### Android application type

net6.0-android, +Xamarin.Forms

### Affected platform version

NET 6.0.200

### Description

The situation is: i do have `net6-android` app, i do need to publish it in private vendor's app market, all applications in this market should be signed with vendor's keys... so i do build APK, send it to the vendor, vendor do resign the apk with his private key and sends me it back. 
The problem is - original app runs OK, but resigned - crashes on start.

In adb log i can see:

```
F/monodroid(31182): ../../../jni/embedded-assemblies.hh:161 (ensure_valid_assembly_stores): Invalid or incomplete assembly store data
```

looks lite smth is wrong with `apk/assemblies` folder, but it is the same as in original apk...

So i'm looking for your advice if and how can i try to fix the problem....

### Steps to Reproduce

no steps, just can send you apks if it can help

### Relevant log output

```shell
I/ActivityManager( 1595): Start proc 31182:ru.limesoft.mobilecashdesk/u0a159 for activity ru.limesoft.mobilecashdesk/crc64faaff5a6b9429b14.SplashActivity
W/linker  (31182): libmonosgen-2.0.so: unused DT entry: type 0x6ffffef5 arg 0x10530
W/linker  (31182): libmonosgen-2.0.so: unused DT entry: type 0x6ffffffe arg 0x165a8
W/linker  (31182): libmonosgen-2.0.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker  (31182): libxamarin-app.so: unused DT entry: type 0x6ffffef5 arg 0x170
W/linker  (31182): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6ffffef5 arg 0x2754
W/linker  (31182): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6ffffffe arg 0x34e4
W/linker  (31182): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6fffffff arg 0x2
I/DOTNET  (31182): JNI_OnLoad: JNI_OnLoad in pal_jni.c
I/DOTNET  (31182): GetOptionalMethod: optional method setApplicationProtocols ([Ljava/lang/String;)V was not found
I/DOTNET  (31182): GetOptionalMethod: optional method getRevocationChecker ()Ljava/security/cert/CertPathChecker; was not found
I/DOTNET  (31182): GetOptionalMethod: optional method getReason ()Ljava/security/cert/CertPathValidatorException$Reason; was not found
D/DOTNET  (31182): GetOptionalClassGRef: optional class java/security/cert/CertPathValidatorException$BasicReason was not found
D/DOTNET  (31182): GetOptionalClassGRef: optional class java/security/cert/PKIXReason was not found
D/DOTNET  (31182): GetOptionalClassGRef: optional class javax/net/ssl/SNIHostName was not found
I/DOTNET  (31182): GetOptionalMethod: optional method getApplicationProtocol ()Ljava/lang/String; was not found
W/linker  (31182): libmonodroid.so: unused DT entry: type 0x6ffffef5 arg 0x1004
W/linker  (31182): libmonodroid.so: unused DT entry: type 0x6ffffffe arg 0xfa4
W/linker  (31182): libmonodroid.so: unused DT entry: type 0x6fffffff arg 0x3
W/art     (31182): Attempt to remove local handle scope entry from IRT, ignoring
F/monodroid(31182): ../../../jni/embedded-assemblies.hh:161 (ensure_valid_assembly_stores): Invalid or incomplete assembly store data
F/libc    (31182): Fatal signal 6 (SIGABRT), code -6 in tid 31182 (.mobilecashdesk)
I/libc    (31182): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
I/Zygote  (  277): Process 31182 exited due to signal (6)
I/ActivityManager( 1595): Process ru.limesoft.mobilecashdesk (pid 31182) has died
I/ActivityManager( 1595): Start proc 31201:ru.limesoft.mobilecashdesk/u0a159 for activity ru.limesoft.mobilecashdesk/crc64faaff5a6b9429b14.SplashActivity
I/SurfaceFlinger(  231): FPS: 52
W/linker  (31201): libmonosgen-2.0.so: unused DT entry: type 0x6ffffef5 arg 0x10530
W/linker  (31201): libmonosgen-2.0.so: unused DT entry: type 0x6ffffffe arg 0x165a8
W/linker  (31201): libmonosgen-2.0.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker  (31201): libxamarin-app.so: unused DT entry: type 0x6ffffef5 arg 0x170
W/linker  (31201): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6ffffef5 arg 0x2754
W/linker  (31201): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6ffffffe arg 0x34e4
W/linker  (31201): libSystem.Security.Cryptography.Native.Android.so: unused DT entry: type 0x6fffffff arg 0x2
I/DOTNET  (31201): JNI_OnLoad: JNI_OnLoad in pal_jni.c
I/DOTNET  (31201): GetOptionalMethod: optional method setApplicationProtocols ([Ljava/lang/String;)V was not found
I/DOTNET  (31201): GetOptionalMethod: optional method getRevocationChecker ()Ljava/security/cert/CertPathChecker; was not found
I/DOTNET  (31201): GetOptionalMethod: optional method getReason ()Ljava/security/cert/CertPathValidatorException$Reason; was not found
D/DOTNET  (31201): GetOptionalClassGRef: optional class java/security/cert/CertPathValidatorException$BasicReason was not found
D/DOTNET  (31201): GetOptionalClassGRef: optional class java/security/cert/PKIXReason was not found
D/DOTNET  (31201): GetOptionalClassGRef: optional class javax/net/ssl/SNIHostName was not found
I/DOTNET  (31201): GetOptionalMethod: optional method getApplicationProtocol ()Ljava/lang/String; was not found
W/linker  (31201): libmonodroid.so: unused DT entry: type 0x6ffffef5 arg 0x1004
W/linker  (31201): libmonodroid.so: unused DT entry: type 0x6ffffffe arg 0xfa4
W/linker  (31201): libmonodroid.so: unused DT entry: type 0x6fffffff arg 0x3
W/art     (31201): Attempt to remove local handle scope entry from IRT, ignoring
F/monodroid(31201): ../../../jni/embedded-assemblies.hh:161 (ensure_valid_assembly_stores): Invalid or incomplete assembly store data
F/libc    (31201): Fatal signal 6 (SIGABRT), code -6 in tid 31201 (.mobilecashdesk)
I/libc    (31201): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
I/Zygote  (  277): Process 31201 exited due to signal (6)
I/ActivityManager( 1595): Process ru.limesoft.mobilecashdesk (pid 31201) has died
W/ActivityManager( 1595): Force removing ActivityRecord{34be56b2 u0 ru.limesoft.mobilecashdesk/crc64faaff5a6b9429b14.SplashActivity t87}: app died, no saved state
W/ResourceType( 2930): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 2930): Failure retrieving resources for com.android.providers.downloads.ui: Resource ID #0x0
W/WindowManager( 1595): Failed looking up window
W/WindowManager( 1595): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@28043898 does not exist
W/WindowManager( 1595):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8837)
W/WindowManager( 1595):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8828)
W/WindowManager( 1595):         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2613)
W/WindowManager( 1595):         at com.android.server.wm.Session.remove(Session.java:187)
W/WindowManager( 1595):         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3085)
W/WindowManager( 1595):         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6025)
W/WindowManager( 1595):         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3406)
W/WindowManager( 1595):         at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager( 1595):         at android.os.Looper.loop(Looper.java:135)
W/WindowManager( 1595):         at android.os.HandlerThread.run(HandlerThread.java:61)
W/WindowManager( 1595):         at com.android.server.ServiceThread.run(ServiceThread.java:46)
V/WindowManager( 1595): Relayout Window{255077c1 u0 com.android.documentsui/com.android.documentsui.DocumentsActivity}: viewVisibility=4 req=720x1280 WM.LayoutParams{(0,0)(fillxfill) sim=#120 ty=1 fl=#81810100 wanim=0x1030380 vsysui=0x600 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2}
V/WindowManager( 1595): Relayout Window{255077c1 u0 com.android.documentsui/com.android.documentsui.DocumentsActivity}: viewVisibility=0 req=720x1280 WM.LayoutParams{(0,0)(fillxfill) sim=#110 ty=1 fl=#81810100 wanim=0x1030380 vsysui=0x600 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2}
I/Adreno-EGL(10209): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.4_RB1__release_AU (I385e983e35)
I/Adreno-EGL(10209): OpenGL ES Shader Compiler Version: E031.25.03.04
I/Adreno-EGL(10209): Build Date: 02/13/16 Sat
I/Adreno-EGL(10209): Local Branch: mybranch18237875
I/Adreno-EGL(10209): Remote Branch: quic/LA.BR.1.2.4_rb1.36
I/Adreno-EGL(10209): Local Patches: NONE
I/Adreno-EGL(10209): Reconstruct Branch: NOTHING
I/OpenGLRenderer(10209): Initialized EGL, version 1.4
I/Timeline(10209): Timeline: Activity_idle id: android.os.BinderProxy@d424605 time:439765776
I/Timeline( 1595): Timeline: Activity_windows_visible id: ActivityRecord{23c164bc u0 com.android.documentsui/.DocumentsActivity t22} time:439766160
V/WLAN_PSA(  267): NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
V/WLAN_PSA(  267): NL MSG, PID: 267
I/SurfaceFlinger(  231): FPS: 42
```

**Comment by grendello** [comment]
@ili do you use any apk optimizing utilities/repackers? None of the entries in the `lib` and `assemblies` folders inside the apk must be compressed. You can check how the entry is stored in the archive by issuing this command (on Unix, on Windows you can probably open the apk in the Explorer and right-click on the entries to learn what is their compression method):

```sh
$ unzip -lv your.apk | grep assemblies
  555508  Stored   555508   0% 2022-05-17 15:42 bb388dea  assemblies/assemblies.blob
  546864  Stored   546864   0% 2022-05-17 15:42 7ba3b0ae  assemblies/assemblies.arm64_v8a.blob
  551939  Stored   551939   0% 2022-05-17 15:42 fa265533  assemblies/assemblies.x86_64.blob
  540882  Stored   540882   0% 2022-05-17 15:42 cc93a2b5  assemblies/assemblies.armeabi_v7a.blob
  540954  Stored   540954   0% 2022-05-17 15:42 6c540f1e  assemblies/assemblies.x86.blob
    1326  Defl:X      585  56% 2022-05-17 15:42 879e3c49  assemblies/assemblies.manifest
    1116  Stored     1116   0% 2022-05-17 15:42 888ef848  assemblies/rc.bin
```

All the `.blob` entries must have `Stored` as their compression method.  

If you use Android Gradle Plugin, then the problem you're seeing might be the same as in [this issue](https://github.com/xamarin/xamarin-android/issues/6838#issuecomment-1110816027).

**Comment by ili** [comment]
@grendello thanks for your answer

l'v checked original apk and resigned one - in the both cases `assemblies/*.blob` are `Stored`, `lib/**/*.so` - `Deflated`

Some my invistigations:

I'v compared both apks and see changes only in `META-INF` folder, after resign:

-  all files from this folder are removed (excepting `MANIFEST.MF`)
-  `MANIFEST.MF` is changed
- `UROVOKEY.SF` & `UROVOKEY.RSA`

I'v tried to restore missed files & zip fiolder into apk. But in manually reassembled apk  `assemblies/*.blob` are `Deflated`. Can you please advice me a tool to proper archive apk? :)

**Comment by grendello** [comment]
You can modify apk files with the standard `zip` utility. If you pass `-0` to it, it will store the files you're adding. However, the APK archives must also be properly aligned, using the `zipalign` tool, or otherwise they won't be installable on Android devices.

Before you set out to do the above, can you try the following with the APK that breaks for you:

1. remove the application from your device/emulator, so that no trace of it is left.
2. install the app as usual, but do not run it yet
3. issue the following commands from the terminal, with your device connected
```sh
$ adb shell setprop debug.mono.log default,assembly
$ adb logcat -G 16M
$ adb logcat -c
```
4. Start the application and, after it crashes, dump logcat with `adb logcat -d > log.txt` and attach the resulting file to this issue.

Hopefully this will reveal more information to help us find the issue.

**Comment by ili** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/8714007/log.txt)

Here it is, you can find app start by searching `ru.limesoft.mobilecashdesk`

It looks like problem is here:

```
D/monodroid-assembly( 8791): Looking for assembly stores in APK (common: '/assemblies.blob'; arch-specific: '/assemblies.armeabi_v7a.blob')
I/monodroid-assembly( 8791):                        mmap_start: 0x9f319000  mmap_end: 0xa4cc8ff4  mmap_len:     23511037  file_start: 0x9f31977c  file_end: 0xa4cc7980  file_len:     23509121      apk descriptor: 17  file: assemblies/assemblies.blob
F/monodroid-assembly( 8791): Assembly 'assemblies/assemblies.armeabi_v7a.blob' is located at bad offset 29687873 within the .apk
F/monodroid-assembly( 8791): You MUST run `zipalign` on base.apk
```

I'v used [zipalign](https://developer.android.com/studio/command-line/zipalign) on broken akp and that saves!

Thanks a lot for your help, it is invaluable!
