### ISSUE TITLE
Exception in SslStream.AuthenticateAsClient in net6.0-android project, works in Xamarin.Android

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-android#7119]
### Android application type

Android for .NET (net6.0-android, etc.)

Moving issue from MAUI 
https://github.com/dotnet/maui/issues/8224

### Description

Was migrating a Xamarin.Android project to .NET6.0-Android. I am experiencing the following exception when connecting to my server using custom certificates.

    "Authentication failed, see inner exception." 
       at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
       at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
       at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
       at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
       at AndroidApp1.MainActivity.OnCreate(Bundle savedInstanceState) in 
    C:\Users\Alex\source\repos\AndroidApp1\AndroidApp1\MainActivity.cs:line 23
InnerException:

     Exception of type 'Interop+AndroidCrypto+SslException' was thrown.

There are no other details in the exception or logs provided as to why authentication failed.

### Steps to Reproduce

I was able to replicate the issue in a brand new .NET6.0-Android app with the following sample client side code. Please note this exact same code snippet works in a brand new Xamarin.Android project on the exact same device. So it should not be a certificate import or device issue. The server is accepting TLS 1.2 and higher protocols.

            protected override void OnCreate(Bundle savedInstanceState)
		{
			base.OnCreate(savedInstanceState);
			SetContentView(Resource.Layout.activity_main);

			string hostname = "work";
			int port = 5280;

			var tcpClient = new TcpClient();
			IAsyncResult result = tcpClient.BeginConnect(hostname, port, null, null);
			var connected = result.AsyncWaitHandle.WaitOne(2000, true);
			if (connected)
			{
				tcpClient.EndConnect(result);
				var stream = new SslStream(tcpClient.GetStream(), false, ValidateServerCertificate, null);
				try
				{
					stream.AuthenticateAsClient(hostname);

					Console.WriteLine("Xamarin.Android Executes Here");
				}
				catch (Exception ex)
				{
					Console.WriteLine(".NET6.0-Android Executes Here");
				}
			}
		}

		private bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
		{
			return true;
		}

I have tried specifying the ssl protocols on the client and other authentication options with no change in result. I have also tried playing around with HttpClient Implementation setting to make sure it matches the Xamarin.Android project. Again no luck.

![image](https://user-images.githubusercontent.com/53029348/174948270-60739fb4-7633-40d5-a318-d2640da88d19.png)

Visual Studio 17.2.3
dotnet --version
6.0.300

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, 11

**Comment by PureWeen** [comment]
@AlexNik4 moving your issue here.

**Comment by akoeplinger** [comment]
@simonrozsival would you mind taking a look?

**Comment by simonrozsival** [comment]
@akoeplinger yeah, I'll look into it

**Comment by simonrozsival** [comment]
I can reproduce the problem on my Samsung phone (Android 12.0, API 31) when I set the `hostname` to either `self-signed.badssl.com` or `expired.badssl.com`. The app prints the following output in logcat:

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
   at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
   at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
   at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
   at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
   at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
   at com.android.org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:237)
   at crc648fb9cbf0486d8864.MainActivity.n_onCreate(Native Method)
   at crc648fb9cbf0486d8864.MainActivity.onCreate(MainActivity.java:37)
   at android.app.Activity.performCreate(Activity.java:8290)
   at android.app.Activity.performCreate(Activity.java:8270)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:226)
   at android.os.Looper.loop(Looper.java:313)
   at android.app.ActivityThread.main(ActivityThread.java:8663)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:672)
   at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
   at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:368)
   at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
   at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:106)
   at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
   at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
   at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
   at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
   at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
   at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1115)
   at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1087)
   ... 22 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   ... 36 more
```

The same piece of code works correctly against servers with trusted certificates.

The `ValidateServerCertificate` callback is never called because we do not pass it to Java where all the certificate validation happens. We would need to wrap it in a custom `TrustManager` in the AndroidCrypto layer and pass it to the `SSLContext` at initialization similarly to what we do in Xamarin.Android. Therefore, If I understand it correctly, it's currently impossible to bypass certificate validation in `SslStream` with a custom callback on Android at the moment.

**Comment by simonrozsival** [comment]
@AlexNik4 As a workaround you should add an Android-specific [Network security configuration](https://developer.android.com/training/articles/security-config) file and include your self-signed certificate.

**Comment by AlexNik4** [comment]
@simonrozsival Thanks for looking into the issue. Appreciate the heads up about a potential workaround, but it will not help us. In our feature, any customer is able to use their own self signed certificates. It is not something we can configure within our app during development.

**Comment by simonrozsival** [comment]
@AlexNik4 I see. Unfortunately, you'll probably have to ask the user to install the certificate system through Settings then (since even the `KeyChain.CreateInstallIntent` API doesn't work since Android 11). Otherwise, you could also write platform specific code using Android's SSLContext class with a custom TrustManager if that's an option for you.
