### ISSUE TITLE
Cannot construct class that implements AudioManager.IOnModeChangedListener

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-android#7148]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2022

### Description

If you try to construct the following class you get an unhandled exception in the JNI code:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]   at Android.Runtime.JNINativeWrapper._unhandled_exception (System.Exception e) [0x0000e] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12 
[mono-rt]   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLLL_V (_JniMarshal_PPLLLL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0, System.IntPtr p1, System.IntPtr p2, System.IntPtr p3) [0x00023] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:331 
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLLL_V(intptr,intptr,intptr,intptr,intptr,intptr)
```

```
public class AudioModeChangeListener : Java.Lang.Object, AudioManager.IOnModeChangedListener
{
    public void OnModeChanged(int mode)
    {
    }
}
```

### Steps to Reproduce

1. add a class with the code from the Description
2. Try to construct that class in a Xamarn.Android project
-> exception occurs

### Did you find any workaround?

no

**Comment by trampster** [comment]
By putting the code in a try catch I managed to get a much better exception:

```
Java.Lang.ClassNotFoundException: crc64befbf5bb285b619d.AudioModeChangeListener ---> Java.Lang.NoClassDefFoundError: Failed resolution of: Landroid/media/AudioManager$OnModeChangedListener; ---> Java.Lang.ClassNotFoundException: Didn't find class "android.media.AudioManager$OnModeChangedListener" on path: DexPathList[[zip file "/data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/lib/arm64, /data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x0015a] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.Types.cs:88 
  at Java.Interop.JniType..ctor (System.String classname) [0x00006] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:37 
  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x00058] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:27 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:77 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:107 
  at Java.Lang.Object..ctor () [0x0001f] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Java.Lang.Object.cs:27 
  at Pttox.Forms.Droid.Services.AudioModeChangeListener..ctor () <0x7498816b98 + 0x0003b> in <73796bbfb1da4ad8878d803d87b133e5>:0 
  at Pttox.Forms.Droid.Services.AndroidAudioService.<Start>b__18_0 () [0x00074] in C:\Work\hydra-src\apps\Xamarin-PTToX\src\Pttox.Forms.Android\Services\AndroidAudioService.cs:137 
  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: crc64befbf5bb285b619d.AudioModeChangeListener
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/media/AudioManager$OnModeChangedListener;
	... 9 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.media.AudioManager$OnModeChangedListener" on path: DexPathList[[zip file "/data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/lib/arm64, /data/app/com.taitradio.unified.pttox-W05uEng4WfSZ_DzHCwZDDg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more
```

**Comment by trampster** [comment]
Just realised this is because that API was only added in API 31 and I was testing on an Android 10 device.

I'm not sure why the exception stack trace gets destory if I don't catch it myself. I'm guessing it's some issue with the way android/xamarin handled unhandled exceptions.
