### ISSUE TITLE
InvalidProgramException calling classic Xamarin.Android dll

### ISSUE THREAD

**Issue by JRosanowski** [xamarin/xamarin-android#7271]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.3

### Description

We have a classic Xamarin.Android class library provided by a third party that calls into a dynamic Android .so (the dll may have been created with swig but I'm not 100% sure about that). When using it with .Net Maui or an Android .Net 6 application we get an InvalidProgramException.  Should we expect this dll to work or do Android .Net 6 apps require Android .Net 6 class libraries?

### Steps to Reproduce

The code is proprietary so I can't provide a sample app easily.

### Did you find any workaround?

No work-arounds.

**Comment by grendello** [comment]
@JRosanowski can you please attach the full stack trace of the crash you see? Ideally, a logcat output produced with the following commands would be great:

```shell
$ adb shell setprop debug.mono.log default,assembly
$ adb logcat -G 16M
$ adb logcat -c
# Run the application at this point
$ adb logcat -d > log.txt
```

**Comment by JRosanowski** [comment]
The app is called AndroidApp1
Thanks.
[log.txt](https://github.com/xamarin/xamarin-android/files/9354984/log.txt)

**Comment by jonpryor** [comment]
Relevant log file output:

```
08-17 10:02:47.756  7254  7254 I MonoDroid: UNHANDLED EXCEPTION:
08-17 10:02:47.773  7254  7254 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
08-17 10:02:47.773  7254  7254 I MonoDroid: 
08-17 10:02:47.773  7254  7254 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
08-17 10:02:47.773  7254  7254 I MonoDroid: android.runtime.JavaProxyThrowable: System.InvalidProgramException
08-17 10:02:47.773  7254  7254 I MonoDroid:    at Trimble.LicensingV2.Implementation.Licensing..ctor(String storagePath, String serialNumber)
08-17 10:02:47.773  7254  7254 I MonoDroid:    at Trimble.Licensing.LicensingFactory.CreateV2Licensing(Context context)
08-17 10:02:47.773  7254  7254 I MonoDroid:    at AndroidApp1.MainActivity.OnCreate(Bundle savedInstanceState)
08-17 10:02:47.773  7254  7254 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
08-17 10:02:47.773  7254  7254 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at crc64a6e0c00971f6cd91.MainActivity.n_onCreate(Native Method)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at crc64a6e0c00971f6cd91.MainActivity.onCreate(MainActivity.java:29)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:8290)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:8270)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.os.Looper.loopOnce(Looper.java:226)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.os.Looper.loop(Looper.java:313)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
08-17 10:02:47.773  7254  7254 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 10:02:47.774  7254  7254 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-17 10:02:47.774  7254  7254 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I do not know which NuGet package contains the type `Trimble.Licensing.LicensingFactory`.

**Comment by grendello** [comment]
The licensing shared library is apparently loaded by the licensing type constructor:

```
08-17 10:02:47.714  7254  7254 I monodroid-assembly: Trying to load shared library '/data/app/~~QpZc1fgZ0NIiyj-rYuzHtw==/com.companyname.AndroidApp1-TDJbAbM4g7dPW67RfFj_lQ==/lib/arm64/libTrimble.Licensing.CSWrapped.so'
08-17 10:02:47.714  7254  7254 D monodroid-assembly: Caching p/invoke entry Trimble.Licensing.CSWrapped @ CSharp_LicensingFactoryProxy_CreateV2Licensing__SWIG_1
08-17 10:02:47.746  7254  7254 D AndroidRuntime: Shutting down VM
```

it appears to be loaded properly, but on return from p/invoke the exception is thrown. It looks as if the licensing type's constructor is throwing it.

**Comment by jonpryor** [comment]
@JRosanowski: What NuGet package contains `Trimble.Licensing.LicensingFactory.CreateV2Licensing()`?

**Comment by JRosanowski** [comment]
@jonpryor It's a proprietary dll. I was mainly trying to find out if it should be expected to work with Android .Net6 or .Net Maui projects even though it's built with Xamarin Classic. We currently have no problem with it in a Xamarin Forms project and a Xamarin Classic Android project. If it is expected to work then I can ask the team that maintains it to investigate but I thought someone here might have knowledge of whether it should work in the first place or whether it needs to be rebuilt with Android .Net 6.
Cheers.

**Comment by JRosanowski** [comment]
It turned out to be some sort of Babel obfuscator issue
