### ISSUE TITLE
Cannot build the sdk due to HTTP 503

### ISSUE THREAD

**Issue by FuJa0815** [xamarin/xamarin-android#7304]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

main branch

### Description

I tried to compile the SDK, but it fails due to a HTTP 503 error.

### Steps to Reproduce

git clone this
make prepare

### Relevant log output

```shell
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Install required .NET Preview SDK locally
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Downloading dotnet-install...
  🔗 https://dot.net/v1/dotnet-install.sh
Discovering download URLs for dotnet SDK '7.0.100-rc.2.22417.1'...
Installing dotnet SDK '7.0.100-rc.2.22417.1'...
Archive path: /home/jfuehrer/android-archives/dotnet-sdk-7.0.100-rc.2.22417.1-linux-x64.tar.gz
[Tar] extracting archive
[Tar] log file: bin/BuildDebug/prepare-20220824T103232.tar-extract-archive.dotnet-sdk-7.0.100-rc.2.22417.1-linux-x64.tar.gz.log
TODO: Implement parsing, if necessary
      From: Xamarin.Android.Prepare.TarRunner+OutputSink..ctor at /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/ToolRunners/TarRunner.OutputSink.cs(15,5)
Elapsed: 00:00:02.9306753
/home/jfuehrer/xamarin-android/bin/Debug/dotnet/sdk/7.0.100-rc.2.22417.1/MSBuild.dll -nologo -bl:/home/jfuehrer/xamarin-android/bin/BuildDebug/msbuild-20220824T103232-download-runtime-packs.binlog -maxcpucount -target:Restore -verbosity:m /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/package-download
.proj
  Error: dotnet restore /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/package-download.proj failed.

Step Xamarin.Android.Prepare.Step_InstallDotNetPreview failed
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_InstallDotNetPreview failed
   at Xamarin.Android.Prepare.Scenario.Run(Context context, Log log) in /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/Application/Scenario.cs:line 50
   at Xamarin.Android.Prepare.Context.Execute() in /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/Application/Context.cs:line 845
   at Xamarin.Android.Prepare.App.Run(String[] args) in /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/Main.cs:line 174

make: *** [Makefile:186: prepare] Error 1
➜  xamarin-android git:(main) ✗ dotnet restore /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/package-download.proj 
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c914a8/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-arm64/index.json'.
  Response status code does not indicate success: 503 (Service Unavailable).
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c914a8/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-x86/index.json'.
  Response status code does not indicate success: 503 (Service Unavailable).
  Restored /home/jfuehrer/xamarin-android/build-tools/xaprepare/xaprepare/package-download.proj (in 17.92 sec).
```

**Comment by jpobst** [comment]
HTTP 503 is generally that the server is temporarily having issues.

I would retry this.
