### ISSUE TITLE
MAUI build errors in VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7317]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-build-errors-in-VS-2022/10121759)._

---
Update VS 2022 to Version 17.3.0
Opened new MAUI project, tried adding some nugets, 
and I keep getting build errors:

```
Error	XARDF7024	System.IO.IOException: The process cannot access the file 'values.xml' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()	MauiPOC1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets	2449	

```

```
Error java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, 
origin: C:\Users\[user]\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : 
com/google/common/util/concurrent/ListenableFuture.class	
MauiPOC1	
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.D8.targets	79	

```

This happens when trying to Build/Rebuild after adding nuget.
I tried closing the Pixel 5 Android 12 Emulator and this still happens.
Before adding the nuget, the project compiled and ran successfully.  

---
#### Feedback Bot on 8/16/2022, 01:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
Version `1.0.0.5` of `Xamarin.Google.Guava.ListenableFuture` was broken.

I would suggest using a more recent version:
https://www.nuget.org/packages/Xamarin.Google.Guava.ListenableFuture/1.0.0.9

Additional details:
https://github.com/xamarin/AndroidX/issues/535
