### ISSUE TITLE
Xamarin.AndroidDesigner.Tests failing with The session is not in a state where custom controls can be used

### ISSUE THREAD

**Issue by mdh1418** [xamarin/xamarin-android#7375]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Windows

### Description

Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6687060&view=logs&j=291cfdd8-b55d-5aec-3c07-abeba850aaac&t=cb584966-c328-5870-08e4-af92574c76b6

```
1) Failed : Xamarin.AndroidDesigner.Tests.AndroidDesignerSessionCustomControlsTest.CanLoadCustomControlReferencingEmbeddedResources
  Expected: False
  But was:  True
   at Xamarin.AndroidDesigner.Tests.AndroidDesignerSessionCustomControlsTest.<CanLoadCustomControlReferencingEmbeddedResources>d__38.MoveNext() in D:\a\1\s\UITools\Designer\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Tests\AndroidDesignerSessionCustomControlsTest.cs:line 765

2) Failed : Xamarin.AndroidDesigner.Tests.AndroidDesignerSessionCustomControlsTest.CanLoadCustomWidgetWithAsset
  Expected: False
  But was:  True
   at Xamarin.AndroidDesigner.Tests.AndroidDesignerSessionCustomControlsTest.<CanLoadCustomWidgetWithAsset>d__34.MoveNext() in D:\a\1\s\UITools\Designer\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Tests\AndroidDesignerSessionCustomControlsTest.cs:line 702

3) Failed : Xamarin.AndroidDesigner.Tests.AndroidDesignerSessionCustomControlsTest.CheckThemeHierarchyForAppCompat
The session is not in a state where custom controls can be used
   at Xamarin.AndroidDesigner.Tests.SessionCustomControlBasedTest.EnsureSessionHasCustomControlsEnabled() in D:\a\1\s\UITools\Designer\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Tests\FixtureHelpers\SessionCustomControlBasedTest.cs:line 43
   at Xamarin.AndroidDesigner.Tests.SessionCustomControlBasedTest.<Setup>d__7.MoveNext() in D:\a\1\s\UITools\Designer\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Tests\FixtureHelpers\SessionCustomControlBasedTest.cs:line 31

...

50) Failed : Xamarin.AndroidDesigner.Tests.Moyeu.CanLoadLayoutsInProject
Custom controls are not enabled in the test session, bailing out early
   at Xamarin.AndroidDesigner.Tests.RegressionTest.<Setup>d__8.MoveNext() in D:\a\1\s\UITools\Designer\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Tests\RegressionTest.cs:line 65

```

### Steps to Reproduce

Opened a new PR https://github.com/xamarin/xamarin-android/pull/7331 with unrelated changes.

**Comment by jpobst** [comment]
Thanks for the effort to file this, but our team does not track test failures with issues.  😁
