### ISSUE TITLE
"Application has stopped" on starting app after updating from Xamarin.Android.Sdk.12.3.0.3 to Xamarin.Android.Sdk.13.0.0.0

### ISSUE THREAD

**Issue by massimoappi** [xamarin/xamarin-android#7407]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2022 17.3 Pro, VS2022 17.4 Pro Preview

### Description

Hello to all.

After upgraded Visual Studio 2022 from 17.3 to 17.4 (preview) in Win10 22H2 Pro (but VS2022 Pro 17.3 not preview behave in the same way), a working Xamarin.Android project targeting (old) Android 4.2 API 17 Jelly Bean device started to hang, both in debug or manual app launch from home. The Android Alert box says: "Unfortunally, application has stopped". Debug seems not to start at all; putting a break-point in the main activity OnCreate() method does not stop; app seems to stop before.

On Visual Studio "Debug" output window, the log is:

```
Inoltro della porta 8828 del debugger
Rilevamento del processo esistente
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "<app>/crc64829ad6bf367081bd.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=<app>/crc64829ad6bf367081bd.MainActivity }

[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "__umask_chk" referenced by "libxamarin-debug-app-helper.so"...
[AndroidRuntime] 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[AndroidRuntime] 	at java.lang.System.loadLibrary(System.java:535)
[AndroidRuntime] 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
[AndroidRuntime] 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:4819)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
[AndroidRuntime] 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:137)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5041)
[AndroidRuntime] 	at java.lang.reflect.Method.invokeNative(Native Method)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Method.java:511)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
[AndroidRuntime] 	at dalvik.system.NativeStart.main(Native Method)
```
The source code is untouched from june 2022, and today, end of september 2022, the same code is not working anymore. If code is not changed, environment (IDE) must have changed! So I start to investigate about Xamarin installed versions, and I found this issue wich pointer me to the solution (or better, the workaround...) https://github.com/xamarin/xamarin-android/issues/4053#issuecomment-567431280

In my case, problem started after upgraded to the Xamarin.Android.Sdk-13.0.0.0.vsix using the Visual Studio Installer upgrade process. After downloaded previous Xamarin.Android.Sdk-12.3.0.3.vsix version and replaced the updated SDK files, as suggested on the link, build and debug started to work successfully.

So the problem is really in the Xamarin.Android.Sdk-13.0.0.0.vsix upgrade.

Now, I extracted all the 12.* Xamarin.Android.Sdk released versions found in https://github.com/xamarin/xamarin-android/blob/main/Documentation/previous-releases.md in the respective .vsix output folders, naming each folder version with the pattern "folder-mai.min.rev", to have them all on the disk at the same time, then created symbolic link to use a single version at time inside VS.

This is the batch I created to quick switch between Sdk versions:
```@echo off

REM https://github.com/xamarin/xamarin-android/issues/4053
REM Move the original directories and files for the Xamarin.Android SDK out of the way. For the default install location of Visual Studio 2019 Community, those paths are:
REM 
REM C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android
REM C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Android.Sdk.props
REM C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Android.Sdk.targets
REM C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Novell
REM C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid
REM One option is to move these items to a temporary location in the user home directory to make it easy to put them back. Another option is to delete them.
REM 
REM Open the .vsix package as a ZIP archive, for example by renaming it to have a .zip extension and browsing it in Explorer.
REM 
REM Find the corresponding directories and files from step 1 under the $MSBuild and $ReferenceAssemblies directories in the .vsix archive, and extract them into the appropriate locations in the Visual Studio installation.

REM Set VS2022 root folder
SET VS_ROOT_FOLDER=C:\Program Files\Microsoft Visual Studio\2022\Preview
SET XAMARIN_ANDROID_VERSION=

echo.
echo *** Run this script with elevated prompt permissions ***
echo.
echo Available Xamarin.Android version:
echo  1. Xamarin.Android ver 12.1.0.5
echo  2. Xamarin.Android ver 12.2.0.4
echo  3. Xamarin.Android ver 12.3.0.3
echo  4. Xamarin.Android ver 13.0.0.0
echo.
choice /N /C "1234" /M "Select version to apply: "

IF "%ERRORLEVEL%" EQU "4" SET XAMARIN_ANDROID_VERSION=13.0.0.0
IF "%ERRORLEVEL%" EQU "3" SET XAMARIN_ANDROID_VERSION=12.3.0.3
IF "%ERRORLEVEL%" EQU "2" SET XAMARIN_ANDROID_VERSION=12.2.0.4
IF "%ERRORLEVEL%" EQU "1" SET XAMARIN_ANDROID_VERSION=12.1.0.5
IF "%XAMARIN_ANDROID_VERSION%" EQU "" goto unknown_version

echo.
echo Removing current symbolic link..
rmdir "%VS_ROOT_FOLDER%\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid"
rmdir "%VS_ROOT_FOLDER%\Msbuild\Novell"
rmdir "%VS_ROOT_FOLDER%\Msbuild\Xamarin"
echo.
echo Creating symbolic link..
mklink /d "%VS_ROOT_FOLDER%\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid" "%VS_ROOT_FOLDER%\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid-%XAMARIN_ANDROID_VERSION%"
mklink /d "%VS_ROOT_FOLDER%\Msbuild\Novell" "%VS_ROOT_FOLDER%\Msbuild\Novell-%XAMARIN_ANDROID_VERSION%"
mklink /d "%VS_ROOT_FOLDER%\Msbuild\Xamarin" "%VS_ROOT_FOLDER%\Msbuild\Xamarin-%XAMARIN_ANDROID_VERSION%"
echo.
echo Symbolic links created successfully.
echo.
goto end

:unknown_version
echo.
echo "%XAMARIN_ANDROID_VERSION%"
echo Error: unknown version
echo.
goto end

:end
pause
```

All the 12.* versions are building and debugging fine, without the runtime error. Only the 13.0 version raise that error while starting the app.

How should I manage this breaking change now? Should I prepare a virtual machine with Windows10/VS2022/Xamarin.Android.Sdk-12.3.0.3 and disconnect it from the world, to keep the environment unchanged in the future?

Please provide some guidelines to well manage this issue.

**P.S.: I know that Xamarin.Android targets KitKat 4.4 as minimum platform, but JB 4.2 is very close to that version, the app is very simple and source code worked until SDK 12. I understand that JB is a very old platform, and I don't expect Microsoft still support it.. for me is enought to know the correct way to "freeze" a development environment and continue to support that platform with the 12. Xamarin.Anroid SDK.**

Thanks!

### Steps to Reproduce

Create "Empty App" from VS2022 Xamarin.Android template, using the Xamarin.Android.Sdk-13.0.0.0.vsix updated SDK and deploy to a Jelly Bean 4.2 android device (maybe also 4.3 and 4.4 may throw same exception).

### Did you find any workaround?

Use Xamarin.Android.Sdk-12.3.0.3 from here: [https://aka.ms/xamarin-android-commercial-d17-2-windows](url)

**Comment by massimoappi** [comment]
Thank you @jonpryor for your detailed reply!
Now it's clear to me why I got that behaviour with the same untouched source code.
I will start to plan how to migrate our App to newer (supported) Android device.
Kind regards!
