### ISSUE TITLE
Access denied when attempting to build a project

### ISSUE THREAD

**Issue by nacjacks** [xamarin/xamarin-android#7433]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

Rider 2022.2.3, .NET6.0.401

### Description

When attempting to build a project targeting Android I receive the following exception. I have attempted to move the project to different folders and changing the folder permissions to be more open. I haven't found anything online regarding this issue.

```
Xamarin.Android.Common.targets(1055, 2): [XACIC7019] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 125
   at Xamarin.Android.Tasks.CopyIfChanged.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```

### Steps to Reproduce

1. Create a new Android project
2. Attempt to build the project

### Did you find any workaround?

[msbuild.binlog.txt](https://github.com/xamarin/xamarin-android/files/9699687/msbuild.binlog.txt)

**Comment by dellis1972** [comment]
This might happen if a destination file is read only. Check that none of your files are read only, these attributes would be copied over to the intermediate directory files. Although the CopyIfChange does does make any file it copies writable....

I guess the other thing is to check the IDE is not running as admin. 
Also check any Anti-Virus you have. You might need to add an exclusion.
