### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() failed with: System.ArgumentException: An invalid IP address was specified. (Parameter 'address')   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)

### ISSUE THREAD

**Issue by n9** [xamarin/xamarin-android#7435]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.3.3, Windows 10, Android Emulator, .NET 6.0.400

### Description

Calling to `NetworkInterface.GetAllNetworkInterfaces()` caused the following exception:

```
System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)
   at System.Net.NetworkInformation.AndroidNetworkInterface.AddAddress(IpAddressInfo* addressInfo)
   at System.Net.NetworkInformation.NetworkInterfacePal.ToAndroidNetworkInterfaceArray(Int32 interfaceCount, IntPtr networkInterfacesPtr, Int32 addressCount, IntPtr addressPtr)
   at System.Net.NetworkInformation.NetworkInterfacePal.TransformNetworkInterfacess[AndroidNetworkInterface[]](Func`5 transform)
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAndroidNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at My.MyActivity.OnResume() in C:\PathTo\MyActivity.cs:line 121
   at Android.App.Activity.n_OnResume(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.App.Activity.cs:line 4732
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

It seems to be caused by "some" current state of network of Android emulator or computer. Previously the same code was working properly.

### Output of `adb shell ifconfig`
```
dummy0    Link encap:UNSPEC
          inet6 addr: fe80::983b:fcff:fe1a:b9e5/64 Scope: Link
          UP BROADCAST RUNNING NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:114 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:21286

radio0    Link encap:UNSPEC
          inet addr:10.0.2.18  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fec0::a916:24cf:d7d7:16b9/64 Scope: Site
          inet6 addr: fe80::70d0:1cff:fec9:8c8f/64 Scope: Link
          inet6 addr: fec0::31b8:f588:185e:ea1/64 Scope: Site
          inet6 addr: fec0::70d0:1cff:fec9:8c8f/64 Scope: Site
          UP BROADCAST RUNNING ALLMULTI  MTU:1500  Metric:1
          RX packets:889 errors:0 dropped:0 overruns:0 frame:0
          TX packets:296 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:133083 TX bytes:74404

lo        Link encap:UNSPEC
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope: Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:52046 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52046 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6892031 TX bytes:6892031

wlan0     Link encap:UNSPEC    Driver mac80211_hwsim
          inet addr:10.0.2.16  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::d00b:6e81:2477:d8f0/64 Scope: Link
          inet6 addr: fec0::e24:5b2f:ec21:1508/64 Scope: Site
          inet6 addr: fec0::4d3e:ab0d:9188:6c52/64 Scope: Site
          inet6 addr: fec0::5cce:119e:b970:3657/64 Scope: Site
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:69448 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43917 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:47201968 TX bytes:6537821
```

### Output of `adb shell ip address`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 9a:3b:fc:1a:b9:e5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::983b:fcff:fe1a:b9e5/64 scope link
       valid_lft forever preferred_lft forever
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
5: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
8: ip6_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
9: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
10: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
11: ip6gre0@NONE: <NOARP> mtu 1448 qdisc noop state DOWN group default qlen 1000
    link/gre6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
12: hwsim0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ieee802.11/radiotap 12:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
15: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:15:b2:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.16/24 brd 10.0.2.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fec0::4d3e:ab0d:9188:6c52/64 scope site temporary dynamic
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fec0::5cce:119e:b970:3657/64 scope site temporary deprecated dynamic
       valid_lft 86093sec preferred_lft 0sec
    inet6 fec0::e24:5b2f:ec21:1508/64 scope site dynamic mngtmpaddr stable-privacy
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fe80::d00b:6e81:2477:d8f0/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
17: radio0@if11: <BROADCAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:d0:1c:c9:8c:8f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.2.18/24 brd 10.0.2.255 scope global radio0
       valid_lft forever preferred_lft forever
    inet6 fec0::31b8:f588:185e:ea1/64 scope site temporary deprecated dynamic
       valid_lft 68128sec preferred_lft 0sec
    inet6 fec0::a916:24cf:d7d7:16b9/64 scope site temporary deprecated dynamic
       valid_lft 68128sec preferred_lft 0sec
    inet6 fec0::70d0:1cff:fec9:8c8f/64 scope site deprecated dynamic mngtmpaddr
       valid_lft 68128sec preferred_lft 0sec
    inet6 fe80::70d0:1cff:fec9:8c8f/64 scope link
       valid_lft forever preferred_lft forever
```

### Steps to Reproduce

It's not repeatable bug.
It appeared for the first time.

### Did you find any workaround?

Not yet. But I expect that restarting the Android emulator or computer might help.

**Comment by grendello** [comment]
My guess would be the `dummy0` device passing a null/empty IPv4 address to `System.Net.IPAddress`

**Comment by jonathanpeppers** [comment]
Closing as fixed. The underlying Android network-interface memory overlap was fixed in dotnet/runtime#76370: https://github.com/dotnet/runtime/pull/76370, with the API 21–23 follow-up in dotnet/runtime#76541: https://github.com/dotnet/runtime/pull/76541. The fixes were backported to .NET 6.0.12 in dotnet/runtime#77260: https://github.com/dotnet/runtime/pull/77260. This report used .NET 6.0.400, which predates that servicing fix. If the exception occurs on a currently supported .NET release, please file a new dotnet/runtime issue with a reproducible network configuration. I am a bot.
