### ISSUE TITLE
Adding  Xamarin.Android.Arch.Work.Runtime nuget package to Maui Project generates a MSB4018 error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7515]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding--XamarinAndroidArchWorkRuntim/10173974)._

---
I have  Maui Project w/ .Net 7 and Maps and Map Control.
Added the Xamarin.Android.Arch.Work.Runtime nuget and get:

Error	MSB4018	The "VerifyVersionsTask" task failed unexpectedly.
System.ArgumentException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
Parameter name: input
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at Xamarin.Android.Support.BuildTasks.NugetPackages.GatherProjectJsonVersions(String packageIdPrefix, String projectExtensionsPath, IEnumerable`1 excludedPackages, Version monoandroidVersion, Dictionary`2 packageVersions, TaskLoggingHelper log)
   at Xamarin.Android.Support.BuildTasks.VerifyVersionsTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()	RareBirder	C:\Users\pkzso\.nuget\packages\xamarin.android.support.annotations\28.0.0.3\build\monoandroid90\Xamarin.Android.Support.Annotations.targets	20	

---
#### Feedback Bot on 10/16/2022, 07:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment]
It looks like that package is several years old and still uses Android Support Libraries which are no longer supported (by us or Google).

You likely want to migrate to AndroidX and use something like https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime instead.
