### ISSUE TITLE
Installing the emulator fails "Operation Failed: Installing Android Emulator v31.2.10"

### ISSUE THREAD

**Issue by xoration** [xamarin/xamarin-android#7549]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022  17.4.0

### Description

When trying to install the emulator via the Android SDKs and Tools dialog I receive the error message:
"Operation Failed: Installing Android Emulator v31.2.10 - "Specified argument was out of the range of valid values.""

Before I was stuck without and emulator I had an older version installed but the update failed with the same error message and while trying to figure out what's wrong I accidently uninstalled it...

[2022-11-09_16-48-14.14636.sdkmanager.log](https://github.com/xamarin/xamarin-android/files/9972806/2022-11-09_16-48-14.14636.sdkmanager.log)

### Steps to Reproduce

1. Tools -> Android -> Android SDK Manager...
2. Select Tools Tab
3. Select Android Emulator
4. Click Apply Changes

### Relevant log output

```shell
[2022-11-09 16:49:23.5] WARNING: [Resiliency.Polly.Policies]: Delegate has thrown System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xamarin.Installer.AndroidSDK.Manager.Helper.<CheckIfNetworkAvailable>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext(), retrying...
[2022-11-09 16:49:24.5] ACTION: Install start component emulator
[2022-11-09 16:49:24.5] EXCEPTION: Downloading Android Emulator v31.2.10 failed, Details: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Xamarin.Installer.AndroidSDK.MonitorWithTotalProgress.set_SubComponentsCount(Int32 value)
   at Xamarin.Installer.AndroidSDK.Manager.AndroidSDKComponent.<Install>d__66.MoveNext()
[2022-11-09 16:49:24.5] ACTION: Install result InstallationError component emulator
[2022-11-09 16:49:24.5] ACTION: ApplySdkComponentChanged uninstall:[] install:[emulator]
```

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
