### ISSUE TITLE
Cannot build Android APK after updating Visual Studio

### ISSUE THREAD

**Issue by jamers99** [xamarin/xamarin-android#7595]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.4.1

### Description

We're running this command to build our Android APK in a pipeline:
msbuild.exe "C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" /nologo /nr:false /t:"Clean" /p:configuration="Release" /t:PackageForAndroid

But it's failing with this error:
```
"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj"(Clean;PackageForAndr
oid target) (1) ->
(_BuildApkEmbed target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,
3): error XABLD7028: System.IO.FileNotFoundException: Could not find file 'C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile
\MyEbms.Mobile.Android\obj\Release\110\aot\armeabi-v7a\libaot-Telerik.Documents.Spreadsheet.dll.so'. [C:\Repos\Eagle\Fe
atures\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028: File name: 'C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\obj\Release\110\aot\a
rmeabi-v7a\libaot-Telerik.Documents.Spreadsheet.dll.so' [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.And
roid\MyEbms.Mobile.Android.csproj]
```

This started happening after upgrading our build machines from VS 2022 17.0.* to 17.4.1
I tried reproducing it locally and I'm getting the same issue.

### Steps to Reproduce

I don't have the project available to build yet. Let me know if that is needed.

### Did you find any workaround?

No, this is blocking us, we're unable to do a build.

### Relevant log output

Here are the logs (not all of them since my command line cut off after a while): 
[builderror.txt](https://github.com/xamarin/xamarin-android/files/10126789/builderror.txt)

```shell

Here is the seemingly relevant bit:
"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_ResolveAssemblies target) ->
  C:\Users\james\.nuget\packages\system.io.pipes\4.3.0\ref\netstandard1.3\System.IO.Pipes.dll : warning XA0107: Ignorin
g Reference Assembly `C:\Users\james\.nuget\packages\system.io.pipes\4.3.0\ref\netstandard1.3\System.IO.Pipes.dll`. [C:
\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(316,5
): warning XA0122: Assembly 'Xamarin.Android.Support.Annotations' is using a deprecated attribute '[assembly: Java.Inte
rop.DoNotPackageAttribute]'. Use a newer version of this NuGet package or notify the library author. [C:\Repos\Eagle\Fe
atures\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_ConvertPdbFiles target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'General.Mobile.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Features\MyEbms\
MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'Eagle.Client.Mobile.App.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Feature
s\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'Eagle.Client.Mobile.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Features\My
Ebms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'Eagle.Core.Mobile.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Features\MyEb
ms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'Microsoft.ApplicationInsights.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\F
eatures\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'MyEbms.Mobile.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Features\MyEbms\M
yEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5
): warning XA0125: 'Plugin.SimpleAudioPlayer.pdb' is using a deprecated debug information level. [C:\Repos\Eagle\Featur
es\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the proj
ect file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug
 information level. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(401,5):
 warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the
library author. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_ReadAndroidManifest target) ->
  obj\Release\110\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at p
ath: C:\Program Files (x86)\Android\android-sdk\platforms\android-30\optional\com.symbol.emdk.jar [C:\Repos\Eagle\Featu
res\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_CheckGoogleSdkRequirements target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(347,5
): warning XA1008: The TargetFrameworkVersion (Android API level 30) is lower than the targetSdkVersion (31). Please in
crease the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that
the API levels match. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_BuildApkEmbed target) ->
  obj\Release\110\lp\5\nl\arm64-v8a\libSkiaSharp.so : warning XA4301: APK already contains the item lib/arm64-v8a/libSk
iaSharp.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  obj\Release\110\lp\5\nl\armeabi-v7a\libSkiaSharp.so : warning XA4301: APK already contains the item lib/armeabi-v7a/l
ibSkiaSharp.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csp
roj]
  obj\Release\110\lp\5\nl\x86\libSkiaSharp.so : warning XA4301: APK already contains the item lib/x86/libSkiaSharp.so;
ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  obj\Release\110\lp\5\nl\x86_64\libSkiaSharp.so : warning XA4301: APK already contains the item lib/x86_64/libSkiaShar
p.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  obj\Release\110\lp\6\nl\arm64-v8a\libSkiaSharp.so : warning XA4301: APK already contains the item lib/arm64-v8a/libSk
iaSharp.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  obj\Release\110\lp\6\nl\armeabi-v7a\libSkiaSharp.so : warning XA4301: APK already contains the item lib/armeabi-v7a/l
ibSkiaSharp.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csp
roj]
  obj\Release\110\lp\6\nl\x86\libSkiaSharp.so : warning XA4301: APK already contains the item lib/x86/libSkiaSharp.so;
ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
  obj\Release\110\lp\6\nl\x86_64\libSkiaSharp.so : warning XA4301: APK already contains the item lib/x86_64/libSkiaShar
p.so; ignoring. [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]


"C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj" (Clean;PackageForAndr
oid target) (1) ->
(_BuildApkEmbed target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,
3): error XABLD7028: System.IO.FileNotFoundException: Could not find file 'C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile
\MyEbms.Mobile.Android\obj\Release\110\aot\armeabi-v7a\libaot-Telerik.Documents.Spreadsheet.dll.so'. [C:\Repos\Eagle\Fe
atures\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028: File name: 'C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\obj\Release\110\aot\a
rmeabi-v7a\libaot-Telerik.Documents.Spreadsheet.dll.so' [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.And
roid\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Repos\Eagle\Features\M
yEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at System.IO.File.GetAttributes(String path) [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms
.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Tools.Zip.WindowsPlatformServices.IsDirectory(ZipArchive archive, String path, Boolean
& result) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/WindowsPlatformServices.cs:line 46 [C:\Repos\Eagle\Fe
atures\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Tools.Zip.PlatformServices.<>c__DisplayClass9_0.<IsDirectory>b__0(IPlatformServices se
rvices) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 74 [C:\Repos\Eagle\Features\My
Ebms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Tools.Zip.PlatformServices.CallServices(Func`2 code) in /Users/runner/work/1/s/LibZipS
harp/Xamarin.Tools.Zip/PlatformServices.cs:line 166 [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android
\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Tools.Zip.PlatformServices.IsDirectory(ZipArchive archive, String path) in /Users/runn
er/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 74 [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyE
bms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Tools.Zip.ZipArchive.AddFile(String sourcePath, String archivePath, EntryPermissions p
ermissions, CompressionMethod compressionMethod, Boolean overwriteExisting) in /Users/runner/work/1/s/LibZipSharp/Xamar
in.Tools.Zip/ZipArchive.cs:line 406 [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.A
ndroid.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, Str
ing apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo, String assemblyStoreApkName
) [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Xamarin.Android.Tasks.BuildApk.RunTask() [C:\Repos\Eagle\Features\MyEbms\MyEbms\Mobile\MyEbms.
Mobile.Android\MyEbms.Mobile.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2049,3)
: error XABLD7028:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/
external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17 [C:\Repos\Eagle\Features\My
Ebms\MyEbms\Mobile\MyEbms.Mobile.Android\MyEbms.Mobile.Android.csproj]

    19 Warning(s)
    1 Error(s)
```

**Comment by jamers99** [comment]
I verified that removing Telerik fixes the problem, but we obviously need that. Is there any more logs that would be helpful in diagnosing this? I'm **_unable_** to reproduce this by just making a new project and adding Telerik...

**Comment by hakakou** [comment]
I got this also, probably related in the latest VS 17.4.2. The project is using Telerik. The only way to manage to compile in release mode is by disabling AOT compilation in "Android Options"

```
XABLD7028: System.IO.FileNotFoundException: Could not find file 'C:\mobile\App1.Android\obj\Release\120\aot\armeabi-v7a\libaot-App1.Android.dll.so'.
File name: 'C:\mobile\App1.Android\obj\Release\120\aot\armeabi-v7a\libaot-App1.Android.dll.so'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Xamarin.Tools.Zip.WindowsPlatformServices.IsDirectory(ZipArchive archive, String path, Boolean& result) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/WindowsPlatformServices.cs:line 47
   at Xamarin.Tools.Zip.PlatformServices.CallServices(Func`2 code) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 166
   at Xamarin.Tools.Zip.PlatformServices.IsDirectory(ZipArchive archive, String path) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/PlatformServices.cs:line 74
   at Xamarin.Tools.Zip.ZipArchive.AddFile(String sourcePath, String archivePath, EntryPermissions permissions, CompressionMethod compressionMethod, Boolean overwriteExisting) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs:line 406
   at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo, String assemblyStoreApkName)
   at Xamarin.Android.Tasks.BuildApk.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
Done building project "App1.Android.csproj" -- FAILED.
Build FAILED.
```

**Comment by jonathanpeppers** [comment]
Is someone able to reproduce this in a sample app and share it? Thanks!

We might also be able to dig deeper with a `.binlog`:
```
msbuild YourAndroidApp.csproj -bl -t:Clean,SignAndroidPackage
```
This should create an `msbuild.binlog` file in the current directory you can share.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
