### ISSUE TITLE
WorkloadManifest targets/json mismatch

### ISSUE THREAD

**Issue by etvorun** [xamarin/xamarin-android#8112]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), .NET Android (net7.0-android, etc.)

### Affected platform version

.net8

### Description

Content of WorkloadManifest.targets does not match WorkloadManifest.json in C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.android. The *.targets file contains `<Import Project="Sdk.targets" Sdk="Microsoft.Android.Sdk.net6"/>` while there is no corresponding `"Microsoft.Android.Sdk.net6"` entry in *.json. This causes errors when running UpgradeAssistant in VS.

### Steps to Reproduce

1. Install .NET Upgrade Assistant extension for VS (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.upgradeassistant; alternatively use latest in-development version from [WebTools](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/WebTools/pullrequests?_a=completed) repository).
2. Install .NET Multi-platform App UI Development workload, include optional Xamarin and .NET 8 components.
3. Create a File > New Android App (Xamarin). Let's assume it is named XamApp.
4. Select XamApp.Android project in Solution Explorer, right click and select Upgrade.
5. Follow on screen instructions to Side-by-Side upgrade project to .net7.
**Expected**: no errors related to upgrading XamApp.AndroidCore.csproj
**Actual**: errors related to upgrading XamApp.AndroidCore.csproj
Note: for more details see VS [bug 1829352](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1829352).

![image](https://github.com/xamarin/xamarin-android/assets/48451158/d9ab11f7-9926-4db7-bb21-0bd09502f81a)

### Did you find any workaround?

Manually edit WorkloadManifest.targets to comment out `<Import Project="Sdk.targets" Sdk="Microsoft.Android.Sdk.net6"/>` .

### Relevant log output

```shell
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.Android.Sdk.net6' specified could not be found.  C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.android\WorkloadManifest.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportGroupElement(String directoryOfImportingFile, ProjectImportGroupElement importGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, IDirectoryCacheFactory directoryCacheFactory, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, Boolean interactive)
   at MSBuild.Abstractions.UnconfiguredProject.LoadProjects(ProjectCollection collection, ProjectRootElement rootElement)
   at MSBuild.Abstractions.MSBuildConversionWorkspace.TryCreateSdkBaselineProject(String projectFilePath, IProject project, IProjectRootElement root, ImmutableDictionary`2 configurations, String tfm, Boolean keepCurrentTFMs, Nullable`1& baselineProject)
   at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at Microsoft.UpgradeAssistant.TryConvert.Slices.Services.TryConvertService.<ConvertAsync>d__0.MoveNext()
```

**Comment by pjcollins** [comment]
I think this scenario will be fixed by https://github.com/xamarin/xamarin-android/commit/ee90ad9b4c87bf6a3840a70b51b9a684e79c5985, and should hopefully be resolved in .NET 8 Preview 5.

**Comment by jonathanpeppers** [comment]
@etvorun was any project `net6.0-android`? Do we need to make the upgrade assistant output `net7.0-android` projects?

.NET 6 MAUI & mobile are already out of support: https://dotnet.microsoft.com/platform/support/policy/maui

**Comment by jpobst** [comment]
Hopefully this is fixed now as `net6.0-android` is out of support.
