### ISSUE TITLE
Cannot run the debugger on a basic Android .Net application

### ISSUE THREAD

**Issue by actus-reus** [xamarin/xamarin-android#8159]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

Visual Studio Community 2022 for Mac Version 17.6 (build 1575)

### Description

Cannot run the debugger on a basic Android .Net application. In debug mode, the application compiles and deploys correctly (on a physical device)  but  before loading the debugger the message Cannot execute "$projectpath/bin/Debug/net7.0-android/testApp2.dll" is shown in the status bar and the debugger does not load. The application is installed on the device and can be launched from the home screen though. Device is API28.

From the Visual Studio log:

```
 ERROR [2023-06-30 10:09:33Z]: Cannot execute "/Volumes/xxx/xxx/Tmp/testApp2/bin/Debug/net7.0-android/testApp2.dll"
System.ArgumentNullException: Value cannot be null. (Parameter 'versions')
   at Xamarin.Android.Tools.AndroidAppManifest.Load(String filename, AndroidVersions versions) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/external/androidtools/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs:line 84
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.GetDefaultLaunchableActivityName(MonoDroidProjectConfiguration conf) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 240
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.TryGetActivityNameFromManifest(MonoDroidProjectConfiguration conf, ProgressMonitor monitor, String& activity, Boolean reportNoLaunchableActivity) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 213
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.UpdateExecutionConfiguration(AndroidExecutionTarget target, MonoDroidExecutionCommand command, ProgressMonitor monitor, MonoDroidProjectConfiguration configuration) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 79
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidProjectState.PrepareToRunApplicationAsync(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, ExecutionCommand executionCommand) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/AndroidProjectState.cs:line 331
   at Xamarin.Addins.Core.ProjectSystem.XamarinSdkProjectExtension.OnExecuteCommand(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, ExecutionCommand executionCommand) in /Users/runner/work/1/s/Xamarin.Addins.Core/ProjectSystem/XamarinSdkProjectExtension.cs:line 286
   at MonoDevelop.Projects.DotNetProject.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:line 2410
```

### Steps to Reproduce

- With VS2022 for Mac, create a new solution/project with the _Android Application_ (Android -->App--> .Net) project template 
- Attempt to run the application on a physical device with the debugger connected

### Did you find any workaround?

No

### Relevant log output

```shell
From the Visual Studio log:

 ERROR [2023-06-30 10:09:33Z]: Cannot execute "/Volumes/xxx/xxx/Tmp/testApp2/bin/Debug/net7.0-android/testApp2.dll"
System.ArgumentNullException: Value cannot be null. (Parameter 'versions')
   at Xamarin.Android.Tools.AndroidAppManifest.Load(String filename, AndroidVersions versions) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/external/androidtools/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs:line 84
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.GetDefaultLaunchableActivityName(MonoDroidProjectConfiguration conf) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 240
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.TryGetActivityNameFromManifest(MonoDroidProjectConfiguration conf, ProgressMonitor monitor, String& activity, Boolean reportNoLaunchableActivity) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 213
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidRunConfigurationProperties.UpdateExecutionConfiguration(AndroidExecutionTarget target, MonoDroidExecutionCommand command, ProgressMonitor monitor, MonoDroidProjectConfiguration configuration) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/PropertiesProviders/AndroidRunConfigurationProperties.cs:line 79
   at MonoDevelop.MonoDroid.ProjectSystem.AndroidProjectState.PrepareToRunApplicationAsync(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, ExecutionCommand executionCommand) in /Users/runner/work/1/s/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid/ProjectSystem/AndroidProjectState.cs:line 331
   at Xamarin.Addins.Core.ProjectSystem.XamarinSdkProjectExtension.OnExecuteCommand(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, ExecutionCommand executionCommand) in /Users/runner/work/1/s/Xamarin.Addins.Core/ProjectSystem/XamarinSdkProjectExtension.cs:line 286
   at MonoDevelop.Projects.DotNetProject.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:line 2410
```

**Comment by dellis1972** [comment]
Can you provide a diagnostic log so we can investigate further. 
You can get the instructions on how to get the diagnostic log at https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting.

By the looks of the stack trace this is an IDE extension issue.  you might want to report the issue via the menu item in VS For Mac itself via https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022#how-to-report-a-problem. This will direct the issue to the correct team.

**Comment by actus-reus** [comment]
Hello,

Here you have:

[android-deploy-Samsung SM-G950F.log](https://github.com/xamarin/xamarin-android/files/11937178/android-deploy-Samsung.SM-G950F.log)
[BuildLog.txt](https://github.com/xamarin/xamarin-android/files/11937186/BuildLog.txt)

Here you have the project generated through the VS template:

[testApp2.zip](https://github.com/xamarin/xamarin-android/files/11937210/testApp2.zip)

Emmanuel.

**Comment by dellis1972** [comment]
@tondat any ideas on this one? Looks like the `projectProperties.AndroidVersions` property is null..

**Comment by actus-reus** [comment]
Hello there,

Any news on this front? Could you give me some hints? Is `AndroidVersions` supposed to be retrieved from the project, from the manifest or from the system?

**Comment by jpobst** [comment]
This issue likely occurs in the Visual Studio integration, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
