### ISSUE TITLE
`SpannableString.GetSpans` does NOT accept nullable for `kind`

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#8167]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), .NET Android (net7.0-android, etc.)

### Affected platform version

API 21

### Description

```cs
public virtual Object[]? SpannableStringInternal.GetSpans(int queryStart, int queryEnd, Class? kind);
```

![image](https://github.com/xamarin/xamarin-android/assets/1096616/298e68e0-83f1-4cbc-8a9b-616b7106c3bf)

It is not null in the docs either: https://developer.android.com/reference/android/text/SpannableString#getSpans(int,%20int,%20java.lang.Class%3CT%3E)

> Return an array of the markup objects attached to the specified slice of this CharSequence and whose type is the specified type or a subclass of it. Specify Object.class for the type if you want all the objects regardless of type.

The other API I am using does:

https://developer.android.com/reference/android/text/SpannableString#nextSpanTransition(int,%20int,%20java.lang.Class)

> Return the first offset greater than start where a markup object of class type begins or ends, or limit if there are no starts or ends greater than start but less than limit. **Specify null or Object.class** for the type if you want every transition regardless of type.

### Steps to Reproduce

Run some valid code and observe the exception.

**Comment by jpobst** [comment]
What's weird is that `kind` is not marked with `@NonNull`, and the code checks for `null`, so the annotation appears to be correct:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/SpannableStringInternal.java#341

I wonder if this is some kind of error we are causing because we had to do magic to expose methods from the private `SpannableStringInternal` type:

https://github.com/xamarin/xamarin-android/blob/69b4ab056badcb5d25a5faf39d08baeb1b8b7010/src/Mono.Android/metadata#L1484

Or could it be because `java.lang.Class` is a "special"-ish Java type?

**Comment by jonpryor** [comment]
> It is not null in the docs either: https://developer.android.com/reference/android/text/SpannableString#getSpans(int,%20int,%20java.lang.Class%3CT%3E)

The method declaration within the Java documentation *does* allow `null`; Java doesn't have "nullable reference types", so `Class<T>` by default allows null.  For Java to say that it can't be null, there are a number of Java annotations which can be used, none of which are used here, *or* you rely on documentation, which doesn't *explicitly* call things out either.

There is thus unfortunately no *automated* way for us to *verify* nullability of parameters, other than to [check for a handful of "known" annotations](https://github.com/xamarin/java.interop/blob/e1121ead9f1602c1590abfa6235fa16aec567c4d/src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs#L498-L517), which means it's very easy for things to leak through the cracks.

(Not that I'm saying this *can't* be fixed; we can fix this via metadata.  My point is that this is {unfortunately} expected, and that pointing to the Java docs as a "source of truth" is not necessarily the source of truth you may think it is.)

**Comment by jonpryor** [comment]
@jpobst [wrote](https://github.com/xamarin/xamarin-android/issues/8167#issuecomment-1622264911):

> and the code checks for null,

lol, *some* of the code checks for `null`, but not all!  This is where the full stack trace would be handy, but consider this call to `ArrayUtils.emptyArray()`: https://github.com/aosp-mirror/platform_frameworks_base/blob/a694149b9fba63811fca00b685257f006f381dd4/core/java/android/text/SpannableStringInternal.java#L406

`ArrayUtils.emptyArray()` has no null check, with line 126 always calling `kind.hashCode()`: https://github.com/aosp-mirror/platform_frameworks_base/blob/037244751d7bfb728dd51265b251e3a24da38556/core/java/com/android/internal/util/ArrayUtils.java#L114-L136

**Comment by jpobst** [comment]
With this code:
```csharp
var s = new SpannableString("Hello there!");
var b = s.GetSpans(0, 3, null);
```

This is the stack trace I get:
```
**Java.Lang.NullPointerException:** 'Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference'

**Java.Lang.NullPointerException:** 'Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 11524
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 867
[mono-rt]    at Android.Text.SpannableString.GetSpans(Int32 queryStart, Int32 queryEnd, Class kind) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Text.SpannableString.cs:line 246
[mono-rt]    at size_test.MainActivity.OnCreate(Bundle savedInstanceState) in C:\Users\jopobst\Desktop\size-test\MainActivity.cs:line 16
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Activity.cs:line 2816
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
[mono-rt] 	at com.android.internal.util.ArrayUtils.emptyArray(ArrayUtils.java:127)
[mono-rt] 	at android.text.SpannableStringInternal.getSpans(SpannableStringInternal.java:406)
[mono-rt] 	at android.text.SpannableString.getSpans(SpannableString.java:24)
[mono-rt] 	at crc64889938116b43042d.MainActivity.n_onCreate(Native Method)
[mono-rt] 	at crc64889938116b43042d.MainActivity.onCreate(MainActivity.java:30)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:8305)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:8284)
[mono-rt] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
[mono-rt] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
[mono-rt] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
[mono-rt] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:201)
[mono-rt] 	at android.os.Looper.loop(Looper.java:288)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:7872)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
[mono-rt] 	at com.android.internal.util.ArrayUtils.emptyArray(ArrayUtils.java:127)
[mono-rt] 	at android.text.SpannableStringInternal.getSpans(SpannableStringInternal.java:406)
[mono-rt] 	at android.text.SpannableString.getSpans(SpannableString.java:24)
[mono-rt] 	at crc64889938116b43042d.MainActivity.n_onCreate(Native Method)
[mono-rt] 	at crc64889938116b43042d.MainActivity.onCreate(MainActivity.java:30)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:8305)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:8284)
[mono-rt] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
[mono-rt] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
[mono-rt] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
[mono-rt] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:201)
[mono-rt] 	at android.os.Looper.loop(Looper.java:288)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:7872)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[mono-rt] 
```

Kinda weird that I get an NPE on a different method.  (Pixel 5 - API 33 emulator)

**Comment by jpobst** [comment]
I don't think there is anything to do here.  We only surface the annotations that Google has done.  We have made the explicit decision that we will not attempt to do any additional manual annotations.
