### ISSUE TITLE
Archive fails when linking Sdk Assemblies Only with Mono.Cecil.ResolutionException: Failed to resolve Kotlin.Coroutines.IContinuationInterceptor

### ISSUE THREAD

**Issue by Evige** [xamarin/xamarin-android#8338]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.7.3, Xamarin.Android SDK 13.2.1.2

### Description

Updated Visual Studio and this started showing up. Clean / Restart doesn't work.

### Steps to Reproduce

Haven't tried with new clean project,

1) Set Android project to Release/Any CPU
2) From Android Options Linker properties Linking to Sdk Assemblies Only
3) Clean Solution and try to Archive from Build.
4) Archive fails

### Did you find any workaround?

Setting linking to None from Sdk Assemblies Only.

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Kotlin.Coroutines.IContinuationInterceptor' (defined in assembly 'Xamarin.KotlinX.Coroutines.Core.Jvm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Kotlin.StdLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Kotlin.Coroutines.IContinuationInterceptor
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInterfaceImplementation(InterfaceImplementation iface)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs:line 166
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```

**Comment by dellis1972** [comment]
Do you need to add a reference to the Nuget `Xamarin.Kotlin.StdLib`

**Comment by Evige** [comment]
> Do you need to add a reference to the Nuget `Xamarin.Kotlin.StdLib`

Yes, that was one step of a solution. Now the archieve works correctly again after installing/updating a couple of Nugets. With Xamarin.Kotlin.StdLib I needed to add references to Nuget packages: Xamarin.AndroidX.Core (StdLib came with this as well), Xamarin.AndroidX.Activity, Xamarin.AndroidX.RecyclerView and updated Xamarin.AndroidX.Preferences.

With a previous version of Visual Studio Archive worked without these Nugets.

But thanks for the help!
