### ISSUE TITLE
hexadecimal value 0x0C, is an invalid character.

### ISSUE THREAD

**Issue by blmiles** [xamarin/xamarin-android#8349]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022, Version 17.7.3, .Net 7, Maui, Android App

### Description

This was building on the weekend, I'm made no changes to the project.
The android App was running on a target device (NOT an emulator) running Android 13.

When I now build I get the following error:
Error XAGJS7004 System.ArgumentException: '', hexadecimal value 0x0C, is an invalid character.

I have check every possible file and line I know to check. No idea why this happens NOW.
Zero changes over the weekend.

Here's the full error:
_Severity	Code	Description	Project	File	Line	Suppression State
Error	XAGJS7004	System.ArgumentException: '', hexadecimal value 0x0C, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at Xamarin.Android.Tasks.ManifestDocument.<>c.<ResolveDuplicates>b__92_0(XElement x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.RemoveDuplicateElements()
   at Xamarin.Android.Tasks.ManifestDocument.Save(Action`2 logCodedWarning, TextWriter stream, Boolean removeNodes)
   at Xamarin.Android.Tasks.ManifestDocument.Save(Action`2 logCodedWarning, Stream stream, Boolean removeNodes)
   at Xamarin.Android.Tasks.ManifestDocument.SaveIfChanged(TaskLoggingHelper log, String filename)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	mycompany	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Common.targets	1476_	

### Steps to Reproduce

No idea.

Possibly create new Maui app, target Android, target latest OS version, target latest SDK.

### Did you find any workaround?

No

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	XAGJS7004	System.ArgumentException: '', hexadecimal value 0x0C, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at Xamarin.Android.Tasks.ManifestDocument.<>c.<ResolveDuplicates>b__92_0(XElement x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.<ResolveDuplicates>d__92.MoveNext()
   at Xamarin.Android.Tasks.ManifestDocument.RemoveDuplicateElements()
   at Xamarin.Android.Tasks.ManifestDocument.Save(Action`2 logCodedWarning, TextWriter stream, Boolean removeNodes)
   at Xamarin.Android.Tasks.ManifestDocument.Save(Action`2 logCodedWarning, Stream stream, Boolean removeNodes)
   at Xamarin.Android.Tasks.ManifestDocument.SaveIfChanged(TaskLoggingHelper log, String filename)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	mycompany	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Common.targets	1476
```

**Comment by jonathanpeppers** [comment]
Is it an invalid character in your `AndroidManifest.xml` file?

If you could share a `.binlog` of the failing build, we can probably find the file path. (and maybe line number?)

https://aka.ms/binlog

**Comment by blmiles** [comment]
@jonathanpeppers - thanks for such a quick response!

This is the AndroidManifest.xml
It is very short and I'm checked every line!

I'll get the binlog shortly...

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.mycompany.myapp" android:versionCode="16" android:versionName="7.0.0.0">
	<application android:allowBackup="true" android:supportsRtl="true" android:label="myapp" android:icon="@mipmap/icon"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
	<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.MANAGE_MEDIA" />
	<uses-sdk android:minSdkVersion="31" android:targetSdkVersion="33" />
	<queries>
		<intent>
			<action android:name="android.support.customtabs.action.CustomTabsService" />
		</intent>
	</queries>
</manifest>

**Comment by blmiles** [comment]
@jonathanpeppers 

Is there any way I can send the buildlog to you directly without uploading here?

Thanks

**Comment by jonathanpeppers** [comment]
You could use the email on [my GitHub profile](https://github.com/jonathanpeppers) instead. Thanks.

**Comment by blmiles** [comment]
Excellent, thanks so much!

**Comment by blmiles** [comment]
@jonathanpeppers 

Found the issue. Sent email explanation...

**Comment by jonathanpeppers** [comment]
Can you share an example of what file was wrong? It feels like it didn't give you a line number + file name that you could double-click the error to see where the issue was.

**Comment by jonathanpeppers** [comment]
Can you share the value of `Constants.MYAPPLABEL`?

It sounds like `[Activity(Label= "Something Invalid XML")]` doesn't give a line number for the `AndroidManifest.xml` file. So, we could keep this open to look into in the future.

**Comment by blmiles** [comment]
Hi Jonathan,

Here it is: public const string MYAPPLABEL=
"7\n\fC\a&\f\t\r\u00017\n\0\u000e\u001bm\u001b\u0004\0\0:\f\u0002\u0002\u0012
\a";

Hope that helps!

**Comment by blmiles** [comment]
Actually, here's the whole file:

using Android.App;
using Android.Content.PM;

namespace MyCompany;

[Activity(*Label= Constants.MYAPPLABLE*, NoHistory = true, LaunchMode =
LaunchMode.SingleTop, Exported = true)]
[IntentFilter(new[] { Android.Content.Intent.ActionView },
              Categories = new[] { Android.Content.Intent.CategoryDefault,
Android.Content.Intent.CategoryBrowsable },
              DataScheme = CALLBACK_SCHEME)]
public class WebAuthenticationCallbackActivity :
Microsoft.Maui.Authentication.WebAuthenticatorCallbackActivity
{
    const string CALLBACK_SCHEME = *XORService.XORCipher(Constants.
MYAPPLABLE, Constants.XORKEY),*
}

This actually works with the non-XOR'd value assigned to the Label.
Part of my Auth0 authentication...

Thx,

Lindsay Miles
