### ISSUE TITLE
BundleTool -  Failing when deploying to Pixel 6 running latest Android 14 beta.

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#8368]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.8.0 Prev 2.0

### Description

Done executing task "BuildApkSet" -- FAILED.

### Steps to Reproduce

Deploy app. Get the following

```
Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
com.android.tools.build.bundletool.model.exceptions.AdbOutputParseException: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.GlExtensionsParser.parse(GlExtensionsParser.java:72)
	at com.android.tools.build.bundletool.device.DdmlibDevice.getGlExtensions(DdmlibDevice.java:147)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:62)
	at com.android.tools.build.bundletool.commands.BuildApksModule.provideDeviceSpec(BuildApksModule.java:126)
	at com.android.tools.build.bundletool.commands.BuildApksModule_ProvideDeviceSpecFactory.provideDeviceSpec(BuildApksModule_ProvideDeviceSpecFactory.java:36)
	at com.android.tools.build.bundletool.commands.BuildApksModule_ProvideDeviceSpecFactory.get(BuildApksModule_ProvideDeviceSpecFactory.java:27)
	at com.android.tools.build.bundletool.commands.BuildApksModule_ProvideDeviceSpecFactory.get(BuildApksModule_ProvideDeviceSpecFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.android.tools.build.bundletool.commands.DaggerBuildApksManagerComponent.create(DaggerBuildApksManagerComponent.java:202)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:699)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:77)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
The command exited with code 1.
Done executing task "BuildApkSet" -- FAILED.
```
For some reason, I can't attach the log file either txt or zip of the build!

### Did you find any workaround?

Deploys OK to other  devices

**Comment by gmck** [comment]
[Build20230923.zip](https://github.com/xamarin/xamarin-android/files/12707388/Build20230923.zip)

Works now.

**Comment by dellis1972** [comment]
This looks like an issue with bundletool querying the device for information. My guess is try a different bundletool? There is probably a bug in it somewhere.

**Comment by gmck** [comment]
Where does one get a different bundle tool?

**Comment by dellis1972** [comment]
This is the area where you can get releases https://mvnrepository.com/artifact/com.android.tools.build/bundletool. 
Not sure which one would work though. 

If you want to use your own you will need to override the `AndroidBundleToolJarPath` msbuild property.

**Comment by gmck** [comment]
@dellis1972 
How do you tell which version VS2022 is using? The build doesn't emit a version number that I could find.

**Comment by dellis1972** [comment]
` java -jar <path to bundletoo.jar> version`

I'm not sure what the path will be, you'll need to look in the logs to find it as its burried in the sdk packs folder somewhere.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
