### ISSUE TITLE
Xamarin.Forms Android App (GnollHack) reports a runtime error unless installation path is very short

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#8697]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XamarinForms-Android-App-GnollHack-re/10415066)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.6.4]
After upgrading to Visual Studio 17.6.5, I started having problems with our [GnollHack Xamarin.Forms Android](https://github.com/hyvanmielenpelit/GnollHack) app  (q.v. [Build Instructions](https://github.com/hyvanmielenpelit/GnollHack/wiki/Build-Instructions-for-Android-Version-on-Windows)). In MainActivity, we have the following line:

`AssetPackListener.StateUpdate += Listener_StateUpdate;`

When I debugged the app, this line started to report the following **runtime error**:

```
{Java.Lang.ClassNotFoundException: mono.xamarin.google.android.play.core.assetpacks.AssetPackStateUpdateListenerWrapper_AssetPackStateListenerImplementor ---> Java.Lang.ClassNotFoundException: Didn't find class "mono.xamarin.google.android.play.core.assetpacks.AssetPackStateUpdateListenerWrapper_AssetPackStateListenerImplementor" on path: DexPathList[[zip file "/data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/base.apk"],nativeLibraryDirectories=[/data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/lib/arm64, /data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:12890 
  at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x0004c] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:397 
  at Android.Runtime.JNIEnv.AllocObject (System.String jniClassName) [0x00000] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:172 
  at Android.Runtime.JNIEnv.StartCreateInstance (System.String jniClassName, System.String jniCtorSignature, Android.Runtime.JValue* constructorParameters) [0x00007] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:236 
  at Android.Runtime.JNIEnv.StartCreateInstance (System.String jniClassName, System.String jniCtorSignature, Android.Runtime.JValue[] constructorParameters) [0x00018] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:243 
  at Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper+IAssetPackStateListenerImplementor..ctor (System.Object sender) [0x00000] in C:\a\_work\1\s\generated\com.google.android.play.core\obj\Release\monoandroid12.0\generated\src\Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper.cs:134 
  at Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper.__CreateIAssetPackStateListenerImplementor () [0x00000] in C:\a\_work\1\s\generated\com.google.android.play.core\obj\Release\monoandroid12.0\generated\src\Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper.cs:286 
  at Java.Interop.EventHelper.AddEventHandler[TInterface,TImplementor] (System.WeakReference& implementor, System.Func`1[TResult] creator, System.Action`1[T] setListener, System.Action`1[T] add) [0x00021] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/EventHelper.cs:16 
  at Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper.add_StateUpdate (System.EventHandler`1[TEventArgs] value) [0x0000d] in C:\a\_work\1\s\generated\com.google.android.play.core\obj\Release\monoandroid12.0\generated\src\Xamarin.Google.Android.Play.Core.AssetPacks.AssetPackStateUpdateListenerWrapper.cs:267 
  at GnollHackClient.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000ab] in C:\Repositories\hyvanmielenpelit\GnollHack\win\win32\winclisrv\GnollHackClient\GnollHackClient.Android\MainActivity.cs:84 
  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: mono.xamarin.google.android.play.core.assetpacks.AssetPackStateUpdateListenerWrapper_AssetPackStateListenerImplementor
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at crc643ccb72c91a5391eb.MainActivity.n_onCreate(Native Method)
	at crc643ccb72c91a5391eb.MainActivity.onCreate(MainActivity.java:46)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.ClassNotFoundException: Didn't find class "mono.xamarin.google.android.play.core.assetpacks.AssetPackStateUpdateListenerWrapper_AssetPackStateListenerImplementor" on path: DexPathList[[zip file "/data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/base.apk"],nativeLibraryDirectories=[/data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/lib/arm64, /data/app/~~K4kX1ILlQwNmneMe31Y06w==/com.soundmindentertainment.gnollhack-2UfOpi9rt_geYTOanfhLCw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
```

After 10 hours of troubleshooting, it turned out that it was caused by the installation path being too long. The original path wasn't too long either:
`C:\Repositories\hyvanmielenpelit\GnollHack`

When I changed it to:
`C:\hmp\GnollHack`
the error went away.

The app has a dependency on the following NuGet package: `Xamarin.Google.Android.Play.Core`. This is the package which causes the problem. 
Its name is not short either, so it might be something to do with it.

Please fix all these weird path-too-long-errors or at least report the root cause to the developer. The error messages and stack traces are pretty useless, since they do not tell the root cause.

I'm not sure if it worked in 17.6.4, or if it was caused by the addition of Xamarin.Google.Android.Play.Core NuGet package to our app.

Best regards,
Tommi

---
#### Feedback Bot on 7/13/2023, 06:17 PM: 

(private comment, text removed)
#### Tommi Gustafsson on 7/15/2023, 06:40 AM: 

(private comment, text removed)
#### Dean Ellis [MSFT] on 7/25/2023, 07:49 AM: 

(private comment, text removed)
#### Tommi Gustafsson on 7/26/2023, 05:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dellis1972** [comment]
So this is a Long File Path issue.
