### ISSUE TITLE
Native crash at `AndroidCryptoNative_SSLStreamShutdown`

### ISSUE THREAD

**Issue by akravch** [xamarin/xamarin-android#8755]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8.0.200/34.0.79

### Description

We are getting NDK crashes with the following stack traces:

```
libaot-System.Net.Security.dll.so                   0xbcfd7fc4 + 61380
libmonosgen-2.0.so                                  mono_thread_is_foreign
libart.so                                           0xf0b36dbf + 2833855
libaot-System.Net.Security.dll.so                   0xbcffe92a + 219434
libSystem.Security.Cryptography.Native.Android.so   AndroidCryptoNative_SSLStreamShutdown
libSystem.Security.Cryptography.Native.Android.so   AndroidCryptoNative_SSLStreamWrite
libSystem.Security.Cryptography.Native.Android.so   AndroidCryptoNative_SSLStreamRead
libaot-System.Private.CoreLib.dll.so                0xc9e965be + 2942398
libaot-System.Private.CoreLib.dll.so                0xc9e9670a + 2942730
libaot-System.Net.Security.dll.so                   0xbcfcb3c6 + 9158
libaot-System.Net.Security.dll.so                   0xbcfcb4aa + 9386
libaot-System.Net.Security.dll.so                   0xbcffd192 + 213394
libaot-System.Private.CoreLib.dll.so                0xc9bde0aa + 90282
libaot-System.Private.CoreLib.dll.so                0xc9c171ca + 324042
libaot-System.Private.Uri.dll.so                    0xbe23ec82 + 85122
libaot-System.Net.Security.dll.so                   0xbcfe6886 + 120966
libmonosgen-2.0.so                                  mono_monitor_enter
libaot-System.Net.Security.dll.so                   0xbcfe179a + 100250
libmonosgen-2.0.so                                  mono_find_seq_point
```

```
libaot-System.Net.Security.dll.so                   0xead33c04 + 56324
libaot-System.Net.Security.dll.so                   0xead33ba0 + 56224
libaot-System.Net.Security.dll.so                   0xead580fc + 205052
libSystem.Security.Cryptography.Native.Android.so   AndroidCryptoNative_SSLStreamShutdown
libaot-System.Net.Security.dll.so                   0xead28150 + 8528
libaot-System.Net.Security.dll.so                   0xead28228 + 8744
libaot-System.Net.Security.dll.so                   0xead56a94 + 199316
libaot-System.Net.Security.dll.so                   0xead4149c + 111772
libaot-System.Net.Security.dll.so                   0xead3cb8c + 93068
libaot-System.Net.Security.dll.so                   0xead3c2c8 + 90824
libaot-System.Net.Http.dll.so                       0xebd9d524 + 197924
libaot-System.Net.Http.dll.so                       0xebd9d3bc + 197564
libaot-System.Net.Http.dll.so                       0xebdb3858 + 288856
libaot-System.Net.Http.dll.so                       0xebd996a4 + 181924
libaot-System.Net.Http.dll.so                       0xebde84f4 + 505076
libaot-System.Net.Http.dll.so                       0xebde83e0 + 504800
libaot-System.Net.Http.dll.so                       0xebdfb600 + 583168
libaot-System.Net.Http.dll.so                       0xebde7590 + 501136
libaot-System.Net.Http.dll.so                       0xebde863c + 505404
libaot-System.Net.Http.dll.so                       0xebde8924 + 506148
libaot-System.Net.Http.dll.so                       0xebdfd8a8 + 592040
libaot-System.Net.Http.dll.so                       0xebdfde04 + 593412
libaot-System.Net.Http.dll.so                       0xebde4e68 + 491112
libaot-System.Net.Http.dll.so                       0xebd8cb5c + 129884
libaot-System.Net.Http.dll.so                       0xebe17b80 + 699264
libaot-System.Net.Http.dll.so                       0xebe03054 + 614484
libaot-System.Net.Http.dll.so                       0xebe02b34 + 613172
libaot-System.Net.Http.dll.so                       0xebd8cb5c + 129884
libaot-System.Net.Http.dll.so                       0xebe04c3c + 621628
libaot-System.Net.Http.dll.so                       0xebd7c4f4 + 62708
libaot-System.Net.Http.dll.so                       0xebd7532c + 33580
libaot-<app-name>.dll.so                            0xf26ff8a8 + 460968
libaot-<app-name>.dll.so                            0xf26ffa60 + 461408
libaot-<app-name>.dll.so                            0xf26ff734 + 460596
libaot-<app-name>.dll.so                            0xf26ff614 + 460308
libaot-System.Net.Http.dll.so                       0xebd7532c + 33580
libaot-<app-name>.dll.so                            0xf2702d08 + 474376
libaot-<app-name>.dll.so                            0xf2702e30 + 474672
libaot-<app-name>.dll.so                            0xf27024a0 + 472224
libaot-<app-name>.dll.so                            0xf2701ee8 + 470760
libaot-System.Net.Http.dll.so                       0xebd82164 + 86372
libaot-System.Net.Http.dll.so                       0xebd79278 + 49784
libaot-System.Net.Http.dll.so                       0xebd795e4 + 50660
libaot-System.Net.Http.dll.so                       0xebd79410 + 50192
libaot-System.Net.Http.dll.so                       0xebd7823c + 45628
libaot-System.Net.Http.dll.so                       0xebd77d64 + 44388
libaot-System.Net.Http.dll.so                       0xebd77cd8 + 44248
libaot-<app-name>.dll.so                            0xf270a91c + 506140
libaot-<app-name>.dll.so                            0xf270a144 + 504132
libaot-<app-name>.dll.so                            0xf270a040 + 503872
libaot-<app-name>.dll.so                            0xf270a3a4 + 504740
libaot-<app-name>.dll.so                            0xf2dde734 + 575284
libaot-System.Private.CoreLib.dll.so                0xf863298c + 2206092
libaot-System.Private.CoreLib.dll.so                0xf866e684 + 2451076
libaot-System.Private.CoreLib.dll.so                0xf8662b20 + 2403104
libaot-System.Private.CoreLib.dll.so                0xf8662784 + 2402180
libaot-System.Private.CoreLib.dll.so                0xf866245c + 2401372
libaot-System.Private.CoreLib.dll.so                0xf86717a8 + 2463656
libaot-System.Private.CoreLib.dll.so                0xf865c020 + 2375712
libaot-System.Private.CoreLib.dll.so                0xf865b968 + 2373992
libaot-System.Private.CoreLib.dll.so                0xf865bd14 + 2374932
libaot-System.Private.CoreLib.dll.so                0xf864468c + 2279052
libaot-System.Private.CoreLib.dll.so                0xf86548b4 + 2345140
libaot-System.Private.CoreLib.dll.so                0xf8627688 + 2160264
libmonosgen-2.0.so                                  mono_get_runtime_build_info
libmonosgen-2.0.so                                  mono_thread_internal_is_current
libc.so                                             0xa8a8ea54 + 432724
libc.so                                             0xa8a8ea54 + 432724
libc.so                                             0xa8a43e7c + 126588
```

The app is in AOT, but LLVM is not enabled.

We tried publishing the app with both native and managed HTTP handlers, and in any case we still see these crashes.

### Steps to Reproduce

Unfortunately, we don't have a repro and only seeing this in the production crash logs.

### Did you find any workaround?

No.

**Comment by simonrozsival** [comment]
> We tried publishing the app with both native and managed HTTP handlers, and in any case we still see these crashes.

@akravch This is quite interesting. Both of these stack traces are from apps that use the managed HTTP handler, aren't they? Do you have a stack trace from an app with the native handler?

**Comment by akravch** [comment]
> Both of these stack traces are from apps that use the managed HTTP handler, aren't they?

Yes, they both are.

Unfortunately, our stack traces from the native handler build are symbolificated even worse than the ones I posted before, even the library names are indistinguishable. Although bu the structure it's very close to the second one I posted in my previous message, so I guess they should be same.

<details><summary>Stack trace</summary>
<p>

```
split_config.arm64_v8a.apk                            0x697319a4 + 22948
split_config.arm64_v8a.apk                            0x69731940 + 22848
split_config.arm64_v8a.apk                            0x69750f8c + 151436
libSystem.Security.Cryptography.Native.Android.so     AndroidCryptoNative_SSLStreamShutdown
split_config.arm64_v8a.apk                            0x6972db00 + 6912
split_config.arm64_v8a.apk                            0x6972dbd8 + 7128
split_config.arm64_v8a.apk                            0x69750314 + 148244
split_config.arm64_v8a.apk                            0x6973e05c + 73820
split_config.arm64_v8a.apk                            0x697397bc + 55228
split_config.arm64_v8a.apk                            0x69738e04 + 52740
split_config.arm64_v8a.apk                            0xdc2a4014 + 8212
split_config.arm64_v8a.apk                            0xdc2a3f28 + 7976
split_config.arm64_v8a.apk                            0xdc2ac840 + 43072
split_config.arm64_v8a.apk                            0xdc2a55b4 + 13748
split_config.arm64_v8a.apk                            0xdc2a3e28 + 7720
split_config.arm64_v8a.apk                            0xdc2ae9d8 + 51672
split_config.arm64_v8a.apk                            0xdc467224 + 160292
split_config.arm64_v8a.apk                            0xdc46127c + 135804
split_config.arm64_v8a.apk                            0xdc4669d0 + 158160
split_config.arm64_v8a.apk                            0x35afb5c + 2190172
split_config.arm64_v8a.apk                            0x35eb9fc + 2435580
split_config.arm64_v8a.apk                            0x35e1054 + 2392148
split_config.arm64_v8a.apk                            0x35e0e48 + 2391624
split_config.arm64_v8a.apk                            0x35de798 + 2381720
split_config.arm64_v8a.apk                            0x35de728 + 2381608
split_config.arm64_v8a.apk                            0x35de380 + 2380672
split_config.arm64_v8a.apk                            0x35de2c8 + 2380488
split_config.arm64_v8a.apk                            0x35df2c4 + 2384580
split_config.arm64_v8a.apk                            0x35df020 + 2383904
split_config.arm64_v8a.apk                            0x35def20 + 2383648
split_config.arm64_v8a.apk                            0x35c1838 + 2263096
split_config.arm64_v8a.apk                            0x35d1504 + 2327812
split_config.arm64_v8a.apk                            0x35a4fa8 + 2146216
libmonosgen-2.0.so                                    mono_get_runtime_build_info
libmonosgen-2.0.so                                    mono_thread_internal_is_current
libc.so                                               0x30e16f7c + 794492
```

</p>
</details> 

Also, in our application logs for some of there crashes with the native handler I see that exceptions were thrown internally just before the crash, but they are handled by our code and should not crash the app. Not sure if it's related to the native crash or just a coincidence:

<details><summary>Exceptions</summary>
<p>

```
 ---> System.Net.Http.HttpRequestException: Connection failure
 ---> Java.IO.IOException: Unable to resolve host "<app-host>": No address associated with hostname
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
   at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect()
   at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass133_0.<ConnectAsync>b__0()
  --- End of managed Java.IO.IOException stack trace ---
java.net.UnknownHostException: Unable to resolve host "<app-host>": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)

  --- End of managed Java.IO.IOException stack trace ---
java.net.UnknownHostException: Unable to resolve host "<app-host>": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)

   Exception_EndOfInnerExceptionStack
   at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass133_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState)
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at <app-code>
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at <app-code>
   at <app-code>
   Exception_EndOfInnerExceptionStack
```
```
System.Net.WebException: Socket closed
 ---> Java.Net.SocketException: Socket closed
   at Java.Interop.JniEnvironment.InstanceMethods.CallIntMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualInt32Method(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
   at Java.Net.HttpURLConnection.get_ResponseCode()
   at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass136_0.<DoProcessRequest>b__2()
   at System.Threading.Tasks.Task`1[[System.Net.HttpStatusCode, System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState)
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  --- End of managed Java.Net.SocketException stack trace ---
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)

  --- End of managed Java.Net.SocketException stack trace ---
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)

   Exception_EndOfInnerExceptionStack
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at <app-code>
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at <app-code>
   at <app-code>
```

</p>
</details>

So are you saying we shouldn't see calls to `libSystem.Security.Cryptography.Native.Android.so` when using the native handler at all? I wonder if it can be just some dependency we reference that instantiates `SocketsHttpHandler` explicitly then...

**Comment by simonrozsival** [comment]
> So are you saying we shouldn't see calls to libSystem.Security.Cryptography.Native.Android.so when using the native handler at all?

Yes, those code paths are only used in the managed handler and not in the native handler. The exceptions that have the java stacktraces and `Xamarin.Android.Net.AndroidMessageHandler` mentioned in them come from the native handler.

> Unable to resolve host "<app-host>": ...

This looks suspicious. Is that a string that you could somehow pass to the handler (by accident I assume)? Even if that were the case, I'm not sure why the app would crash.

**Comment by simonrozsival** [comment]
@akravch thanks for the clarification. Unfortunately, there's not much to go by at the moment and unless we're able to reproduce the issue, I don't think we can fix it. Since the app crashes with both the native and managed handler, which are both implemented in a very different way, it makes me wonder if this is caused by some unexpected behavior of your server or global networking configuration of the device (proxy, VPN, DNS settings) that causes the app to crash.

**Comment by akravch** [comment]
I guess it's best for us to switch back to the native handler then, since it at least gives us less of these crashes. Thanks for you assist @simonrozsival!

If I can find a repro, I'll reopen the issue.
